buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        // classpath 'io.github.gradle-nexus:publish-plugin:1.1.0'
    }
}
plugins {
    id 'com.android.library'
    id 'de.undercouch.download' version '5.1.1' // plugin to download files
}


// Get properties passed from the command line
def aarUrlPath = project.findProperty("aarUrl")
def libVersion = project.findProperty("version")

// Check for required properties
if (!aarUrlPath) {
    throw new GradleException("ERROR: Missing required property 'aarUrl'. Usage: -PaarUrl=https://github.com/username/repo/releases/download/v1.0.0/mylibrary.aar")
}

if (!libVersion) {
    throw new GradleException("ERROR: Missing required property 'version'. Usage: -Pversion=1.0.0")
}

// Optional: check if the .aar file actually exists
// if (!file(aarFilePath).exists()) {
//     throw new GradleException("ERROR: The specified aarFile does not exist at path: $aarFilePath")
// }


android {
    compileSdk 34

    defaultConfig {
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName libVersion
    }
}

repositories {
    google()
    mavenCentral()
}



// Where to store downloaded aar
def aarFile = file("$buildDir/libs/mylibrary.aar")

// Task to download the .aar
tasks.register('downloadAAR', de.undercouch.gradle.tasks.download.Download) {
    src aarUrlPath
    dest aarFile
    overwrite true
}

dependencies {
    implementation files(aarFile)
}

// Make sure download runs before any build
tasks.whenTaskAdded { task ->
    if (task.name.startsWith('assemble') || task.name.startsWith('bundle')) {
        task.dependsOn tasks.named('downloadAAR')
    }
}

// Optional: publish block if you want JitPack to see it as a library
publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.massifmaps'
            artifactId = 'massif'
            version = libVersion
            artifact(aarFile) {
                extension = 'aar'
            }
        }
    }
    // repositories {
    //     maven {
    //         name = "GitHubPackages"
    //         url = uri("https://maven.pkg.github.com/massif-maps/MassifMaps")
    //         credentials {
    //             username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
    //             password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
    //         }
    //     }
    // }
}