/* Generated by massif-style mapbox2css. Do not edit by hand:
   re-run the converter against the source style instead. */
/* Colours, fonts and shared sizes live in variables.mss. */
/* Source style: Streets */

Map {
  background-color: linear(([view::zoom] - 1), (6, @background_2), (14, @background));
  background-emissive-strength: 0;
}

#globallandcover[zoom < 9][class = 'grass']::Meadow {
  polygon-fill: @meadow_fill;
  polygon-opacity: linear(([view::zoom] - 1), (0, 1), (8, 0.1));
  polygon-emissive-strength: 0;
}
#globallandcover[zoom < 9][class = 'scrub']::Scrub {
  polygon-fill: @scrub_fill;
  polygon-opacity: linear(([view::zoom] - 1), (0, 1), (8, 0.1));
  polygon-emissive-strength: 0;
}
#globallandcover[zoom < 9][class = 'crop']::Crop {
  polygon-fill: @crop_fill;
  polygon-opacity: linear(([view::zoom] - 1), (0, 1), (8, 0.1));
  polygon-emissive-strength: 0;
}
#landuse when(([class] = 'residential' || [class] = 'suburbs' || [class] = 'neighbourhood'))::Residential {
  polygon-fill: linear(([view::zoom] - 1), (4, @residential_fill), (16, @residential_fill_2));
  polygon-emissive-strength: 0;
}
#landcover[class = 'ice']::Glacier {
  polygon-fill: @shield_halo_fill;
  polygon-opacity: linear(([view::zoom] - 1), (0, 1), (10, 0.7));
  polygon-emissive-strength: 0;
}
#globallandcover[zoom < 9] when(([class] = 'forest' || [class] = 'tree'))::Forest {
  polygon-fill: @forest_fill;
  polygon-opacity: linear(([view::zoom] - 1), (1, 0.8), (8, 0));
  polygon-emissive-strength: 0;
}
#landcover[class = 'sand']::Sand {
  polygon-fill: @sand_fill;
  polygon-opacity: @polygon_fill_opacity;
  polygon-emissive-strength: 0;
}
#landcover[class = 'wood']::Wood {
  polygon-fill: @wood_fill;
  polygon-opacity: 1;
  polygon-emissive-strength: 0;
}
#landuse[zoom < 25] when(([class] = 'industrial' || [class] = 'quarry'))::Industrial {
  polygon-fill: linear(([view::zoom] - 1), (9, (([class] = 'industrial') ? @industrial_fill_2 : (([class] = 'quarry') ? @industrial_fill_3 : @industrial_fill))), (16, (([class] = 'industrial') ? @industrial_fill_4 : (([class] = 'quarry') ? @industrial_fill_5 : @industrial_fill))));
  polygon-opacity: step(([view::zoom] - 1), (0, 1), (9, (([class] = 'quarry') ? 0 : 1)), (10, 1));
  polygon-emissive-strength: 0;
}
#landcover[class = 'grass']::Grass {
  polygon-fill: @grass_fill;
  polygon-opacity: @line_stroke_opacity;
  polygon-emissive-strength: 0;
}
#aeroway[zoom >= 12]['mapnik::geometry_type' = 3]::Airport_zone {
  polygon-fill: @airport_zone_fill;
  polygon-opacity: 1;
  polygon-emissive-strength: 0;
}
#transportation['mapnik::geometry_type' = 3][brunnel = null] when(([class] != 'bridge' ? [class] != 'pier' : false)) when(([subclass] = 'pedestrian' || [subclass] = 'platform'))::Pedestrian {
  polygon-fill: @pedestrian_fill;
  polygon-opacity: 0.7;
  polygon-emissive-strength: 0;
}
#landuse[zoom >= 10][class = 'cemetery']::Cemetery {
  polygon-fill: @cemetery_fill;
  polygon-opacity: linear(([view::zoom] - 1), (9, 0.25), (16, 1));
  polygon-emissive-strength: 0;
}
#landuse[zoom >= 10][class = 'hospital']::Hospital {
  polygon-fill: @hospital_fill;
  polygon-opacity: linear(([view::zoom] - 1), (9, 0.25), (16, 1));
  polygon-emissive-strength: 0;
}
#landuse[zoom >= 10] when(([class] = 'pitch' || [class] = 'stadium' || [class] = 'playground'))::Stadium {
  polygon-fill: @stadium_fill;
  polygon-opacity: linear(([view::zoom] - 1), (9, 0.25), (16, 1));
  polygon-emissive-strength: 0;
}
#landuse[zoom >= 10] when(([class] = 'college' || [class] = 'school' || [class] = 'university'))::School {
  polygon-fill: @school_fill;
  polygon-opacity: linear(([view::zoom] - 1), (9, 0.25), (16, 1));
  polygon-emissive-strength: 0;
}
#waterway[zoom >= 15][brunnel = 'tunnel']::River_tunnel {
  line-cap: 'round';
  line-color: @river_stroke;
  line-dasharray: 15.92,31.84;
  line-opacity: @line_stroke_opacity;
  line-width: linear(([view::zoom] - 1), (12, 0.5), (20, 6));
  line-emissive-strength: 0;
}
#waterway[brunnel != 'tunnel']::River {
  line-cap: 'round';
  line-color: @river_stroke;
  line-width: linear(([view::zoom] - 1), (12, 0.5), (20, 6));
  line-emissive-strength: 0;
}
#water[intermittent = 1]::Water_intermittent {
  polygon-fill: @water_intermittent_fill;
  polygon-opacity: @polygon_fill_opacity;
  polygon-emissive-strength: 0;
}
#water[intermittent != 1]::Water {
  polygon-fill: @polygon_fill;
  polygon-opacity: (([intermittent] = 1) ? 0.85 : 1);
  polygon-emissive-strength: 0;
}
#aeroway[zoom >= 12]::Aeroway {
  line-color: @shield_halo_fill;
  line-width: linear(([view::zoom] - 1), (11, (([class] = 'runway') ? 3 : 0.5)), (20, (([class] = 'runway') ? 16 : 6)));
  line-emissive-strength: 0;
}
#aeroway[zoom >= 12] when(([class] = 'helipad' || [class] = 'heliport'))::Heliport {
  polygon-fill: @shield_halo_fill;
  polygon-opacity: 1;
  polygon-emissive-strength: 0;
}
#transportation[zoom >= 7][class = 'ferry']::Ferry_line {
  line-join: 'round';
  line-color: linear(([view::zoom] - 1), (10, @ferry_line_stroke), (16, @ferry_line_stroke_2));
  line-dasharray: 12.8,12.8;
  line-opacity: linear(([view::zoom] - 1), (6, 0.5), (7, 0.8), (8, 1));
  line-width: linear(([view::zoom] - 1), (10, 0.5), (14, 1.1));
  line-emissive-strength: 0;
}
#transportation[zoom >= 5][brunnel = 'tunnel'] when(([class] != 'bridge' ? ([class] != 'ferry' ? ([class] != 'rail' ? ([class] != 'transit' ? ([class] != 'pier' ? ([class] != 'path' ? ([class] != 'aerialway' ? ([class] != 'motorway_construction' ? ([class] != 'trunk_construction' ? ([class] != 'primary_construction' ? ([class] != 'secondary_construction' ? ([class] != 'tertiary_construction' ? ([class] != 'minor_construction' ? ([class] != 'service_construction' ? [class] != 'track_construction' : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false))::Tunnel_outline {
  line-cap: 'butt';
  line-join: 'round';
  line-color: (([class] = 'motorway') ? @outline_stroke : (([class] = 'trunk' || [class] = 'primary') ? @outline_stroke : @outline_stroke_2));
  line-dasharray: 3.49,1.75;
  line-width: linear(([view::zoom] - 1), (6, 0), (7, 0.5), (10, (([class] = 'motorway') ? (([ramp] = 1) ? 0 : 2.5) : (([class] = 'trunk' || [class] = 'primary') ? 2 : 0))), (12, (([class] = 'motorway') ? (([ramp] = 1) ? 2 : 6) : (([class] = 'trunk' || [class] = 'primary') ? 3 : (([class] = 'secondary' || [class] = 'tertiary') ? 2 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 1 : 0.5))))), (14, (([class] = 'motorway') ? (([ramp] = 1) ? 5 : 8) : (([class] = 'trunk') ? 4 : (([class] = 'primary') ? 6 : (([class] = 'secondary') ? 6 : (([class] = 'tertiary') ? 4 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 3 : 3))))))), (16, (([class] = 'motorway' || [class] = 'trunk' || [class] = 'primary') ? 10 : (([class] = 'secondary') ? 8 : (([class] = 'tertiary') ? 8 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 4 : 4))))), (20, (([class] = 'motorway' || [class] = 'trunk' || [class] = 'primary') ? 26 : (([class] = 'secondary') ? 26 : (([class] = 'tertiary') ? 26 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 18 : 18))))));
  line-emissive-strength: 0;
}
#transportation[zoom >= 5][brunnel = 'tunnel'] when(([class] != 'ferry' ? ([class] != 'rail' ? ([class] != 'transit' ? ([class] != 'pier' ? ([class] != 'bridge' ? ([class] != 'path' ? ([class] != 'aerialway' ? ([class] != 'motorway_construction' ? ([class] != 'trunk_construction' ? ([class] != 'primary_construction' ? ([class] != 'secondary_construction' ? ([class] != 'tertiary_construction' ? ([class] != 'minor_construction' ? ([class] != 'service_construction' ? [class] != 'track_construction' : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false))::Tunnel {
  line-cap: 'butt';
  line-join: 'round';
  line-color: (([class] = 'motorway') ? @line_stroke : (([class] = 'trunk' || [class] = 'primary') ? @tunnel_stroke : @tunnel_stroke_2));
  line-opacity: 1;
  line-width: linear(([view::zoom] - 1), (5, 0), (6, (([class] = 'motorway') ? (([brunnel] = 'bridge') ? 0 : 1) : (([class] = 'trunk' || [class] = 'primary') ? 0 : 0))), (10, (([class] = 'motorway') ? (([ramp] = 1) ? 0 : 2.5) : (([class] = 'trunk' || [class] = 'primary') ? 1.5 : 1))), (12, (([class] = 'motorway') ? (([ramp] = 1) ? 1 : 4) : (([class] = 'trunk') ? 2.5 : (([class] = 'primary') ? 2.5 : (([class] = 'secondary' || [class] = 'tertiary') ? 1.5 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 1 : 1)))))), (14, (([class] = 'motorway') ? (([ramp] = 1) ? 5 : 6) : (([class] = 'trunk') ? 3 : (([class] = 'primary') ? 5 : (([class] = 'secondary') ? 4 : (([class] = 'tertiary') ? 3 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 2 : 2))))))), (16, (([class] = 'motorway' || [class] = 'trunk' || [class] = 'primary') ? 8 : (([class] = 'secondary') ? 7 : (([class] = 'tertiary') ? 6 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 4 : 4))))), (20, (([class] = 'motorway' || [class] = 'trunk' || [class] = 'primary') ? 24 : (([class] = 'secondary') ? 24 : (([class] = 'tertiary') ? 24 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 16 : 16))))));
  line-emissive-strength: 0;
}
#transportation[brunnel = 'tunnel'][class = 'rail']::Railway_tunnel {
  line-color: @line_stroke_2;
  line-opacity: @line_stroke_opacity;
  line-width: linear(([view::zoom] - 1), (14, 0.4), (15, 0.75), (20, 2));
  line-emissive-strength: 0;
}
#transportation[brunnel = 'tunnel'][class = 'rail']::Railway_tunnel_hatching {
  line-color: @line_stroke_2;
  line-dasharray: 2.06,82.53;
  line-opacity: @line_stroke_opacity;
  line-width: linear(([view::zoom] - 1), (14.5, 0), (15, 3), (20, 8));
  line-emissive-strength: 0;
}
#transportation[zoom >= 13]['mapnik::geometry_type' = 2] when(([class] = 'path' || [class] = 'pedestrian'))[brunnel = 'tunnel']::Footway_tunnel_outline {
  line-cap: 'round';
  line-join: 'miter';
  line-color: @shield_halo_fill;
  line-opacity: 1;
  line-width: linear(([view::zoom] - 1), (14, 0), (16, 0), (18, 4), (22, 8));
  line-emissive-strength: 0;
}
#transportation[zoom >= 13]['mapnik::geometry_type' = 2] when(([class] = 'path' || [class] = 'pedestrian'))[brunnel = 'tunnel']::Footway_tunnel {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @line_stroke_3;
  line-dasharray: 8.86,2.21;
  line-opacity: @building_stroke_opacity;
  line-width: linear(([view::zoom] - 1), (14, 0.5), (16, 1), (18, 2), (22, 5));
  line-emissive-strength: 0;
}
#transportation['mapnik::geometry_type' = 3][class = 'pier']::Pier {
  polygon-fill: @background;
  polygon-emissive-strength: 0;
}
#transportation['mapnik::geometry_type' = 2][class = 'pier']::Pier_road {
  line-cap: 'round';
  line-join: 'round';
  line-color: @background;
  line-width: linear(([view::zoom] - 1), (15, 1), (17, 4));
  line-emissive-strength: 0;
}
#transportation[zoom >= 14][zoom < 18][brunnel != 'tunnel'] when(([class] = 'motorway' || [class] = 'primary' || [class] = 'trunk'))::Bridge_outline {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @bridge_outline_stroke;
  line-opacity: @line_stroke_opacity;
  line-width: linear(([view::zoom] - 1), (13, (([class] = 'trunk' || [class] = 'primary') ? 5 : 8)), (15, (([class] = 'trunk' || [class] = 'primary') ? 15 : 22)), (17, (([class] = 'trunk' || [class] = 'primary') ? 20 : 24)));
  line-emissive-strength: 0;
}
#transportation['mapnik::geometry_type' = 3][brunnel = 'bridge']::Bridge {
  polygon-fill: @background;
  polygon-opacity: 0.6;
  polygon-emissive-strength: 0;
}
#transportation[zoom >= 5][brunnel != 'tunnel'] when(([class] != 'aerialway' ? ([class] != 'bridge' ? ([class] != 'ferry' ? ([class] != 'minor_construction' ? ([class] != 'motorway' ? ([class] != 'motorway_construction' ? ([class] != 'path' ? ([class] != 'path_construction' ? ([class] != 'pier' ? ([class] != 'primary' ? ([class] != 'primary_construction' ? ([class] != 'rail' ? ([class] != 'secondary_construction' ? ([class] != 'service_construction' ? ([class] != 'tertiary_construction' ? ([class] != 'track_construction' ? ([class] != 'transit' ? [class] != 'trunk_construction' : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false))::Minor_road_outline {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @outline_stroke_2;
  line-opacity: 1;
  line-width: linear(([view::zoom] - 1), (6, 0), (7, 0.5), (12, (([class] = 'secondary' || [class] = 'tertiary') ? 2 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 1 : 0.5))), (14, (([class] = 'secondary') ? 6 : (([class] = 'tertiary') ? 4 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 3 : 3)))), (16, (([class] = 'secondary') ? 8 : (([class] = 'tertiary') ? 8 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 4 : 4)))), (20, (([class] = 'secondary') ? 26 : (([class] = 'tertiary') ? 26 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 18 : 18)))));
  line-emissive-strength: 0;
}
#transportation[zoom >= 5][brunnel != 'tunnel'] when(([class] = 'primary' || [class] = 'trunk'))::Major_road_outline {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @outline_stroke;
  line-opacity: 1;
  line-width: linear(([view::zoom] - 1), (6, 0), (7, 0.5), (10, (([class] = 'trunk' || [class] = 'primary') ? 2.4 : 0)), (12, (([class] = 'trunk' || [class] = 'primary') ? 3 : 0.5)), (14, (([class] = 'trunk') ? 4 : (([class] = 'primary') ? 6 : 3))), (16, (([class] = 'trunk' || [class] = 'primary') ? 10 : 4)), (20, (([class] = 'trunk' || [class] = 'primary') ? 26 : 18)));
  line-emissive-strength: 0;
}
#transportation[zoom >= 5][brunnel != 'tunnel'][class = 'motorway']::Highway_outline {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @outline_stroke;
  line-opacity: 1;
  line-width: linear(([view::zoom] - 1), (6, 0), (7, 0.5), (10, (([class] = 'motorway') ? (([ramp] = 1) ? 0 : 2.5) : 0)), (12, (([class] = 'motorway') ? (([ramp] = 1) ? 2 : 6) : 0.5)), (14, (([class] = 'motorway') ? (([ramp] = 1) ? 5 : 8) : 3)), (16, (([class] = 'motorway') ? 10 : 4)), (20, (([class] = 'motorway') ? 26 : 18)));
  line-emissive-strength: 0;
}
#transportation[zoom >= 5] when(([class] = 'motorway_construction' || [class] = 'trunk_construction' || [class] = 'primary_construction' || [class] = 'secondary_construction' || [class] = 'tertiary_construction' || [class] = 'minor_construction' || [class] = 'service_construction' || [class] = 'track_construction'))::Road_under_construction {
  line-cap: 'square';
  line-join: 'round';
  line-color: (([class] = 'motorway_construction') ? @line_stroke : (([class] = 'trunk_construction' || [class] = 'primary_construction') ? @road_stroke : @shield_halo_fill));
  line-dasharray: 11.56,11.56;
  line-opacity: (([brunnel] = 'tunnel') ? 0.7 : 1);
  line-width: linear(([view::zoom] - 1), (5, (([class] = 'motorway_construction') ? (([brunnel] = 'bridge') ? 0 : 0.5) : (([class] = 'trunk_construction' || [class] = 'primary_construction') ? 0 : 0))), (10, (([class] = 'motorway_construction') ? (([ramp] = 1) ? 0 : 2.5) : (([class] = 'trunk_construction' || [class] = 'primary_construction') ? 1.5 : 1))), (12, (([class] = 'motorway_construction') ? (([ramp] = 1) ? 1 : 4) : (([class] = 'trunk_construction') ? 2.5 : (([class] = 'primary_construction') ? 2.5 : (([class] = 'secondary_construction' || [class] = 'tertiary_construction') ? 1.5 : (([class] = 'minor_construction' || [class] = 'service_construction' || [class] = 'track_construction') ? 1 : 1)))))), (14, (([class] = 'motorway_construction') ? (([ramp] = 1) ? 5 : 6) : (([class] = 'trunk_construction') ? 3 : (([class] = 'primary_construction') ? 5 : (([class] = 'secondary_construction') ? 4 : (([class] = 'tertiary_construction') ? 3 : (([class] = 'minor_construction' || [class] = 'service_construction' || [class] = 'track_construction') ? 2 : 2))))))), (16, (([class] = 'motorway_construction' || [class] = 'trunk_construction' || [class] = 'primary_construction') ? 8 : (([class] = 'secondary_construction') ? 7 : (([class] = 'tertiary_construction') ? 6 : (([class] = 'minor_construction' || [class] = 'service_construction' || [class] = 'track_construction') ? 4 : 4))))), (20, (([class] = 'motorway_construction' || [class] = 'trunk_construction' || [class] = 'primary_construction') ? 24 : (([class] = 'secondary_construction') ? 24 : (([class] = 'tertiary_construction') ? 24 : (([class] = 'minor_construction' || [class] = 'service_construction' || [class] = 'track_construction') ? 16 : 16))))));
  line-emissive-strength: 0;
}
#transportation[zoom >= 5][brunnel != 'tunnel'] when(([class] != 'aerialway' ? ([class] != 'bridge' ? ([class] != 'ferry' ? ([class] != 'minor_construction' ? ([class] != 'motorway' ? ([class] != 'motorway_construction' ? ([class] != 'path' ? ([class] != 'path_construction' ? ([class] != 'pier' ? ([class] != 'primary' ? ([class] != 'primary_construction' ? ([class] != 'rail' ? ([class] != 'secondary_construction' ? ([class] != 'service_construction' ? ([class] != 'tertiary_construction' ? ([class] != 'track_construction' ? ([class] != 'transit' ? [class] != 'trunk_construction' : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false) : false))::Minor_road {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @shield_halo_fill;
  line-width: linear(([view::zoom] - 1), (5, 0.5), (10, 1), (12, (([class] = 'secondary' || [class] = 'tertiary') ? 1.5 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 1 : 1))), (14, (([class] = 'secondary') ? 4 : (([class] = 'tertiary') ? 3 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 2 : 2)))), (16, (([class] = 'secondary') ? 7 : (([class] = 'tertiary') ? 6 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 4 : 4)))), (20, (([class] = 'secondary') ? 24 : (([class] = 'tertiary') ? 24 : (([class] = 'minor' || [class] = 'service' || [class] = 'track') ? 16 : 16)))));
  line-emissive-strength: 0;
}
#transportation[zoom >= 5][brunnel != 'tunnel'] when(([class] = 'primary' || [class] = 'trunk'))::Major_road {
  line-cap: 'butt';
  line-join: 'round';
  line-color: linear(([view::zoom] - 1), (6, @line_stroke), (8, @road_stroke));
  line-width: linear(([view::zoom] - 1), (6, 0.75), (10, (([class] = 'trunk' || [class] = 'primary') ? 1.5 : 1)), (12, (([class] = 'trunk' || [class] = 'primary') ? 2.5 : 1)), (14, (([class] = 'trunk') ? 3 : (([class] = 'primary') ? 5 : 2))), (16, (([class] = 'trunk' || [class] = 'primary') ? 8 : 4)), (20, (([class] = 'trunk' || [class] = 'primary') ? 24 : 16)));
  line-emissive-strength: 0;
}
#transportation[zoom >= 5][brunnel != 'tunnel'][class = 'motorway']::Highway {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @line_stroke;
  line-width: linear(([view::zoom] - 1), (5, 0.5), (6, (([class] = 'motorway') ? (([brunnel] = 'bridge') ? 0 : 1) : 0)), (10, (([class] = 'motorway') ? (([ramp] = 1) ? 0 : 2.5) : 1)), (12, (([class] = 'motorway') ? (([ramp] = 1) ? 1 : 4) : 1)), (14, (([class] = 'motorway') ? (([ramp] = 1) ? 5 : 6) : 2)), (16, (([class] = 'motorway') ? 8 : 4)), (20, (([class] = 'motorway') ? 24 : 16)));
  line-emissive-strength: 0;
}
#transportation[zoom >= 13]['mapnik::geometry_type' = 2] when(([class] = 'path' || [class] = 'pedestrian'))[brunnel != 'tunnel']::Path_outline {
  line-cap: 'round';
  line-join: 'miter';
  line-color: @shield_halo_fill;
  line-width: linear(([view::zoom] - 1), (14, 0), (16, 0), (18, 4), (22, 8));
  line-emissive-strength: 0;
}
#transportation[zoom >= 13]['mapnik::geometry_type' = 2][class = 'path_pedestrian'][brunnel != 'tunnel']::Path_minor {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @path_stroke;
  line-dasharray: 8.86,2.21;
  line-width: linear(([view::zoom] - 1), (14, 0.5), (16, 1), (18, 2), (22, 5));
  line-emissive-strength: 0;
}
#transportation[zoom >= 13]['mapnik::geometry_type' = 2] when(([class] = 'path' || [class] = 'pedestrian'))[brunnel != 'tunnel']::Path {
  line-cap: 'butt';
  line-join: 'round';
  line-color: @path_stroke;
  line-dasharray: 8.86,2.21;
  line-width: linear(([view::zoom] - 1), (14, 0.5), (16, 1), (18, 2), (22, 5));
  line-emissive-strength: 0;
}
#transportation when([brunnel] != 'tunnel')[class = 'rail']::Major_rail {
  line-color: linear(([view::zoom] - 1), (8, @major_rail_stroke), (16, @line_stroke_4));
  line-opacity: (([service] = 'yard') ? 0.5 : 1);
  line-width: linear(([view::zoom] - 1), (14, 0.4), (15, 0.75), (20, 2));
  line-emissive-strength: 0;
}
#transportation when([brunnel] != 'tunnel')[class = 'rail']::Major_rail_hatching {
  line-color: @major_rail_stroke;
  line-dasharray: 2.06,92.85;
  line-opacity: (([service] = 'yard') ? 0.5 : 1);
  line-width: linear(([view::zoom] - 1), (14.5, 0), (15, 3), (20, 8));
  line-emissive-strength: 0;
}
#transportation when(([subclass] = 'light_rail' || [subclass] = 'tram'))::Minor_rail {
  line-color: @line_stroke_2;
  line-width: linear(([view::zoom] - 1), (14, 0.4), (15, 0.75), (20, 2));
  line-emissive-strength: 0;
}
#transportation when(([subclass] = 'tram' || [subclass] = 'light_rail'))::Minor_rail_hatching {
  line-color: @line_stroke_2;
  line-dasharray: 1.96,39.27;
  line-width: linear(([view::zoom] - 1), (14.5, 0), (15, 2), (20, 6));
  line-emissive-strength: 0;
}
#building[zoom >= 14][zoom < 16]['param::buildings'>0]::Building {
  polygon-fill: @building_fill;
  polygon-opacity: 0.3;
  line-color: linear(([view::zoom] - 1), (13, @building_stroke), (14, @building_stroke_2));
  line-width: @building_stroke_opacity;
  polygon-emissive-strength: 0;
  line-emissive-strength: 0;
}
#building[zoom >= 16]['param::buildings'>1][hide_3d = null]::Building_3D {
  building-min-height: [render_min_height];
  building-fill: @building_3d_fill;
  building-height: [render_height];
  building-fill-opacity: @building_stroke_opacity;
}
#waterway[brunnel = 'bridge']::Aqueduct_outline {
  line-cap: 'round';
  line-join: 'round';
  line-color: @aqueduct_outline_stroke;
  line-width: linear(([view::zoom] - 1), (14, 1), (20, 6));
  line-emissive-strength: 0;
}
#waterway['mapnik::geometry_type' = 2][brunnel = 'bridge']::Aqueduct {
  line-cap: 'round';
  line-join: 'round';
  line-color: @polygon_fill;
  line-width: linear(([view::zoom] - 1), (12, 0.5), (20, 5));
  line-emissive-strength: 0;
}
#transportation[zoom >= 14][class = 'aerialway']::Cablecar {
  line-cap: 'round';
  line-blur: 1;
  line-color: @shield_halo_fill;
  line-width: linear(([view::zoom] - 1), (13, 2), (19, 4));
  line-emissive-strength: 0;
}
#transportation[zoom >= 14][class = 'aerialway']::Cablecar_dash {
  line-cap: 'round';
  line-join: 'bevel';
  line-color: @cablecar_dash_stroke;
  line-dasharray: 14.4,14.4;
  line-width: linear(([view::zoom] - 1), (13, 1), (19, 2));
  line-emissive-strength: 0;
}
#boundary[zoom >= 4] when(([admin_level] = 3 || [admin_level] = 4 || [admin_level] = 5 || [admin_level] = 6 || [admin_level] = 7 || [admin_level] = 8))[maritime = 0]::Other_border {
  line-color: @line_stroke_4;
  line-dasharray: 5.45,2.73;
  line-width: linear(([view::zoom] - 1), (3, 0.75), (4, 0.8), (11, (([admin_level] <= 6) ? 1.75 : 1.5)), (18, (([admin_level] <= 6) ? 3 : 2)));
  line-emissive-strength: 0;
}
#boundary[zoom >= 1][admin_level = 2][disputed = 1][maritime = 0]::Disputed_border {
  line-cap: 'round';
  line-join: 'round';
  line-color: @line_stroke_3;
  line-dasharray: 14,14;
  line-width: linear(([view::zoom] - 1), (1, 0.5), (5, 1.5), (10, 2), (24, 12));
  line-emissive-strength: 0;
}
#boundary[zoom >= 1][admin_level = 2][disputed = 0][maritime = 0]::Country_border {
  line-cap: 'round';
  line-join: 'round';
  line-color: @country_border_stroke;
  line-width: linear(([view::zoom] - 1), (1, 0.5), (5, 1.5), (10, 2), (24, 12));
  line-emissive-strength: 0;
}
#waterway[zoom >= 14]['mapnik::geometry_type' = 2]::River_labels {
  text-placement: 'line';
  text-spacing: @river_labels_spacing;
  text-name: ([name:en]) ?? ([name]);
  text-face-name: @font_roboto_italic;
  text-character-spacing: (0.2 * linear(([view::zoom] - 1), (12, 8), (16, 14), (22, 20)));
  text-wrap-width: 0;
  text-size: linear(([view::zoom] - 1), (12, 8), (16, 14), (22, 20));
  text-fill: @labels_fill_2;
  text-halo-fill: @river_labels_halo_fill;
  text-halo-radius: linear(([view::zoom] - 1), (10, 1), (18, 2));
  text-placement-priority: 5700000;
  text-min-distance: @river_labels_spacing;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#water_name[zoom >= 1]['mapnik::geometry_type' = 1][name != null][class != 'lake']::Ocean_labels {
  text-placement: 'billboard';
  text-name: [name:en];
  text-face-name: @font_roboto_italic;
  text-wrap-width: (5 * linear(([view::zoom] - 1), (1, (([class] = 'ocean') ? 14 : 10)), (3, (([class] = 'ocean') ? 18 : 14)), (9, (([class] = 'ocean') ? 22 : 18)), (14, (([class] = 'lake') ? 14 : (([class] = 'sea') ? 20 : 26)))));
  text-size: linear(([view::zoom] - 1), (1, (([class] = 'ocean') ? 14 : 10)), (3, (([class] = 'ocean') ? 18 : 14)), (9, (([class] = 'ocean') ? 22 : 18)), (14, (([class] = 'lake') ? 14 : (([class] = 'sea') ? 20 : 26))));
  text-fill: linear(([view::zoom] - 1), (1, @ocean_labels_fill), (4, @ocean_labels_fill_2));
  text-halo-fill: linear(([view::zoom] - 1), (1, @ocean_labels_halo_fill), (3, @ocean_labels_halo_fill_2));
  text-halo-radius: @text_halo_radius;
  text-opacity: step(([view::zoom] - 1), (0, 0), (1, (([class] = 'ocean') ? 1 : 0)), (3, 1));
  text-halo-opacity: step(([view::zoom] - 1), (0, 0), (1, (([class] = 'ocean') ? 1 : 0)), (3, 1));
  text-placement-priority: 5800000;
  text-min-distance: @text_minimum_distance;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#water_name[zoom >= 1]['mapnik::geometry_type' = 2][class = 'lake']::Lake_labels {
  text-placement: 'line';
  text-name: ([name:en]) ?? ([name]);
  text-face-name: @font_roboto_italic;
  text-character-spacing: (0.1 * linear(([view::zoom] - 1), (10, 13), (14, 16), (22, 20)));
  text-wrap-width: 0;
  text-size: linear(([view::zoom] - 1), (10, 13), (14, 16), (22, 20));
  text-fill: @labels_fill_2;
  text-halo-fill: @lake_labels_halo_fill;
  text-halo-radius: 1.5;
  text-placement-priority: 5900000;
  text-spacing: @text_spacing;
  text-min-distance: @text_spacing;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#housenumber[zoom >= 19]::Housenumber {
  text-placement: 'billboard';
  text-name: [housenumber];
  text-face-name: @font_roboto_regular;
  text-size: 10;
  text-fill: @housenumber_fill;
  text-halo-fill: @housenumber_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-placement-priority: 6000000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: 100;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 14] when(([subclass] = 'gondola' || [subclass] = 'cable_car'))::Gondola {
  text-placement: 'line';
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-name: ([name:en]) ?? ([name]);
  text-face-name: @font_roboto_italic;
  text-dx: (0.8 * linear(([view::zoom] - 1), (13, 11), (15, 12), (18, 13), (22, 14)));
  text-dy: (0.8 * linear(([view::zoom] - 1), (13, 11), (15, 12), (18, 13), (22, 14)));
  text-size: linear(([view::zoom] - 1), (13, 11), (15, 12), (18, 13), (22, 14));
  text-fill: @text_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-placement-priority: 6100000;
  text-spacing: @text_spacing;
  text-min-distance: @text_spacing;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 13][class = 'ferry']::Ferry {
  text-placement: 'line';
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-name: ([name:en]) ?? ([name]);
  text-face-name: @font_roboto_italic;
  text-dx: (0.8 * linear(([view::zoom] - 1), (13, 11), (15, 12)));
  text-dy: (0.8 * linear(([view::zoom] - 1), (13, 11), (15, 12)));
  text-size: linear(([view::zoom] - 1), (13, 11), (15, 12));
  text-fill: @labels_fill_2;
  text-halo-fill: @ferry_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-placement-priority: 6200000;
  text-spacing: @text_spacing;
  text-min-distance: @text_spacing;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation[zoom >= 17][oneway != null] when(([class] = 'motorway' || [class] = 'trunk' || [class] = 'primary' || [class] = 'secondary' || [class] = 'tertiary' || [class] = 'minor' || [class] = 'service'))::Oneway {
  marker-file: url('icons/oneway.png');
  marker-placement: 'line';
  marker-sdf: true;
  marker-width: (linear(([view::zoom] - 1), (16, 0.7), (19, 1)) * 33);
  marker-color: @oneway_color;
  marker-opacity: @line_stroke_opacity;
  marker-halo-opacity: 0.5;
  marker-transform: rotate((([oneway] = 1) ? 0 : 0));
  marker-emissive-strength: 0.45;
  marker-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 9] when(([subclass] != 'gondola' ? [subclass] != 'cable_car' : false)) when(([class] != 'ferry' ? [class] != 'service' : false))::Road_labels {
  text-placement: 'line';
  text-spacing: step(([view::zoom] - 1), (0, 250), (21, 1000));
  text-allow-overlap: false;
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-name: ([name:en]) ?? ([name]);
  text-face-name: @font_roboto_regular;
  text-wrap-width: 0;
  text-dx: (0 * linear(([view::zoom] - 1), (13, 10), (14, 11), (18, 13), (22, 15)));
  text-dy: (0.15 * linear(([view::zoom] - 1), (13, 10), (14, 11), (18, 13), (22, 15)));
  text-size: linear(([view::zoom] - 1), (13, 10), (14, 11), (18, 13), (22, 15));
  text-fill: @road_labels_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-placement-priority: 6400000;
  text-min-distance: step(([view::zoom] - 1), (0, 250), (21, 1000));
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 17][ref_length > 0]['mapnik::geometry_type' = 1][subclass = 'junction']::Highway_junction {
  text-placement: 'billboard';
  text-spacing: @highway_spacing;
  text-name: [ref];
  text-face-name: @font_roboto_regular;
  text-dx: 0;
  text-dy: 0.9;
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-size: @highway_size;
  text-fill: @highway_junction_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-placement-priority: 6500000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: @highway_wrap_width;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 9][ref_length <= 6]['mapnik::geometry_type' = 2] when(([network] != 'us-interstate' ? ([network] != 'us-highway' ? [network] != 'us-state' : false) : false)) when([class] != 'path')[class = 'motorway']::Highway_shield_b1 {
  shield-placement: 'billboard-line-repeat';
  shield-spacing: linear(([view::zoom] - 1), (10, 200), (18, 400));
  shield-name: [ref];
  shield-face-name: @font_roboto_bold;
  shield-text-dx: 0;
  shield-text-dy: 0.5;
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'middle';
  shield-size: 10;
  shield-text-transform: 'uppercase';
  shield-fill: @labels_icon_halo_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @text_halo_radius;
  shield-placement-priority: 6600000;
  shield-min-distance: linear(([view::zoom] - 1), (10, 200), (18, 400));
  shield-file: ([param::icon-road_[ref_length]]);
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shield_halo_fill;
  shield-icon-halo-fill: @labels_icon_halo_fill;
  shield-icon-halo-radius: 1;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 9][ref_length <= 6]['mapnik::geometry_type' = 2] when(([network] != 'us-interstate' ? ([network] != 'us-highway' ? [network] != 'us-state' : false) : false)) when([class] != 'path') when((!([class] = 'motorway')))::Highway_shield_b2 {
  shield-placement: 'billboard-line-repeat';
  shield-spacing: linear(([view::zoom] - 1), (10, 200), (18, 400));
  shield-name: [ref];
  shield-face-name: @font_roboto_regular;
  shield-text-dx: 0;
  shield-text-dy: 0.5;
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'middle';
  shield-size: 10;
  shield-text-transform: 'uppercase';
  shield-fill: @labels_icon_halo_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @text_halo_radius;
  shield-placement-priority: 6600000;
  shield-min-distance: linear(([view::zoom] - 1), (10, 200), (18, 400));
  shield-file: ([param::icon-road_[ref_length]]);
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shield_halo_fill;
  shield-icon-halo-fill: @labels_icon_halo_fill;
  shield-icon-halo-radius: 1;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 8][ref_length <= 6]['mapnik::geometry_type' = 2] when(([network] = 'us-highway' || [network] = 'us-state')) when([class] != 'path')[class = 'motorway']::Highway_shield__US__b1 {
  text-placement: 'billboard';
  text-spacing: @highway_spacing;
  text-name: [ref];
  text-face-name: @font_roboto_bold;
  text-dx: 0;
  text-dy: 0.45;
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-size: @highway_size;
  text-fill: @labels_icon_halo_fill;
  text-halo-fill: @highway_shield_halo_fill;
  text-halo-radius: 0;
  text-placement-priority: 6700000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: @highway_wrap_width;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 8][ref_length <= 6]['mapnik::geometry_type' = 2] when(([network] = 'us-highway' || [network] = 'us-state')) when([class] != 'path') when((!([class] = 'motorway')))::Highway_shield__US__b2 {
  text-placement: 'billboard';
  text-spacing: @highway_spacing;
  text-name: [ref];
  text-face-name: @font_roboto_regular;
  text-dx: 0;
  text-dy: 0.45;
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-size: @highway_size;
  text-fill: @labels_icon_halo_fill;
  text-halo-fill: @highway_shield_halo_fill;
  text-halo-radius: 0;
  text-placement-priority: 6700000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: @highway_wrap_width;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 8][ref_length <= 6]['mapnik::geometry_type' = 2][network = 'us-interstate'] when([class] != 'path')[class = 'motorway']::Highway_shield_interstate_top__US__b1 {
  text-placement: 'billboard';
  text-spacing: @highway_spacing;
  text-name: [ref];
  text-face-name: @font_roboto_bold;
  text-dx: 0;
  text-dy: 0.9;
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-size: @highway_size;
  text-fill: @highway_shield_interstate_top_us_fill;
  text-halo-fill: @highway_shield_halo_fill;
  text-halo-radius: 0;
  text-placement-priority: 6800000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: @highway_wrap_width;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 8][ref_length <= 6]['mapnik::geometry_type' = 2][network = 'us-interstate'] when([class] != 'path') when((!([class] = 'motorway')))::Highway_shield_interstate_top__US__b2 {
  text-placement: 'billboard';
  text-spacing: @highway_spacing;
  text-name: [ref];
  text-face-name: @font_roboto_regular;
  text-dx: 0;
  text-dy: 0.9;
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-size: @highway_size;
  text-fill: @highway_shield_interstate_top_us_fill;
  text-halo-fill: @highway_shield_halo_fill;
  text-halo-radius: 0;
  text-placement-priority: 6800000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: @highway_wrap_width;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 8][ref_length <= 6]['mapnik::geometry_type' = 2][network = 'us-interstate'] when([class] != 'path')[class = 'motorway']::Highway_shield_interstate__US__b1 {
  text-placement: 'billboard';
  text-spacing: @highway_spacing;
  text-name: [ref];
  text-face-name: @font_roboto_bold;
  text-dx: 0;
  text-dy: 0.9;
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-size: @highway_size;
  text-fill: @shield_halo_fill;
  text-halo-fill: @highway_shield_halo_fill;
  text-halo-radius: 0;
  text-placement-priority: 6900000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: @highway_wrap_width;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#transportation_name[zoom >= 8][ref_length <= 6]['mapnik::geometry_type' = 2][network = 'us-interstate'] when([class] != 'path') when((!([class] = 'motorway')))::Highway_shield_interstate__US__b2 {
  text-placement: 'billboard';
  text-spacing: @highway_spacing;
  text-name: [ref];
  text-face-name: @font_roboto_regular;
  text-dx: 0;
  text-dy: 0.9;
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-size: @highway_size;
  text-fill: @shield_halo_fill;
  text-halo-fill: @highway_shield_halo_fill;
  text-halo-radius: 0;
  text-placement-priority: 6900000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: @highway_wrap_width;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#poi[zoom >= 17]['mapnik::geometry_type' = 1] when(([class] = 'atm' || [class] = 'bank' || [class] = 'bbq' || [class] = 'cemetery' || [class] = 'courthouse' || [class] = 'drinking_water' || [class] = 'fire_station' || [class] = 'fountain' || [class] = 'hairdresser' || [class] = 'office' || [class] = 'post' || [class] = 'prison' || [class] = 'recycling' || [class] = 'shower' || [class] = 'telephone' || [class] = 'toilets' || [class] = 'townhall' || [class] = 'town_hall'))::Public {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @public_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (16, (([class] = 'atm' || [class] = 'bank' || [class] = 'cemetery' || [class] = 'courthouse' || [class] = 'townhall' || [class] = 'town_hall') ? 1 : 0)), (17, (([class] = 'atm' || [class] = 'bank' || [class] = 'cemetery' || [class] = 'courthouse' || [class] = 'fire_station' || [class] = 'townhall' || [class] = 'town_hall' || [class] = 'post') ? 1 : 0)), (18, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (16, (([class] = 'atm' || [class] = 'bank' || [class] = 'cemetery' || [class] = 'courthouse' || [class] = 'townhall' || [class] = 'town_hall') ? 1 : 0)), (17, (([class] = 'atm' || [class] = 'bank' || [class] = 'cemetery' || [class] = 'courthouse' || [class] = 'fire_station' || [class] = 'townhall' || [class] = 'town_hall' || [class] = 'post') ? 1 : 0)), (18, 1));
  shield-placement-priority: (7000000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::public-t0-[class]] ?? ((([class] != null)) ? '' : 'icons/dot.png'));
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @public_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (16, (([class] = 'atm' || [class] = 'bank' || [class] = 'cemetery' || [class] = 'courthouse' || [class] = 'townhall' || [class] = 'town_hall') ? 1 : 0)), (17, (([class] = 'atm' || [class] = 'bank' || [class] = 'cemetery' || [class] = 'courthouse' || [class] = 'fire_station' || [class] = 'townhall' || [class] = 'town_hall' || [class] = 'post') ? 1 : 0)), (18, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -5.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 17]['mapnik::geometry_type' = 1] when(([class] = 'american_football' || [class] = 'athletics' || [class] = 'archery' || [class] = 'baseball' || [class] = 'basketball' || [class] = 'climbing' || [class] = 'equestrian' || [class] = 'fitness' || [class] = 'fitness_centre' || [class] = 'golf' || [class] = 'motor' || [class] = 'multi' || [class] = 'playground' || [class] = 'pitch' || [class] = 'running' || [class] = 'sauna' || [class] = 'soccer' || [class] = 'sport' || [class] = 'stadium' || [class] = 'sports_centre' || [class] = 'sports_hall' || [class] = 'swimming' || [class] = 'swimming_area' || [class] = 'swimming_pool' || [class] = 'tennis' || [class] = 'volleyball' || [class] = 'water_park'))[name != null]::Sport {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @sport_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (16, (([class] = 'playground' || [class] = 'pitch' || [class] = 'stadium' || [class] = 'sports_hall' || [class] = 'swimming_pool') ? 1 : 0)), (17, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (16, (([class] = 'playground' || [class] = 'pitch' || [class] = 'stadium' || [class] = 'sports_hall' || [class] = 'swimming_pool') ? 1 : 0)), (17, 1));
  shield-placement-priority: (7100000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::icon-[subclass]] ?? [param::icon-[class]] ?? 'icons/dot.png');
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @sport_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (16, (([class] = 'playground' || [class] = 'pitch' || [class] = 'stadium' || [class] = 'sports_hall' || [class] = 'swimming_pool') ? 1 : 0)), (17, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -1.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 16]['mapnik::geometry_type' = 1] when(([class] = 'college' || [class] = 'childcare' || [class] = 'dancing_school' || [class] = 'driving_school' || [class] = 'kindergarten' || [class] = 'school' || [class] = 'university'))[name != null]::Education {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @education_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (15, (([subclass] = 'university') ? 1 : 0)), (16, (([subclass] = 'school' || [subclass] = 'university') ? 1 : 0)), (17, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (15, (([subclass] = 'university') ? 1 : 0)), (16, (([subclass] = 'school' || [subclass] = 'university') ? 1 : 0)), (17, 1));
  shield-placement-priority: (7200000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::education-t0-[class]] ?? ((([class] != null)) ? '' : 'icons/dot.png'));
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @education_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (15, (([subclass] = 'university') ? 1 : 0)), (16, (([subclass] = 'school' || [subclass] = 'university') ? 1 : 0)), (17, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -5.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 15]['mapnik::geometry_type' = 1] when(([class] = 'apartment' || [class] = 'aquarium' || [class] = 'attraction' || [class] = 'campsite' || [class] = 'camp_site' || [class] = 'caravan_site' || [class] = 'castle' || [class] = 'chalet' || [class] = 'guest_house' || [class] = 'hotel' || [class] = 'hostel' || [class] = 'information' || [class] = 'lodging' || [class] = 'motel' || [class] = 'reservoir' || [class] = 'ruins' || [class] = 'theme_park' || [class] = 'zoo'))[subclass != 'board'][name != null]::Tourism {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @tourism_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'attraction') ? 1 : 0)), (16, (([subclass] = 'attraction' || [subclass] = 'castle' || [subclass] = 'hotel' || [subclass] = 'zoo') ? 1 : 0)), (17, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'attraction') ? 1 : 0)), (16, (([subclass] = 'attraction' || [subclass] = 'castle' || [subclass] = 'hotel' || [subclass] = 'zoo') ? 1 : 0)), (17, 1));
  shield-placement-priority: (7300000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::tourism-t0-[class]] ?? ((([class] != null)) ? '' : 'icons/dot.png'));
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @tourism_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'attraction') ? 1 : 0)), (16, (([subclass] = 'attraction' || [subclass] = 'castle' || [subclass] = 'hotel' || [subclass] = 'zoo') ? 1 : 0)), (17, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -5.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 15]['mapnik::geometry_type' = 1] when(([class] = 'art_gallery' || [class] = 'archeological_site' || [class] = 'cinema' || [class] = 'community_centre' || [class] = 'gallery' || [class] = 'library' || [class] = 'monastery' || [class] = 'monument' || [class] = 'museum' || [class] = 'opera' || [class] = 'place_of_worship' || [class] = 'planetarium' || [class] = 'theatre'))[subclass != 'artwork'][name != null]::Culture {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @culture_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (14, (([class] = 'museum') ? 1 : 0)), (15, (([class] = 'cinema' || [class] = 'art_gallery' || [class] = 'museum' || [class] = 'theatre') ? 1 : 0)), (16, (([class] = 'cinema' || [class] = 'art_gallery' || [class] = 'library' || [class] = 'museum' || [class] = 'place_of_worship' || [class] = 'theatre') ? 1 : 0)), (17, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (14, (([class] = 'museum') ? 1 : 0)), (15, (([class] = 'cinema' || [class] = 'art_gallery' || [class] = 'museum' || [class] = 'theatre') ? 1 : 0)), (16, (([class] = 'cinema' || [class] = 'art_gallery' || [class] = 'library' || [class] = 'museum' || [class] = 'place_of_worship' || [class] = 'theatre') ? 1 : 0)), (17, 1));
  shield-placement-priority: (7400000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::icon-[subclass]] ?? [param::icon-[class]] ?? 'icons/dot.png');
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @culture_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (14, (([class] = 'museum') ? 1 : 0)), (15, (([class] = 'cinema' || [class] = 'art_gallery' || [class] = 'museum' || [class] = 'theatre') ? 1 : 0)), (16, (([class] = 'cinema' || [class] = 'art_gallery' || [class] = 'library' || [class] = 'museum' || [class] = 'place_of_worship' || [class] = 'theatre') ? 1 : 0)), (17, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -1.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 15]['mapnik::geometry_type' = 1] when(([class] = 'alcohol_shop' || [class] = 'bakery' || [class] = 'book' || [class] = 'books' || [class] = 'butcher' || [class] = 'chemist' || [class] = 'clothing_store' || [class] = 'convenience' || [class] = 'gift' || [class] = 'grocery' || [class] = 'laundry' || [class] = 'mall' || [class] = 'music' || [class] = 'shop' || [class] = 'supermarket'))[name != null]::Shopping {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @shopping_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'mall') ? 1 : 0)), (15, (([subclass] = 'mall' || [subclass] = 'supermarket') ? 1 : 0)), (16, (([subclass] = 'bakery' || [subclass] = 'chemist' || [subclass] = 'mall' || [subclass] = 'supermarket') ? 1 : 0)), (17, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'mall') ? 1 : 0)), (15, (([subclass] = 'mall' || [subclass] = 'supermarket') ? 1 : 0)), (16, (([subclass] = 'bakery' || [subclass] = 'chemist' || [subclass] = 'mall' || [subclass] = 'supermarket') ? 1 : 0)), (17, 1));
  shield-placement-priority: (7500000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::icon-[subclass]] ?? [param::icon-[class]] ?? 'icons/dot.png');
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shopping_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'mall') ? 1 : 0)), (15, (([subclass] = 'mall' || [subclass] = 'supermarket') ? 1 : 0)), (16, (([subclass] = 'bakery' || [subclass] = 'chemist' || [subclass] = 'mall' || [subclass] = 'supermarket') ? 1 : 0)), (17, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -1.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 15][zoom < 23]['mapnik::geometry_type' = 1] when(([class] = 'bar' || [class] = 'beer' || [class] = 'biergarten' || [class] = 'cafe' || [class] = 'fast_food' || [class] = 'food_court' || [class] = 'ice_cream' || [class] = 'pub' || [class] = 'restaurant'))[name != null]::Food {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @food_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (14, (([rank] <= 20) ? 1 : 0)), (15, (([rank] <= 99) ? 1 : 0)), (16, (([rank] <= 499) ? 1 : 0)), (17, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (14, (([rank] <= 20) ? 1 : 0)), (15, (([rank] <= 99) ? 1 : 0)), (16, (([rank] <= 499) ? 1 : 0)), (17, 1));
  shield-placement-priority: (7600000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::food-t0-[class]] ?? 'icons/dot.png');
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @food_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (14, (([rank] <= 20) ? 1 : 0)), (15, (([rank] <= 99) ? 1 : 0)), (16, (([rank] <= 499) ? 1 : 0)), (17, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -5.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 15]['mapnik::geometry_type' = 1] when(([class] = 'bicycle' || [class] = 'bicycle_parking' || [class] = 'bicycle_rental' || [class] = 'car' || [class] = 'car_rental' || [class] = 'car_repair' || [class] = 'charging_station' || [class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'harbor' || [class] = 'heliport' || [class] = 'highway_rest_area' || [class] = 'motorcycle_parking' || [class] = 'parking' || [class] = 'parking_garage' || [class] = 'parking_paid' || [class] = 'scooter' || [class] = 'terminal' || [class] = 'toll'))::Transport {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @transport_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (14, (([class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'terminal') ? 1 : 0)), (16, (([class] = 'car' || [class] = 'car_rental' || [class] = 'car_repair' || [class] = 'charging_station' || [class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'harbor' || [class] = 'heliport' || [class] = 'highway_rest_area' || [class] = 'terminal' || [class] = 'toll') ? 1 : 0)), (17, (([class] = 'car' || [class] = 'car_rental' || [class] = 'car_repair' || [class] = 'charging_station' || [class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'harbor' || [class] = 'heliport' || [class] = 'highway_rest_area' || [class] = 'parking' || [class] = 'parking_garage' || [class] = 'parking_paid' || [class] = 'terminal' || [class] = 'toll') ? 1 : 0)), (18, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (14, (([class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'terminal') ? 1 : 0)), (16, (([class] = 'car' || [class] = 'car_rental' || [class] = 'car_repair' || [class] = 'charging_station' || [class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'harbor' || [class] = 'heliport' || [class] = 'highway_rest_area' || [class] = 'terminal' || [class] = 'toll') ? 1 : 0)), (17, (([class] = 'car' || [class] = 'car_rental' || [class] = 'car_repair' || [class] = 'charging_station' || [class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'harbor' || [class] = 'heliport' || [class] = 'highway_rest_area' || [class] = 'parking' || [class] = 'parking_garage' || [class] = 'parking_paid' || [class] = 'terminal' || [class] = 'toll') ? 1 : 0)), (18, 1));
  shield-placement-priority: (7700000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::transport-t0-[class]] ?? ((([class] != null)) ? 'icons/dot.png' : ''));
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @transport_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (14, (([class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'terminal') ? 1 : 0)), (16, (([class] = 'car' || [class] = 'car_rental' || [class] = 'car_repair' || [class] = 'charging_station' || [class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'harbor' || [class] = 'heliport' || [class] = 'highway_rest_area' || [class] = 'terminal' || [class] = 'toll') ? 1 : 0)), (17, (([class] = 'car' || [class] = 'car_rental' || [class] = 'car_repair' || [class] = 'charging_station' || [class] = 'ferry_terminal' || [class] = 'fuel' || [class] = 'harbor' || [class] = 'heliport' || [class] = 'highway_rest_area' || [class] = 'parking' || [class] = 'parking_garage' || [class] = 'parking_paid' || [class] = 'terminal' || [class] = 'toll') ? 1 : 0)), (18, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -5.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 15][class = 'park'][name != null]::Park {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @park_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (14, (([rank] <= 10) ? 1 : 0)), (15, (([rank] <= 99) ? 1 : 0)), (16, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (14, (([rank] <= 10) ? 1 : 0)), (15, (([rank] <= 99) ? 1 : 0)), (16, 1));
  shield-placement-priority: (7800000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: url('icons/park.png');
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @park_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (14, (([rank] <= 10) ? 1 : 0)), (15, (([rank] <= 99) ? 1 : 0)), (16, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -5.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#poi[zoom >= 15]['mapnik::geometry_type' = 1] when(([class] = 'clinic' || [class] = 'dentist' || [class] = 'doctors' || [class] = 'first_aid' || [class] = 'hospital' || [class] = 'pharmacy' || [class] = 'veterinary'))[name != null]::Healthcare {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (12, 10), (16, 12), (22, 14));
  shield-fill: @healthcare_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'hospital') ? 1 : 0)), (16, (([class] = 'clinic' || [class] = 'hospital') ? 1 : 0)), (17, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'hospital') ? 1 : 0)), (16, (([class] = 'clinic' || [class] = 'hospital') ? 1 : 0)), (17, 1));
  shield-placement-priority: (7900000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::healthcare-t0-[class]] ?? ((([class] != null)) ? '' : 'icons/dot.png'));
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @healthcare_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (14, (([subclass] = 'hospital') ? 1 : 0)), (16, (([class] = 'clinic' || [class] = 'hospital') ? 1 : 0)), (17, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -5.03;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#place[zoom >= 5] when(([class] != 'continent' ? ([class] != 'country' ? ([class] != 'state' ? ([class] != 'region' ? ([class] != 'province' ? ([class] != 'city' ? ([class] != 'town' ? [class] != 'place' : false) : false) : false) : false) : false) : false) : false))::Place_labels {
  text-placement: 'billboard';
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'middle';
  text-name: [name];
  text-face-name: @font_roboto_regular;
  text-character-spacing: ((([class] = 'suburb' || [class] = 'neighborhood' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'island') ? 0.2 : 0) * linear(([view::zoom] - 1), (3, 11), (8, 13), (11, (([class] = 'village') ? 12 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 9 : (([class] = 'island') ? 8 : 12)))), (16, (([class] = 'village') ? 18 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 15 : (([class] = 'island') ? 11 : 16))))));
  text-wrap-width: ((([class] = 'island') ? 6 : 8) * linear(([view::zoom] - 1), (3, 11), (8, 13), (11, (([class] = 'village') ? 12 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 9 : (([class] = 'island') ? 8 : 12)))), (16, (([class] = 'village') ? 18 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 15 : (([class] = 'island') ? 11 : 16))))));
  text-dx: (0 * linear(([view::zoom] - 1), (3, 11), (8, 13), (11, (([class] = 'village') ? 12 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 9 : (([class] = 'island') ? 8 : 12)))), (16, (([class] = 'village') ? 18 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 15 : (([class] = 'island') ? 11 : 16))))));
  text-dy: (0 * linear(([view::zoom] - 1), (3, 11), (8, 13), (11, (([class] = 'village') ? 12 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 9 : (([class] = 'island') ? 8 : 12)))), (16, (([class] = 'village') ? 18 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 15 : (([class] = 'island') ? 11 : 16))))));
  text-min-distance: (2 * 2);
  text-size: linear(([view::zoom] - 1), (3, 11), (8, 13), (11, (([class] = 'village') ? 12 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 9 : (([class] = 'island') ? 8 : 12)))), (16, (([class] = 'village') ? 18 : (([class] = 'suburb' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'hamlet' || [class] = 'isolated_dwelling') ? 15 : (([class] = 'island') ? 11 : 16)))));
  text-transform: (([class] = 'suburb' || [class] = 'neighborhood' || [class] = 'neighbourhood' || [class] = 'quarter' || [class] = 'island') ? 'uppercase' : 'none');
  text-fill: @place_labels_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: 1.2;
  text-opacity: step(([view::zoom] - 1), (0, 1), (8, (([class] = 'island') ? 0 : 1)), (9, (([class] = 'island') ? 1 : 1)));
  text-halo-opacity: step(([view::zoom] - 1), (0, 1), (8, (([class] = 'island') ? 0 : 1)), (9, (([class] = 'island') ? 1 : 1)));
  text-placement-priority: (8000000 - (0 + [rank]));
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#poi[zoom >= 13] when(([class] = 'bus' || [class] = 'railway'))[name != null]::Station {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name];
  shield-face-name: @font_roboto_medium;
  shield-line-spacing: (-0.3 * linear(([view::zoom] - 1), (13, 11), (16, 12), (22, 16)));
  shield-wrap-width: (9 * linear(([view::zoom] - 1), (13, 11), (16, 12), (22, 16)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (13, 11), (16, 12), (22, 16)));
  shield-text-dy: (0.9 * linear(([view::zoom] - 1), (13, 11), (16, 12), (22, 16)));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (13, 11), (16, 12), (22, 16));
  shield-fill: @shield_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @shield_halo_radius;
  shield-text-opacity: step(([view::zoom] - 1), (0, 0), (12, (([subclass] = 'station') ? 1 : 0)), (14, (([subclass] = 'station' || [subclass] = 'subway' || [subclass] = 'tram_stop') ? 1 : 0)), (16, (([subclass] = 'bus_stop' || [subclass] = 'station' || [subclass] = 'subway' || [subclass] = 'tram_stop') ? 1 : 0)), (17, 1));
  shield-halo-opacity: step(([view::zoom] - 1), (0, 0), (12, (([subclass] = 'station') ? 1 : 0)), (14, (([subclass] = 'station' || [subclass] = 'subway' || [subclass] = 'tram_stop') ? 1 : 0)), (16, (([subclass] = 'bus_stop' || [subclass] = 'station' || [subclass] = 'subway' || [subclass] = 'tram_stop') ? 1 : 0)), (17, 1));
  shield-placement-priority: (8100000 - (0 + [rank]));
  shield-wrap-before: true;
  shield-file: ([param::station-t0-[subclass]] ?? ((([subclass] != null)) ? 'icons/dot.png' : ''));
  shield-unlock-image: true;
  shield-image-scale: ((1) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shield_fill;
  shield-icon-opacity: step(([view::zoom] - 1), (0, 0), (12, (([subclass] = 'station') ? 1 : 0)), (14, (([subclass] = 'station' || [subclass] = 'subway' || [subclass] = 'tram_stop') ? 1 : 0)), (16, (([subclass] = 'bus_stop' || [subclass] = 'station' || [subclass] = 'subway' || [subclass] = 'tram_stop') ? 1 : 0)), (17, 1));
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: 2;
  shield-text-optional: true;
  shield-dy: -3;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#aeroway[zoom >= 16][class = 'gate']::Airport_gate {
  text-placement: 'billboard';
  text-name: [ref];
  text-face-name: @font_roboto_medium;
  text-size: linear(([view::zoom] - 1), (15, 10), (22, 18));
  text-fill: @text_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-placement-priority: 8200000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: (10 * linear(([view::zoom] - 1), (15, 10), (22, 18)));
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#aerodrome_label[zoom >= 9][zoom < 10][iata != null] when([class] != 'public')::Airport_b1 {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: ' ';
  shield-face-name: @font_roboto_medium;
  shield-line-spacing: (0 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-wrap-width: (9 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11)));
  shield-fill: @shield_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: linear(([view::zoom] - 1), (8, 1), (12, 2));
  shield-placement-priority: 8300000;
  shield-wrap-before: true;
  shield-file: ([param::airport-t0-[class]] ?? 'icons/airfield.png');
  shield-unlock-image: true;
  shield-image-scale: ((linear(([view::zoom] - 1), (8, 0.6), (10, (([class] = 'international') ? 0.8 : 0.6)), (16, (([class] = 'international') ? 1 : 0.8)))) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shield_fill;
  shield-icon-opacity: 1;
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: linear(([view::zoom] - 1), (8, 1), (12, 2));
  shield-text-optional: true;
  shield-dy: -4.54;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#aerodrome_label[zoom >= 10][zoom < 13][iata != null] when([class] != 'public')::Airport_b2 {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [iata];
  shield-face-name: @font_roboto_medium;
  shield-line-spacing: (0 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-wrap-width: (9 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11)));
  shield-fill: @shield_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: linear(([view::zoom] - 1), (8, 1), (12, 2));
  shield-placement-priority: 8300000;
  shield-wrap-before: true;
  shield-file: ([param::airport-t0-[class]] ?? 'icons/airfield.png');
  shield-unlock-image: true;
  shield-image-scale: ((linear(([view::zoom] - 1), (8, 0.6), (10, (([class] = 'international') ? 0.8 : 0.6)), (16, (([class] = 'international') ? 1 : 0.8)))) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shield_fill;
  shield-icon-opacity: 1;
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: linear(([view::zoom] - 1), (8, 1), (12, 2));
  shield-text-optional: true;
  shield-dy: -4.54;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#aerodrome_label[zoom >= 13][zoom < 25][iata != null] when([class] != 'public')::Airport_b3 {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'top';
  shield-name: [name:en];
  shield-face-name: @font_roboto_medium;
  shield-line-spacing: (0 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-wrap-width: (9 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-text-dy: (0.8 * linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11))));
  shield-min-distance: (2 * 2);
  shield-size: linear(([view::zoom] - 1), (9, 9), (10, (([class] = 'international') ? 10 : 7)), (14, (([class] = 'international') ? 13 : 11)));
  shield-fill: @shield_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: linear(([view::zoom] - 1), (8, 1), (12, 2));
  shield-placement-priority: 8300000;
  shield-wrap-before: true;
  shield-file: ([param::airport-t0-[class]] ?? 'icons/airfield.png');
  shield-unlock-image: true;
  shield-image-scale: ((linear(([view::zoom] - 1), (8, 0.6), (10, (([class] = 'international') ? 0.8 : 0.6)), (16, (([class] = 'international') ? 1 : 0.8)))) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shield_fill;
  shield-icon-opacity: 1;
  shield-icon-halo-fill: @shield_halo_fill;
  shield-icon-halo-radius: linear(([view::zoom] - 1), (8, 1), (12, 2));
  shield-text-optional: true;
  shield-dy: -4.54;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#place[zoom >= 4][zoom < 10] when(([class] = 'state' || [class] = 'province'))[rank <= 6]::State_labels {
  text-placement: 'billboard';
  text-name: ([name:en]) ?? ([name]);
  text-face-name: @font_roboto_medium;
  text-character-spacing: (0.1 * linear(([view::zoom] - 1), (3, 9), (5, 10), (6, 11)));
  text-wrap-width: (8 * linear(([view::zoom] - 1), (3, 9), (5, 10), (6, 11)));
  text-min-distance: (2 * 2);
  text-size: linear(([view::zoom] - 1), (3, 9), (5, 10), (6, 11));
  text-transform: 'uppercase';
  text-fill: @state_labels_fill;
  text-halo-fill: @state_labels_halo_fill;
  text-halo-radius: @labels_halo_radius;
  text-opacity: step(([view::zoom] - 1), (0, 0), (3, (([rank] <= 3) ? 1 : 0)), (8, (([rank] = 0) ? 0 : 1)));
  text-halo-opacity: step(([view::zoom] - 1), (0, 0), (3, (([rank] <= 3) ? 1 : 0)), (8, (([rank] = 0) ? 0 : 1)));
  text-placement-priority: (8400000 - (0 + [rank]));
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#place[zoom >= 7][zoom < 13][class = 'town']::Town_labels_b1 {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'bottom';
  shield-name: ([name:en]) ?? ([name]);
  shield-face-name: @font_roboto_regular;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (6, (([rank] <= 12) ? 11 : 10)), (9, (([rank] <= 15) ? 13 : 12)), (16, (([rank] <= 15) ? 22 : 20))));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (6, (([rank] <= 12) ? 11 : 10)), (9, (([rank] <= 15) ? 13 : 12)), (16, (([rank] <= 15) ? 22 : 20))));
  shield-text-dy: (-0.15 * linear(([view::zoom] - 1), (6, (([rank] <= 12) ? 11 : 10)), (9, (([rank] <= 15) ? 13 : 12)), (16, (([rank] <= 15) ? 22 : 20))));
  shield-size: linear(([view::zoom] - 1), (6, (([rank] <= 12) ? 11 : 10)), (9, (([rank] <= 15) ? 13 : 12)), (16, (([rank] <= 15) ? 22 : 20)));
  shield-fill: linear(([view::zoom] - 1), (6, @labels_fill), (12, @town_labels_fill));
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @text_halo_radius;
  shield-placement-priority: (8500000 - (0 + [rank]));
  shield-min-distance: @text_minimum_distance;
  shield-wrap-before: true;
  shield-file: url('icons/circle.png');
  shield-unlock-image: true;
  shield-image-scale: ((linear(([view::zoom] - 1), (6, 0.3), (14, 0.4))) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @town_labels_icon_fill;
  shield-icon-halo-fill: @labels_icon_halo_fill;
  shield-icon-halo-radius: 1;
  shield-dy: 3.61;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#place[zoom >= 13][zoom < 17][class = 'town']::Town_labels_b2 {
  text-placement: 'billboard';
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'bottom';
  text-name: ([name:en]) ?? ([name]);
  text-face-name: @font_roboto_regular;
  text-wrap-width: (8 * linear(([view::zoom] - 1), (6, (([rank] <= 12) ? 11 : 10)), (9, (([rank] <= 15) ? 13 : 12)), (16, (([rank] <= 15) ? 22 : 20))));
  text-dx: (0 * linear(([view::zoom] - 1), (6, (([rank] <= 12) ? 11 : 10)), (9, (([rank] <= 15) ? 13 : 12)), (16, (([rank] <= 15) ? 22 : 20))));
  text-dy: (-0.15 * linear(([view::zoom] - 1), (6, (([rank] <= 12) ? 11 : 10)), (9, (([rank] <= 15) ? 13 : 12)), (16, (([rank] <= 15) ? 22 : 20))));
  text-size: linear(([view::zoom] - 1), (6, (([rank] <= 12) ? 11 : 10)), (9, (([rank] <= 15) ? 13 : 12)), (16, (([rank] <= 15) ? 22 : 20)));
  text-fill: linear(([view::zoom] - 1), (6, @labels_fill), (12, @town_labels_fill));
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-placement-priority: (8500000 - (0 + [rank]));
  text-min-distance: @text_minimum_distance;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#place[zoom >= 5][zoom < 14][class = 'city'][capital != 2]::City_labels_b1 {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'bottom';
  shield-name: [name:en];
  shield-face-name: @font_roboto_medium;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (4, (([rank] <= 2) ? 14 : 12)), (8, (([rank] <= 4) ? 18 : 14)), (12, (([rank] <= 4) ? 24 : 18)), (16, (([rank] <= 4) ? 32 : 26))));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (4, (([rank] <= 2) ? 14 : 12)), (8, (([rank] <= 4) ? 18 : 14)), (12, (([rank] <= 4) ? 24 : 18)), (16, (([rank] <= 4) ? 32 : 26))));
  shield-text-dy: (-0.15 * linear(([view::zoom] - 1), (4, (([rank] <= 2) ? 14 : 12)), (8, (([rank] <= 4) ? 18 : 14)), (12, (([rank] <= 4) ? 24 : 18)), (16, (([rank] <= 4) ? 32 : 26))));
  shield-size: linear(([view::zoom] - 1), (4, (([rank] <= 2) ? 14 : 12)), (8, (([rank] <= 4) ? 18 : 14)), (12, (([rank] <= 4) ? 24 : 18)), (16, (([rank] <= 4) ? 32 : 26)));
  shield-fill: @labels_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @labels_halo_radius;
  shield-placement-priority: (8600000 - (0 + [rank]));
  shield-min-distance: @text_minimum_distance;
  shield-wrap-before: true;
  shield-file: url('icons/circle.png');
  shield-unlock-image: true;
  shield-image-scale: ((0.4) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shield_halo_fill;
  shield-icon-opacity: 1;
  shield-icon-halo-fill: @labels_icon_halo_fill;
  shield-icon-halo-radius: 1;
  shield-dy: 4.45;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#place[zoom >= 14][zoom < 17][class = 'city'][capital != 2]::City_labels_b2 {
  text-placement: 'billboard';
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'bottom';
  text-name: [name:en];
  text-face-name: @font_roboto_medium;
  text-wrap-width: (8 * linear(([view::zoom] - 1), (4, (([rank] <= 2) ? 14 : 12)), (8, (([rank] <= 4) ? 18 : 14)), (12, (([rank] <= 4) ? 24 : 18)), (16, (([rank] <= 4) ? 32 : 26))));
  text-dx: (0 * linear(([view::zoom] - 1), (4, (([rank] <= 2) ? 14 : 12)), (8, (([rank] <= 4) ? 18 : 14)), (12, (([rank] <= 4) ? 24 : 18)), (16, (([rank] <= 4) ? 32 : 26))));
  text-dy: (-0.15 * linear(([view::zoom] - 1), (4, (([rank] <= 2) ? 14 : 12)), (8, (([rank] <= 4) ? 18 : 14)), (12, (([rank] <= 4) ? 24 : 18)), (16, (([rank] <= 4) ? 32 : 26))));
  text-size: linear(([view::zoom] - 1), (4, (([rank] <= 2) ? 14 : 12)), (8, (([rank] <= 4) ? 18 : 14)), (12, (([rank] <= 4) ? 24 : 18)), (16, (([rank] <= 4) ? 32 : 26)));
  text-fill: @labels_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @labels_halo_radius;
  text-placement-priority: (8600000 - (0 + [rank]));
  text-min-distance: @text_minimum_distance;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#place[zoom >= 5][zoom < 14][class = 'city'][capital = 2]::Capital_city_labels_b1 {
  shield-placement: 'billboard';
  shield-horizontal-alignment: 'middle';
  shield-vertical-alignment: 'bottom';
  shield-name: [name:en];
  shield-face-name: @font_roboto_medium;
  shield-wrap-width: (8 * linear(([view::zoom] - 1), (4, 14), (8, 18), (12, 24), (16, 32)));
  shield-text-dx: (0 * linear(([view::zoom] - 1), (4, 14), (8, 18), (12, 24), (16, 32)));
  shield-text-dy: (-0.15 * linear(([view::zoom] - 1), (4, 14), (8, 18), (12, 24), (16, 32)));
  shield-size: linear(([view::zoom] - 1), (4, 14), (8, 18), (12, 24), (16, 32));
  shield-fill: @labels_fill;
  shield-halo-fill: @shield_halo_fill;
  shield-halo-radius: @labels_halo_radius;
  shield-placement-priority: (8700000 - (0 + [rank]));
  shield-min-distance: @text_minimum_distance;
  shield-wrap-before: true;
  shield-file: url('icons/circle.png');
  shield-unlock-image: true;
  shield-image-scale: ((linear(([view::zoom] - 1), (4, 0.45), (10, 0.5), (11, 0.6))) / 1.0);
  shield-sdf: true;
  shield-icon-fill: @shield_halo_fill;
  shield-icon-opacity: 1;
  shield-icon-halo-fill: @labels_icon_halo_fill;
  shield-icon-halo-radius: 1;
  shield-dy: 5.22;
  shield-emissive-strength: 0.45;
  shield-halo-emissive-strength: 0;
}
#place[zoom >= 14][zoom < 17][class = 'city'][capital = 2]::Capital_city_labels_b2 {
  text-placement: 'billboard';
  text-horizontal-alignment: 'middle';
  text-vertical-alignment: 'bottom';
  text-name: [name:en];
  text-face-name: @font_roboto_medium;
  text-wrap-width: (8 * linear(([view::zoom] - 1), (4, 14), (8, 18), (12, 24), (16, 32)));
  text-dx: (0 * linear(([view::zoom] - 1), (4, 14), (8, 18), (12, 24), (16, 32)));
  text-dy: (-0.15 * linear(([view::zoom] - 1), (4, 14), (8, 18), (12, 24), (16, 32)));
  text-size: linear(([view::zoom] - 1), (4, 14), (8, 18), (12, 24), (16, 32));
  text-fill: @labels_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @labels_halo_radius;
  text-placement-priority: (8700000 - (0 + [rank]));
  text-min-distance: @text_minimum_distance;
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#place[zoom >= 2][zoom < 13][class = 'country'][iso_a2 != null][iso_a2 != 'VA']::Country_labels {
  text-placement: 'billboard';
  text-allow-overlap: false;
  text-name: [name:en];
  text-face-name: @font_roboto_medium;
  text-character-spacing: (0.07 * linear(([view::zoom] - 1), (0, 8), (1, 10), (4, (([rank] > 2) ? 15 : 17)), (8, (([rank] > 2) ? 19 : 23))));
  text-wrap-width: (linear(([view::zoom] - 1), (1, 5), (5, 8)) * linear(([view::zoom] - 1), (0, 8), (1, 10), (4, (([rank] > 2) ? 15 : 17)), (8, (([rank] > 2) ? 19 : 23))));
  text-min-distance: (2 * 1);
  text-size: linear(([view::zoom] - 1), (0, 8), (1, 10), (4, (([rank] > 2) ? 15 : 17)), (8, (([rank] > 2) ? 19 : 23)));
  text-transform: 'none';
  text-fill: @labels_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-opacity: linear(([view::zoom] - 1), (4, (([rank] > 4) ? 0 : 1)), (5.9, (([rank] > 4) ? 0 : 1)), (6, (([rank] > 4) ? 1 : 1)));
  text-halo-opacity: linear(([view::zoom] - 1), (4, (([rank] > 4) ? 0 : 1)), (5.9, (([rank] > 4) ? 0 : 1)), (6, (([rank] > 4) ? 1 : 1)));
  text-placement-priority: (8800000 - (0 + [rank]));
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
#place[zoom < 2][class = 'continent']::Continent_labels {
  text-placement: 'billboard';
  text-name: [name:en];
  text-face-name: @font_roboto_medium;
  text-size: linear(([view::zoom] - 1), (0, 12), (2, 13));
  text-transform: 'uppercase';
  text-fill: @continent_labels_fill;
  text-halo-fill: @shield_halo_fill;
  text-halo-radius: @text_halo_radius;
  text-placement-priority: 8900000;
  text-min-distance: @text_minimum_distance;
  text-wrap-width: (10 * linear(([view::zoom] - 1), (0, 12), (2, 13)));
  text-wrap-before: true;
  text-emissive-strength: 0.45;
  text-halo-emissive-strength: 0;
}
