// Generated by scripts/gen-api-constants.py. Do not edit.
package com.massifmaps.api;

/**
 * The facade's names, as constants an editor can complete.
 *
 * A {@link MassifObject.Key} carries the value type with it, so the compiler rejects a
 * colour written to a float. A path is these joined by dots - "fogOptions." + RANGE_START -
 * and the plain string still works for anything this file predates.
 */
public final class ApiNames {

    /** Encodes this map color into 32-bit integer value (ARGB format). */
    public static final MassifObject.Key<Long> ARGB = MassifObject.key("ARGB");
    /** Returns the dots per inch value. */
    public static final MassifObject.Key<Double> DPI = MassifObject.key("DPI");
    /** Returns the value used for converting display independent pixels (dp) to pixels (px). */
    public static final MassifObject.Key<Double> DPTO_PX = MassifObject.key("DPToPX");
    /** Returns the vertical field of view angle. */
    public static final MassifObject.Key<Long> FOVY = MassifObject.key("FOVY");
    /** Returns the current set of HTTP headers used. Initially this set is empty and can be changed with setHTTPHeaders. */
    public static final MassifObject.Key<String> HTTPHEADERS = MassifObject.key("HTTPHeaders");
    /** Returns true/false based whether the TMS tiling scheme is used. */
    public static final MassifObject.Key<Boolean> TMSSCHEME = MassifObject.key("TMSScheme");
    /** Returns the tile data source of the associated UTF grid. By default this is null. */
    public static final MassifObject.Key<MassifObject> UTFGRID_DATA_SOURCE = MassifObject.key("UTFGridDataSource");
    /** Returns the UTF grid event listener. */
    public static final MassifObject.Key<MassifObject> UTFGRID_EVENT_LISTENER = MassifObject.key("UTFGridEventListener");
    /** Returns true if Z-buffering is enabled for 2D geometry. By default it is disabled and used only for billboards. */
    public static final MassifObject.Key<Boolean> ZBUFFERING = MassifObject.key("ZBuffering");
    /** Returns the alpha component of this map color. */
    public static final MassifObject.Key<Long> A = MassifObject.key("a");
    /** Returns the shading color used to accentuate rugged terrain like sharp cliffs and gorges. */
    public static final MassifObject.Key<Integer> ACCENT_COLOR = MassifObject.key("accentColor");
    /** Returns the accuracy of the points in the request. */
    public static final MassifObject.Key<Double> ACCURACY = MassifObject.key("accuracy");
    /** Returns the action of the instruction. */
    public static final MassifObject.Key<String> ACTION = MassifObject.key("action");
    /** Returns the address of the result. */
    public static final MassifObject.Key<String> ADDRESS = MassifObject.key("address");
    /** Returns the altitude of a direction-anchored object. */
    public static final MassifObject.Key<Double> ALTITUDE = MassifObject.key("altitude");
    /** Returns the ambient light color. */
    public static final MassifObject.Key<Integer> AMBIENT_COLOR = MassifObject.key("ambientColor");
    /** Returns the ambient light intensity. */
    public static final MassifObject.Key<Double> AMBIENT_INTENSITY = MassifObject.key("ambientIntensity");
    /** Returns the color of the ambient light. */
    public static final MassifObject.Key<Integer> AMBIENT_LIGHT_COLOR = MassifObject.key("ambientLightColor");
    /** Returns the horizontal anchor point of the label. */
    public static final MassifObject.Key<Double> ANCHOR_POINT_X = MassifObject.key("anchorPointX");
    /** Returns the vertical anchor point of the label. */
    public static final MassifObject.Key<Double> ANCHOR_POINT_Y = MassifObject.key("anchorPointY");
    /** Returns the screen position of the anchor point of this popup in pixels. */
    public static final MassifObject.Key<String> ANCHOR_SCREEN_POS = MassifObject.key("anchorScreenPos");
    /** Returns the angular size of the sprite. */
    public static final MassifObject.Key<Double> ANGULAR_SIZE = MassifObject.key("angularSize");
    /** Returns the cluster animation flag value. */
    public static final MassifObject.Key<Boolean> ANIMATED_CLUSTERS = MassifObject.key("animatedClusters");
    /** Returns the animation duration, in seconds. */
    public static final MassifObject.Key<Double> ANIMATION_DURATION = MassifObject.key("animationDuration");
    /** Returns true if the interaction has started an animation. */
    public static final MassifObject.Key<Boolean> ANIMATION_STARTED = MassifObject.key("animationStarted");
    /** Returns the animation style of the billboard. */
    public static final MassifObject.Key<MassifObject> ANIMATION_STYLE = MassifObject.key("animationStyle");
    /** Returns the number of elements in the array. */
    public static final MassifObject.Key<Long> ARRAY_SIZE = MassifObject.key("arraySize");
    /** Returns the aspect ratio of the map screen. Equal to width / height. */
    public static final MassifObject.Key<Double> ASPECT_RATIO = MassifObject.key("aspectRatio");
    public static final MassifObject.Key<String> ASSET_NAMES = MassifObject.key("assetNames");
    /** Returns the style asset package. */
    public static final MassifObject.Key<MassifObject> ASSET_PACKAGE = MassifObject.key("assetPackage");
    /** Returns the tint applied to Rayleigh scattering. */
    public static final MassifObject.Key<Integer> ATMOSPHERE_COLOR = MassifObject.key("atmosphereColor");
    /** Returns the exposure applied to the scattered light. */
    public static final MassifObject.Key<Double> ATMOSPHERE_LUMINANCE = MassifObject.key("atmosphereLuminance");
    /** Returns the brightness of the sun driving the atmosphere. */
    public static final MassifObject.Key<Double> ATMOSPHERE_SUN_INTENSITY = MassifObject.key("atmosphereSunIntensity");
    /** Returns the horizontal attaching anchor point of the billoard. */
    public static final MassifObject.Key<Double> ATTACH_ANCHOR_POINT_X = MassifObject.key("attachAnchorPointX");
    /** Returns the vertical attaching anchor point of the billoard. */
    public static final MassifObject.Key<Double> ATTACH_ANCHOR_POINT_Y = MassifObject.key("attachAnchorPointY");
    /** Returns how long the terrain takes to sink flat. */
    public static final MassifObject.Key<Double> AUTO_FLATTEN_DURATION = MassifObject.key("autoFlattenDuration");
    /** Returns the screen parallax below which the terrain renders flat. */
    public static final MassifObject.Key<Double> AUTO_FLATTEN_PARALLAX = MassifObject.key("autoFlattenParallax");
    /** Returns how long the terrain takes to rise back into 3D. */
    public static final MassifObject.Key<Double> AUTO_FLATTEN_RISE_DURATION = MassifObject.key("autoFlattenRiseDuration");
    /** Returns the tilt at or above which the terrain renders flat. */
    public static final MassifObject.Key<Double> AUTO_FLATTEN_TILT = MassifObject.key("autoFlattenTilt");
    public static final MassifObject.Key<Boolean> AUTOCOMPLETE = MassifObject.key("autocomplete");
    /** Returns the azimuth of a direction-anchored object. */
    public static final MassifObject.Key<Double> AZIMUTH = MassifObject.key("azimuth");
    /** Returns the blue component of this map color. */
    public static final MassifObject.Key<Long> B = MassifObject.key("b");
    /** Returns the background bitmap. May be null. */
    public static final MassifObject.Key<MassifObject> BACKGROUND_BITMAP = MassifObject.key("backgroundBitmap");
    /** Returns the background color of the button. */
    public static final MassifObject.Key<Integer> BACKGROUND_COLOR = MassifObject.key("backgroundColor");
    /** Returns the balloon popup event listener. */
    public static final MassifObject.Key<MassifObject> BALLOON_POPUP_EVENT_LISTENER = MassifObject.key("balloonPopupEventListener");
    /** Returns the base billboard this billboard is attached to. */
    public static final MassifObject.Key<MassifObject> BASE_BILLBOARD = MassifObject.key("baseBillboard");
    /** Returns the base contour interval in meters. */
    public static final MassifObject.Key<Double> BASE_INTERVAL = MassifObject.key("baseInterval");
    /** Returns the path of the bundled directory the assets are read from. */
    public static final MassifObject.Key<String> BASE_PATH = MassifObject.key("basePath");
    /** Returns the base projection. */
    public static final MassifObject.Key<MassifObject> BASE_PROJECTION = MassifObject.key("baseProjection");
    /** Returns the base URL template containing tags. */
    public static final MassifObject.Key<String> BASE_URL = MassifObject.key("baseURL");
    /** Returns whether the part of the curve below the horizon is drawn. */
    public static final MassifObject.Key<Boolean> BELOW_HORIZON_VISIBLE = MassifObject.key("belowHorizonVisible");
    /** Returns the endianness of output format. */
    public static final MassifObject.Key<Boolean> BIG_ENDIAN = MassifObject.key("bigEndian");
    /** Returns the billboard/label terrain occlusion state. */
    public static final MassifObject.Key<Boolean> BILLBOARD_OCCLUSION_ENABLED = MassifObject.key("billboardOcclusionEnabled");
    /** Returns the billboard/label terrain occlusion tolerance. */
    public static final MassifObject.Key<Double> BILLBOARD_OCCLUSION_TOLERANCE = MassifObject.key("billboardOcclusionTolerance");
    /** Returns the bitmap of the sprite. */
    public static final MassifObject.Key<MassifObject> BITMAP = MassifObject.key("bitmap");
    /** Returns the bitmap scaling factor. */
    public static final MassifObject.Key<Double> BITMAP_SCALE = MassifObject.key("bitmapScale");
    /** Returns the boolean value of this variant. */
    public static final MassifObject.Key<Boolean> BOOL = MassifObject.key("bool");
    /** Returns the color of the border. */
    public static final MassifObject.Key<Integer> BORDER_COLOR = MassifObject.key("borderColor");
    /** Returns the width of the border. */
    public static final MassifObject.Key<Double> BORDER_WIDTH = MassifObject.key("borderWidth");
    public static final MassifObject.Key<Long> BOTTOM = MassifObject.key("bottom");
    /** Returns the bounds of this billboard or the base billboard, if there is one. */
    public static final MassifObject.Key<String> BOUNDS = MassifObject.key("bounds");
    /** Returns the state of the 'break lines' flag. */
    public static final MassifObject.Key<Boolean> BREAK_LINES = MassifObject.key("breakLines");
    /** Returns the current display order of the buildings. */
    public static final MassifObject.Key<String> BUILDING_RENDER_ORDER = MassifObject.key("buildingRenderOrder");
    /** Returns the clicked button. */
    public static final MassifObject.Key<MassifObject> BUTTON = MassifObject.key("button");
    /** Returns the margins for the buttons of the popup. */
    public static final MassifObject.Key<String> BUTTON_MARGINS = MassifObject.key("buttonMargins");
    /** Returns the width of the button. If this value is -1, then button width is calculated automatically based on button text. */
    public static final MassifObject.Key<Long> BUTTON_WIDTH = MassifObject.key("buttonWidth");
    /** Returns the bytes per pixel parameter of this bitmap. Valid values are 1, 2, 3 and 4. */
    public static final MassifObject.Key<Long> BYTES_PER_PIXEL = MassifObject.key("bytesPerPixel");
    /** Returns the state of cache only mode. */
    public static final MassifObject.Key<Boolean> CACHE_ONLY_MODE = MassifObject.key("cacheOnlyMode");
    /** Returns the state of the camera changed flag. */
    public static final MassifObject.Key<Boolean> CAMERA_CHANGED = MassifObject.key("cameraChanged");
    /** Returns the duration of the camera terrain-following correction animation. */
    public static final MassifObject.Key<Double> CAMERA_CLAMP_DURATION = MassifObject.key("cameraClampDuration");
    /** Returns the camera terrain clearance: the minimum height the camera is kept above the terrain surface, in meters. */
    public static final MassifObject.Key<Double> CAMERA_CLEARANCE = MassifObject.key("cameraClearance");
    /** Returns the position the camera itself is above, which at a low tilt is nowhere near the focus - the focus is what the camera looks AT, kilometres out in front of it. This is the viewpoint: where a first-person camera stands, and where a top-down view has to be centred to come back to the same place. */
    public static final MassifObject.Key<String> CAMERA_POS = MassifObject.key("cameraPos");
    public static final MassifObject.Key<Long> CAPACITY = MassifObject.key("capacity");
    /** Returns the CartoCSS string used for the style. */
    public static final MassifObject.Key<String> CARTO_CSS = MassifObject.key("cartoCSS");
    /** Returns the current CartoCSS style set used by the decoder. If decoder uses non-CartoCSS style set, null is returned. */
    public static final MassifObject.Key<MassifObject> CARTO_CSSSTYLE = MassifObject.key("cartoCSSStyle");
    /** Returns the list of category tags describing the address. */
    public static final MassifObject.Key<String> CATEGORIES = MassifObject.key("categories");
    /** Returns the state of the causes overlap flag. */
    public static final MassifObject.Key<Boolean> CAUSES_OVERLAP = MassifObject.key("causesOverlap");
    /** Returns the object event listener. */
    public static final MassifObject.Key<MassifObject> CELESTIAL_EVENT_LISTENER = MassifObject.key("celestialEventListener");
    /** Calculates the center map position of this map envelope object. */
    public static final MassifObject.Key<String> CENTER = MassifObject.key("center");
    public static final MassifObject.Key<String> CENTER_POS = MassifObject.key("centerPos");
    /** Returns the clear color used by the renderer before drawing anything else. By default, this is white. It should be set to (0, 0, 0, 0) if transparent MapView is needed. */
    public static final MassifObject.Key<Integer> CLEAR_COLOR = MassifObject.key("clearColor");
    /** Returns the click handler layer filter. The filter is given as ECMA regular expression that is applied to qualified layer names. */
    public static final MassifObject.Key<String> CLICK_HANDLER_LAYER_FILTER = MassifObject.key("clickHandlerLayerFilter");
    /** Returns the click info. */
    public static final MassifObject.Key<String> CLICK_INFO = MassifObject.key("clickInfo");
    /** Returns the click position. */
    public static final MassifObject.Key<String> CLICK_POS = MassifObject.key("clickPos");
    /** Returns the click radius of the curve. */
    public static final MassifObject.Key<Double> CLICK_RADIUS = MassifObject.key("clickRadius");
    /** Returns the click size of the marker. */
    public static final MassifObject.Key<Double> CLICK_SIZE = MassifObject.key("clickSize");
    /** Returns the click type. */
    public static final MassifObject.Key<String> CLICK_TYPE = MassifObject.key("clickType");
    /** Returns the click type detection state. */
    public static final MassifObject.Key<Boolean> CLICK_TYPE_DETECTION = MassifObject.key("clickTypeDetection");
    /** Returns the width of the line used for click detection. */
    public static final MassifObject.Key<Double> CLICK_WIDTH = MassifObject.key("clickWidth");
    /** Returns the current callback used for creating cluster elements. */
    public static final MassifObject.Key<MassifObject> CLUSTER_ELEMENT_BUILDER = MassifObject.key("clusterElementBuilder");
    /** Returns the color of the object. */
    public static final MassifObject.Key<Integer> COLOR = MassifObject.key("color");
    /** Returns the color format of this bitmap. */
    public static final MassifObject.Key<String> COLOR_FORMAT = MassifObject.key("colorFormat");
    /** Returns the current compiled style set used by the decoder. If decoder uses non-compiled style set, null is returned. */
    public static final MassifObject.Key<MassifObject> COMPILED_STYLE = MassifObject.key("compiledStyle");
    /** Returns the contour line color. */
    public static final MassifObject.Key<Integer> CONTOUR_COLOR = MassifObject.key("contourColor");
    /** Returns whether GPU contour lines are drawn over the hillshade. */
    public static final MassifObject.Key<Boolean> CONTOUR_ENABLED = MassifObject.key("contourEnabled");
    /** Returns the spacing between contour lines in meters. */
    public static final MassifObject.Key<Double> CONTOUR_INTERVAL = MassifObject.key("contourInterval");
    /** Returns the contour line half-width in screen pixels. */
    public static final MassifObject.Key<Double> CONTOUR_WIDTH = MassifObject.key("contourWidth");
    /** Returns the contrast of the hillshade overlay. This is the equivalent of MapLibre's 'hillshade-exaggeration' paint property: it controls the slope response curve and the overall strength of the shading, not the relief itself. */
    public static final MassifObject.Key<Double> CONTRAST = MassifObject.key("contrast");
    /** Returns the convex hull of this map envelope. */
    public static final MassifObject.Key<String> CONVEX_HULL = MassifObject.key("convexHull");
    /** Returns the corner radius of the button. */
    public static final MassifObject.Key<Long> CORNER_RADIUS = MassifObject.key("cornerRadius");
    /** Returns the current layer count. */
    public static final MassifObject.Key<Long> COUNT = MassifObject.key("count");
    /** Returns the country name included in the address. */
    public static final MassifObject.Key<String> COUNTRY = MassifObject.key("country");
    /** Returns the county name included in the address. */
    public static final MassifObject.Key<String> COUNTY = MassifObject.key("county");
    /** Returns the culling delay of the layer in milliseconds. */
    public static final MassifObject.Key<Long> CULL_DELAY = MassifObject.key("cullDelay");
    /** Returns the current action being performed. */
    public static final MassifObject.Key<String> CURRENT_ACTION = MassifObject.key("currentAction");
    /** Returns the custom backend service URL. */
    public static final MassifObject.Key<String> CUSTOM_SERVICE_URL = MassifObject.key("customServiceURL");
    /** Returns tile data as binary data. */
    public static final MassifObject.Key<MassifObject> DATA = MassifObject.key("data");
    /** Returns the extent of the tiles in this data source. The bounds are in coordinate system of the projection of the data source. */
    public static final MassifObject.Key<String> DATA_EXTENT = MassifObject.key("dataExtent");
    /** Returns the original data source that the cache uses. */
    public static final MassifObject.Key<MassifObject> DATA_SOURCE = MassifObject.key("dataSource");
    /** Returns the state of the tile border debug overlay. */
    public static final MassifObject.Key<Boolean> DEBUG_TILE_BORDERS = MassifObject.key("debugTileBorders");
    /** Returns the default layer buffer in tile pixels. */
    public static final MassifObject.Key<Double> DEFAULT_LAYER_BUFFER = MassifObject.key("defaultLayerBuffer");
    /** Calculates the difference vector between the maximum and minimum map positions of this map bounds object. */
    public static final MassifObject.Key<String> DELTA = MassifObject.key("delta");
    /** Returns the clip-space depth bias used when depth-testing draped 2D geometry against the terrain. */
    public static final MassifObject.Key<Double> DEPTH_BIAS = MassifObject.key("depthBias");
    /** Returns the description of this balloon popup. */
    public static final MassifObject.Key<String> DESCRIPTION = MassifObject.key("description");
    /** Returns the color of the description. */
    public static final MassifObject.Key<Integer> DESCRIPTION_COLOR = MassifObject.key("descriptionColor");
    /** Returns the description field variable to use. */
    public static final MassifObject.Key<String> DESCRIPTION_FIELD = MassifObject.key("descriptionField");
    /** Returns the name of the description font. */
    public static final MassifObject.Key<String> DESCRIPTION_FONT_NAME = MassifObject.key("descriptionFontName");
    /** Returns the size of the description font. */
    public static final MassifObject.Key<Long> DESCRIPTION_FONT_SIZE = MassifObject.key("descriptionFontSize");
    /** Returns the margins of the description. */
    public static final MassifObject.Key<String> DESCRIPTION_MARGINS = MassifObject.key("descriptionMargins");
    /** Returns the state of the description wrap parameter. */
    public static final MassifObject.Key<Boolean> DESCRIPTION_WRAP = MassifObject.key("descriptionWrap");
    /** Returns the full path of the directory containing the assets. */
    public static final MassifObject.Key<String> DIR_PATH = MassifObject.key("dirPath");
    /** Returns true if the object is anchored by direction, false if by geographic position. */
    public static final MassifObject.Key<Boolean> DIRECTION_ANCHORED = MassifObject.key("directionAnchored");
    /** Returns the distance of a direction-anchored object. */
    public static final MassifObject.Key<Double> DISTANCE = MassifObject.key("distance");
    /** Returns the floating point value of this variant. */
    public static final MassifObject.Key<Double> DOUBLE = MassifObject.key("double");
    /** Returns the double click detection state. */
    public static final MassifObject.Key<Boolean> DOUBLE_CLICK_DETECTION = MassifObject.key("doubleClickDetection");
    /** Returns the double click max duration in seconds. */
    public static final MassifObject.Key<Double> DOUBLE_CLICK_MAX_DURATION = MassifObject.key("doubleClickMaxDuration");
    /** Returns whether polygon fills are draped as a render-to-texture surface. */
    public static final MassifObject.Key<Boolean> DRAPE_FILLS_ENABLED = MassifObject.key("drapeFillsEnabled");
    /** Returns whether vt tile lines are also draped (in addition to fills). */
    public static final MassifObject.Key<Boolean> DRAPE_LINES_ENABLED = MassifObject.key("drapeLinesEnabled");
    /** Returns the per-tile drape texture resolution, 0 when it follows the screen. */
    public static final MassifObject.Key<Long> DRAPE_RESOLUTION = MassifObject.key("drapeResolution");
    /** Returns the draw distance value. */
    public static final MassifObject.Key<Double> DRAW_DISTANCE = MassifObject.key("drawDistance");
    /** Returns the click duration in seconds. */
    public static final MassifObject.Key<Double> DURATION = MassifObject.key("duration");
    /** Returns the corresponding matching edge index in the matching result. */
    public static final MassifObject.Key<Long> EDGE_INDEX = MassifObject.key("edgeIndex");
    /** Returns the 2D click position on the clicked popup. */
    public static final MassifObject.Key<String> ELEMENT_CLICK_POS = MassifObject.key("elementClickPos");
    /** Returns the info tag of the clicked element. */
    public static final MassifObject.Key<String> ELEMENT_INFO = MassifObject.key("elementInfo");
    /** Returns the list of vector elements. */
    public static final MassifObject.Key<String> ELEMENTS = MassifObject.key("elements");
    /** Returns whether the normal map encodes absolute elevation (so a custom normal-map lighting shader can call getElevation()). */
    public static final MassifObject.Key<Boolean> ELEVATION_ENCODING_ENABLED = MassifObject.key("elevationEncodingEnabled");
    /** Returns whether elevation tile prefetching is enabled. */
    public static final MassifObject.Key<Boolean> ELEVATION_PREFETCH_ENABLED = MassifObject.key("elevationPrefetchEnabled");
    /** Returns whether the fog is drawn at all. */
    public static final MassifObject.Key<Boolean> ENABLED = MassifObject.key("enabled");
    /** Returns the number of threads used by the envelope task pool. */
    public static final MassifObject.Key<Long> ENVELOPE_THREAD_POOL_SIZE = MassifObject.key("envelopeThreadPoolSize");
    /** Returns the normal vector tile should be exagerated based on the zoom level. */
    public static final MassifObject.Key<Boolean> EXAGERATE_HEIGHT_SCALE_ENABLED = MassifObject.key("exagerateHeightScaleEnabled");
    /** Returns the per-frame relief exaggeration factor, i.e. the vertical exaggeration of the slope. Unlike height scale this is a shader uniform applied at render time (no tile re-decode), so it can be animated smoothly. */
    public static final MassifObject.Key<Double> EXAGGERATION = MassifObject.key("exaggeration");
    /** Returns the fade animation type. */
    public static final MassifObject.Key<String> FADE_ANIMATION_TYPE = MassifObject.key("fadeAnimationType");
    /** Returns the far plane distance. */
    public static final MassifObject.Key<Double> FAR = MassifObject.key("far");
    /** Returns the clicked feature. */
    public static final MassifObject.Key<MassifObject> FEATURE = MassifObject.key("feature");
    /** Returns the position on the clicked feature, that is close to the click position. For points it will always be the center position, for lines it will be the closest point on the line, for billboards it will be the anchor point and for polygons it's equal to getClickPos(). */
    public static final MassifObject.Key<String> FEATURE_CLICK_POS = MassifObject.key("featureClickPos");
    /** Returns the feature collection of the search service. */
    public static final MassifObject.Key<MassifObject> FEATURE_COLLECTION = MassifObject.key("featureCollection");
    /** Returns the number of features in this container. */
    public static final MassifObject.Key<Long> FEATURE_COUNT = MassifObject.key("featureCount");
    /** Returns the id of the clicked feature. */
    public static final MassifObject.Key<Long> FEATURE_ID = MassifObject.key("featureId");
    /** Returns the value of feature id override flag. This is intended for cases when feature ids in tile are not globally unique. */
    public static final MassifObject.Key<Boolean> FEATURE_ID_OVERRIDE = MassifObject.key("featureIdOverride");
    /** Returns the name of the layer of the clicked feature. Note that this is the layer name in the tile, not the name of style layer. */
    public static final MassifObject.Key<String> FEATURE_LAYER_NAME = MassifObject.key("featureLayerName");
    /** Returns the position of the clicked feature. For a MultiPoint this is the point that was clicked, not the centre of the whole set - which getFeatureClickPos deliberately does not cover, and which a caller otherwise has to reconstruct from getFeaturePosIndex plus a downcast. */
    public static final MassifObject.Key<String> FEATURE_POS = MassifObject.key("featurePos");
    /** In case of MultiPoint PointGeometry this will return the index of the clicked position */
    public static final MassifObject.Key<Long> FEATURE_POS_INDEX = MassifObject.key("featurePosIndex");
    /** Returns the vertial field of view angle. */
    public static final MassifObject.Key<Long> FIELD_OF_VIEW_Y = MassifObject.key("fieldOfViewY");
    /** Returns the string based search expression. If empty, then search expression is not used. */
    public static final MassifObject.Key<String> FILTER_EXPRESSION = MassifObject.key("filterExpression");
    /** Returns how far a flattened terrain goes back towards a plain 2D map. */
    public static final MassifObject.Key<String> FLATTEN_MODE = MassifObject.key("flattenMode");
    /** Returns how far the terrain is flattened right now, 0 (full 3D) to 1 (flat). */
    public static final MassifObject.Key<Double> FLATTEN_RATIO = MassifObject.key("flattenRatio");
    /** Returns whether the map is asked to render flat. This is the 2D/3D state, whether it was set by the app or by auto-flattening; the switch itself is animated, so for a moment after a change the map is still on its way there. */
    public static final MassifObject.Key<Boolean> FLATTENED = MassifObject.key("flattened");
    /** Returns true while a flyTo animation is running. */
    public static final MassifObject.Key<Boolean> FLIGHT_ACTIVE = MassifObject.key("flightActive");
    /** How far along a flyTo animation is, from 0 to 1, or -1 when none is running. It is the value the camera is actually at, so an app animating its own state alongside the move (a layer fading in, a mode switching over) reads it rather than running its own clock. */
    public static final MassifObject.Key<Double> FLIGHT_PROGRESS = MassifObject.key("flightProgress");
    /** Returns the state of the flippable flag. */
    public static final MassifObject.Key<Boolean> FLIPPABLE = MassifObject.key("flippable");
    /** Returns the focus point offset (from screen center) in pixels. */
    public static final MassifObject.Key<String> FOCUS_POINT_OFFSET = MassifObject.key("focusPointOffset");
    /** Returns the position that the camera is currently looking at. */
    public static final MassifObject.Key<String> FOCUS_POS = MassifObject.key("focusPos");
    /** Returns the fog (atmosphere) options. May be null. */
    public static final MassifObject.Key<MassifObject> FOG_OPTIONS = MassifObject.key("fogOptions");
    /** Returns the font's color. */
    public static final MassifObject.Key<Integer> FONT_COLOR = MassifObject.key("fontColor");
    /** Returns the font's name. */
    public static final MassifObject.Key<String> FONT_NAME = MassifObject.key("fontName");
    /** Returns the font's size. */
    public static final MassifObject.Key<Double> FONT_SIZE = MassifObject.key("fontSize");
    /** Returns the fragment shader source of the effect. */
    public static final MassifObject.Key<String> FRAGMENT_SHADER = MassifObject.key("fragmentShader");
    /** Returns the frame count defined in the Torque style. */
    public static final MassifObject.Key<Long> FRAME_COUNT = MassifObject.key("frameCount");
    /** Returns the time of this map tile. */
    public static final MassifObject.Key<Long> FRAME_NR = MassifObject.key("frameNr");
    /** Returns how fast a free roam drag turns the view. */
    public static final MassifObject.Key<Double> FREE_ROAM_LOOK_SENSITIVITY = MassifObject.key("freeRoamLookSensitivity");
    /** Returns the free roam mode. */
    public static final MassifObject.Key<String> FREE_ROAM_MODE = MassifObject.key("freeRoamMode");
    /** Returns how far a first person move drag travels. */
    public static final MassifObject.Key<Double> FREE_ROAM_MOVE_SPEED = MassifObject.key("freeRoamMoveSpeed");
    /** Returns the green component of this map color. */
    public static final MassifObject.Key<Long> G = MassifObject.key("g");
    /** Returns the geometry as a GeoJSON string, in its own coordinates. Here rather than only on Feature because serialising a shape otherwise means constructing a GeoJSONGeometryWriter, which no string-based binding can do. */
    public static final MassifObject.Key<String> GEO_JSON = MassifObject.key("geoJSON");
    /** Returns the geometry object that defines the location of this billboard. */
    public static final MassifObject.Key<MassifObject> GEOMETRY = MassifObject.key("geometry");
    /** Returns the number of geometry objects in this multi geometry container. */
    public static final MassifObject.Key<Long> GEOMETRY_COUNT = MassifObject.key("geometryCount");
    /** Returns the feature's geometry as a GeoJSON string, in its own coordinates. Serialising a geometry otherwise means constructing a GeoJSONGeometryWriter in the binding, which every binding then does differently and, in a scripting one, slowly. */
    public static final MassifObject.Key<String> GEOMETRY_GEO_JSON = MassifObject.key("geometryGeoJSON");
    /** Returns the active geometry simplifier of the data source. */
    public static final MassifObject.Key<MassifObject> GEOMETRY_SIMPLIFIER = MassifObject.key("geometrySimplifier");
    /** Returns the geometry tag associated with the instructions. */
    public static final MassifObject.Key<String> GEOMETRY_TAG = MassifObject.key("geometryTag");
    /** Returns the ground color. */
    public static final MassifObject.Key<Integer> GROUND_COLOR = MassifObject.key("groundColor");
    /** Returns the tint applied to Mie scattering. */
    public static final MassifObject.Key<Integer> HALO_COLOR = MassifObject.key("haloColor");
    /** Returns the height of the bitmap. */
    public static final MassifObject.Key<String> HEIGHT = MassifObject.key("height");
    /** Returns the height scale of the hillshade overlay. */
    public static final MassifObject.Key<Double> HEIGHT_SCALE = MassifObject.key("heightScale");
    /** Returns the state of the allow overlap flag. */
    public static final MassifObject.Key<Boolean> HIDE_IF_OVERLAPPED = MassifObject.key("hideIfOverlapped");
    /** Returns the color of the upper atmosphere. */
    public static final MassifObject.Key<Integer> HIGH_COLOR = MassifObject.key("highColor");
    /** Returns the shading color of areas that faces towards the light source. */
    public static final MassifObject.Key<Integer> HIGHLIGHT_COLOR = MassifObject.key("highlightColor");
    /** Returns the hillshade rendering method. */
    public static final MassifObject.Key<String> HILLSHADE_METHOD = MassifObject.key("hillshadeMethod");
    /** Returns the list of map position lists defining the inner rings of the polygon (holes). */
    public static final MassifObject.Key<String> HOLES = MassifObject.key("holes");
    /** Returns how far up the sky the fog is blended in. */
    public static final MassifObject.Key<Double> HORIZON_BLEND = MassifObject.key("horizonBlend");
    /** Returns the horizon color. */
    public static final MassifObject.Key<Integer> HORIZON_COLOR = MassifObject.key("horizonColor");
    /** Returns the horizontal offset of the billboard. */
    public static final MassifObject.Key<Double> HORIZONTAL_OFFSET = MassifObject.key("horizontalOffset");
    /** Returns the house number included in the address. */
    public static final MassifObject.Key<String> HOUSE_NUMBER = MassifObject.key("houseNumber");
    /** Returns the internal id of this vector element. */
    public static final MassifObject.Key<Long> ID = MassifObject.key("id");
    /** Returns the illumination direction of the layer. */
    public static final MassifObject.Key<String> ILLUMINATION_DIRECTION = MassifObject.key("illuminationDirection");
    /** Returns wheter the illumination direction should change with the map rotation. */
    public static final MassifObject.Key<Boolean> ILLUMINATION_MAP_ROTATION_ENABLED = MassifObject.key("illuminationMapRotationEnabled");
    /** Returns the optional instruction description. This info is dependent on the routing engine (can be empty) and may be localized. */
    public static final MassifObject.Key<String> INSTRUCTION = MassifObject.key("instruction");
    /** Returns the number of turn-by-turn instructions. */
    public static final MassifObject.Key<Long> INSTRUCTION_COUNT = MassifObject.key("instructionCount");
    /** Returns the turn-by-turn instruction list. */
    public static final MassifObject.Key<String> INSTRUCTIONS = MassifObject.key("instructions");
    /** Returns every turn-by-turn instruction as one JSON array. A maneuver is nine scalars, and reading them one instruction at a time costs a call per field: a mountain route has hundreds. The keys are the property names (`action`, `pointIndex`, `streetName`, `instruction`, `turnAngle`, `azimuth`, `distance`, `time`), and `action` is the enum's constant name. */
    public static final MassifObject.Key<String> INSTRUCTIONS_JSON = MassifObject.key("instructionsJSON");
    /** Returns the interpolated color at the click position. */
    public static final MassifObject.Key<Integer> INTERPOLATED_COLOR = MassifObject.key("interpolatedColor");
    /** Returns the state of the kinetic panning flag. */
    public static final MassifObject.Key<Boolean> KINETIC_PAN = MassifObject.key("kineticPan");
    /** Returns the state of the kinetic rotation flag. */
    public static final MassifObject.Key<Boolean> KINETIC_ROTATION = MassifObject.key("kineticRotation");
    /** Returns the state of kinetic zoom flag. */
    public static final MassifObject.Key<Boolean> KINETIC_ZOOM = MassifObject.key("kineticZoom");
    /** Returns the current relative label blending speed. */
    public static final MassifObject.Key<Double> LABEL_BLENDING_SPEED = MassifObject.key("labelBlendingSpeed");
    /** Returns the contour interval used for label stubs. */
    public static final MassifObject.Key<Double> LABEL_INTERVAL = MassifObject.key("labelInterval");
    /** Returns the current display order of the labels. */
    public static final MassifObject.Key<String> LABEL_RENDER_ORDER = MassifObject.key("labelRenderOrder");
    /** Returns whether only short label stubs are generated instead of full contour lines. */
    public static final MassifObject.Key<Boolean> LABEL_STUBS_ENABLED = MassifObject.key("labelStubsEnabled");
    public static final MassifObject.Key<String> LANGUAGE = MassifObject.key("language");
    /** Returns the layer of the raster tile. */
    public static final MassifObject.Key<MassifObject> LAYER = MassifObject.key("layer");
    /** Returns the current relative layer blending speed. */
    public static final MassifObject.Key<Double> LAYER_BLENDING_SPEED = MassifObject.key("layerBlendingSpeed");
    /** Returns the name of the generated vector tile layer. */
    public static final MassifObject.Key<String> LAYER_NAME = MassifObject.key("layerName");
    /** Returns the layers to filter while decoding tiles. */
    public static final MassifObject.Key<String> LAYERS = MassifObject.key("layers");
    /** Returns wether layers are processed in reversed order to process labels. */
    public static final MassifObject.Key<Boolean> LAYERS_LABELS_PROCESSED_IN_REVERSE_ORDER = MassifObject.key("layersLabelsProcessedInReverseOrder");
    public static final MassifObject.Key<Long> LEFT = MassifObject.key("left");
    /** Returns the background color of the left part of the popup. */
    public static final MassifObject.Key<Integer> LEFT_COLOR = MassifObject.key("leftColor");
    /** Returns the image of the left part of the popup. */
    public static final MassifObject.Key<MassifObject> LEFT_IMAGE = MassifObject.key("leftImage");
    /** Returns the margins of the left part of the popup. */
    public static final MassifObject.Key<String> LEFT_MARGINS = MassifObject.key("leftMargins");
    /** Returns whether the legacy (pre-MapLibre-parity) height scale formula is used. */
    public static final MassifObject.Key<Boolean> LEGACY_HEIGHT_SCALE_ENABLED = MassifObject.key("legacyHeightScaleEnabled");
    /** Calculates the length of this map range. Defined as max - min. */
    public static final MassifObject.Key<Double> LENGTH = MassifObject.key("length");
    /** Returns the length of the arrow after the maneuver point. */
    public static final MassifObject.Key<Double> LENGTH_AFTER = MassifObject.key("lengthAfter");
    /** Returns the length of the arrow before the maneuver point. */
    public static final MassifObject.Key<Double> LENGTH_BEFORE = MassifObject.key("lengthBefore");
    /** Returns the light (sun) options. May be null. */
    public static final MassifObject.Key<MassifObject> LIGHT_OPTIONS = MassifObject.key("lightOptions");
    /** Returns the end point type of the line. */
    public static final MassifObject.Key<String> LINE_END_TYPE = MassifObject.key("lineEndType");
    /** Returns the join type of the line. */
    public static final MassifObject.Key<String> LINE_JOIN_TYPE = MassifObject.key("lineJoinType");
    /** Returns the line style. */
    public static final MassifObject.Key<MassifObject> LINE_STYLE = MassifObject.key("lineStyle");
    /** Returns the list of assets found in the bundle, ignoring the base asset package. */
    public static final MassifObject.Key<String> LOCAL_ASSET_NAMES = MassifObject.key("localAssetNames");
    public static final MassifObject.Key<String> LOCAL_PACKAGES = MassifObject.key("localPackages");
    /** Returns the locality (city, town, village) name included in the address. */
    public static final MassifObject.Key<String> LOCALITY = MassifObject.key("locality");
    /** Returns the location attribute of the request. The matching address near the specified location (up to a specified radius) are preferred. */
    public static final MassifObject.Key<String> LOCATION = MassifObject.key("location");
    /** Returns the location radius attribute of the request (in meters). */
    public static final MassifObject.Key<Double> LOCATION_RADIUS = MassifObject.key("locationRadius");
    /** Returns the current log listener. */
    public static final MassifObject.Key<MassifObject> LOG_EVENT_LISTENER = MassifObject.key("logEventListener");
    /** Returns the integer value of this variant. */
    public static final MassifObject.Key<Long> LONG = MassifObject.key("long");
    /** Returns the long click duration in seconds. */
    public static final MassifObject.Key<Double> LONG_CLICK_DURATION = MassifObject.key("longClickDuration");
    /** Returns the color of the main light. */
    public static final MassifObject.Key<Integer> MAIN_LIGHT_COLOR = MassifObject.key("mainLightColor");
    /** Returns the direction of the main light. */
    public static final MassifObject.Key<String> MAIN_LIGHT_DIRECTION = MassifObject.key("mainLightDirection");
    /** Returns the drag position in projection coordinate system of the layer. */
    public static final MassifObject.Key<String> MAP_POS = MassifObject.key("mapPos");
    /** Returns the map renderer listener. Can be null. */
    public static final MassifObject.Key<MassifObject> MAP_RENDERER_LISTENER = MassifObject.key("mapRendererListener");
    /** Returns the tile id of the clicked feature. */
    public static final MassifObject.Key<String> MAP_TILE = MassifObject.key("mapTile");
    /** Returns the list with details of the matched edges. */
    public static final MassifObject.Key<String> MATCHING_EDGES = MassifObject.key("matchingEdges");
    /** Returns the list with details of the matched points. */
    public static final MassifObject.Key<String> MATCHING_POINTS = MassifObject.key("matchingPoints");
    /** Returns the maximum (north east) map position of this map envelope object. */
    public static final MassifObject.Key<String> MAX = MassifObject.key("max");
    /** Returns the maximum age of the tile data, tile data will expire after that point. */
    public static final MassifObject.Key<Long> MAX_AGE = MassifObject.key("maxAge");
    /** Returns true/false based on whether the max-age header check is used. If this is enabled, SDK will automatically refresh the tiles when tiles have expired. */
    public static final MassifObject.Key<Boolean> MAX_AGE_HEADER_CHECK = MassifObject.key("maxAgeHeaderCheck");
    /** Gets the current maximum overzoom level for this datasource. Over it the datasource will not be "drawn" */
    public static final MassifObject.Key<Long> MAX_OVERZOOM_LEVEL = MassifObject.key("maxOverzoomLevel");
    /** Returns the maximum number of results the search service returns. */
    public static final MassifObject.Key<Long> MAX_RESULTS = MassifObject.key("maxResults");
    /** Returns how many zoom levels below the camera a tile may coarsen to. */
    public static final MassifObject.Key<Long> MAX_TILE_ZOOM_COARSENING = MassifObject.key("maxTileZoomCoarsening");
    /** Returns the maximum visible tile zoom offset, relative to the camera zoom level. */
    public static final MassifObject.Key<Long> MAX_TILE_ZOOM_OFFSET = MassifObject.key("maxTileZoomOffset");
    /** Gets the current maximum underzoom level for this layer. */
    public static final MassifObject.Key<Long> MAX_UNDERZOOM_LEVEL = MassifObject.key("maxUnderzoomLevel");
    /** Returns the maximum zoom level supported by this data source. */
    public static final MassifObject.Key<Long> MAX_ZOOM = MassifObject.key("maxZoom");
    /** Returns maximum zoom level encoded in this tilemask. */
    public static final MassifObject.Key<Long> MAX_ZOOM_LEVEL = MassifObject.key("maxZoomLevel");
    /** Returns the maximum zoom level when clusters are shown. If zoom level is greater, then clusters are replaced with individual elements. Default is 24. */
    public static final MassifObject.Key<Double> MAXIMUM_CLUSTER_ZOOM = MassifObject.key("maximumClusterZoom");
    /** Returns the terrain mesh resolution. */
    public static final MassifObject.Key<Long> MESH_RESOLUTION = MassifObject.key("meshResolution");
    /** Returns a copy of the layer meta data map. The changes you make to this map are NOT reflected in the actual meta data of the layer. */
    public static final MassifObject.Key<String> META_DATA = MassifObject.key("metaData");
    /** Returns package meta info. If package contains no meta info, null is returned. */
    public static final MassifObject.Key<MassifObject> META_INFO = MassifObject.key("metaInfo");
    /** Calculate the midrange value. */
    public static final MassifObject.Key<Double> MIDRANGE = MassifObject.key("midrange");
    /** Returns the minimum (south west) map position of this map envelope object. */
    public static final MassifObject.Key<String> MIN = MassifObject.key("min");
    /** Returns the minimum zoom at which contour geometry is generated. */
    public static final MassifObject.Key<Long> MIN_VISIBLE_ZOOM = MassifObject.key("minVisibleZoom");
    /** Returns the minimum tile zoom level with 3D terrain. */
    public static final MassifObject.Key<Long> MIN_ZOOM = MassifObject.key("minZoom");
    /** Returns the current minimum distance between clusters (in device-independent pixels). */
    public static final MassifObject.Key<Double> MINIMUM_CLUSTER_DISTANCE = MassifObject.key("minimumClusterDistance");
    /** Returns the model asset of the object. */
    public static final MassifObject.Key<MassifObject> MODEL_ASSET = MassifObject.key("modelAsset");
    /** Returns the name included in the address. */
    public static final MassifObject.Key<String> NAME = MassifObject.key("name");
    /** Returns the near plane distance. */
    public static final MassifObject.Key<Double> NEAR = MassifObject.key("near");
    /** Returns the color of the nearest pixel to the click position. */
    public static final MassifObject.Key<Integer> NEAREST_COLOR = MassifObject.key("nearestColor");
    /** Returns the local neighbourhood name included in the address. */
    public static final MassifObject.Key<String> NEIGHBOURHOOD = MassifObject.key("neighbourhood");
    /** Returns the style layers that are kept out of the terrain drape bake. */
    public static final MassifObject.Key<String> NO_DRAPE_LAYER_FILTER = MassifObject.key("noDrapeLayerFilter");
    public static final MassifObject.Key<String> NORMAL_MAP_LIGHTING_SHADER = MassifObject.key("normalMapLightingShader");
    /** Creates a new map vector by normalizing this map vector. */
    public static final MassifObject.Key<String> NORMALIZED = MassifObject.key("normalized");
    /** Returns all the keys in the object. */
    public static final MassifObject.Key<String> OBJECT_KEYS = MassifObject.key("objectKeys");
    /** Returns the opacity of this layer. */
    public static final MassifObject.Key<Double> OPACITY = MassifObject.key("opacity");
    /** Returns the status of the cache database. */
    public static final MassifObject.Key<Boolean> OPEN = MassifObject.key("open");
    /** Returns the orientation mode of the label. */
    public static final MassifObject.Key<String> ORIENTATION_MODE = MassifObject.key("orientationMode");
    /** Returns the internal package id. This should not be displayed to the user. */
    public static final MassifObject.Key<String> PACKAGE_ID = MassifObject.key("packageId");
    /** Returns the package manager instance used by the data source. */
    public static final MassifObject.Key<MassifObject> PACKAGE_MANAGER = MassifObject.key("packageManager");
    public static final MassifObject.Key<MassifObject> PACKAGE_MANAGER_LISTENER = MassifObject.key("packageManagerListener");
    /** Returns the package type. */
    public static final MassifObject.Key<String> PACKAGE_TYPE = MassifObject.key("packageType");
    /** Returns true if the interaction included a map pan action. */
    public static final MassifObject.Key<Boolean> PAN_ACTION = MassifObject.key("panAction");
    /** Returns the map panning bounds constraints. Map bounds minimum and maximum points are in the base projection's coordinate system. */
    public static final MassifObject.Key<String> PAN_BOUNDS = MassifObject.key("panBounds");
    /** Returns the panning mode. */
    public static final MassifObject.Key<String> PANNING_MODE = MassifObject.key("panningMode");
    /** Returns the panning speed mode. */
    public static final MassifObject.Key<String> PANNING_SPEED_MODE = MassifObject.key("panningSpeedMode");
    /** Returns the value of the specified style parameter. The style parameter must be declared in the current style. */
    public static final MassifObject.Key<String> PARAMS = MassifObject.key("params");
    /** Returns the paused state of the action. */
    public static final MassifObject.Key<Boolean> PAUSED = MassifObject.key("paused");
    /** Returns the phase-in duration of the animation. */
    public static final MassifObject.Key<Double> PHASE_IN_DURATION = MassifObject.key("phaseInDuration");
    /** Returns the phase-out duration of the animation. */
    public static final MassifObject.Key<Double> PHASE_OUT_DURATION = MassifObject.key("phaseOutDuration");
    /** Returns the pivot mode. */
    public static final MassifObject.Key<String> PIVOT_MODE = MassifObject.key("pivotMode");
    /** Returns the placement priority of the billboard. */
    public static final MassifObject.Key<Long> PLACEMENT_PRIORITY = MassifObject.key("placementPriority");
    /** Returns the number of points in the path. */
    public static final MassifObject.Key<Long> POINT_COUNT = MassifObject.key("pointCount");
    /** Returns the index of the first geometry point in external point array. */
    public static final MassifObject.Key<Long> POINT_INDEX = MassifObject.key("pointIndex");
    /** Returns the point style. */
    public static final MassifObject.Key<MassifObject> POINT_STYLE = MassifObject.key("pointStyle");
    /** Returns the measured points of the request. */
    public static final MassifObject.Key<String> POINTS = MassifObject.key("points");
    /** Returns the polygon style. */
    public static final MassifObject.Key<MassifObject> POLYGON_STYLE = MassifObject.key("polygonStyle");
    /** Returns the clicked popup. */
    public static final MassifObject.Key<MassifObject> POPUP = MassifObject.key("popup");
    /** Returns the handler used for the popup. */
    public static final MassifObject.Key<MassifObject> POPUP_HANDLER = MassifObject.key("popupHandler");
    /** Returns the position of the point. */
    public static final MassifObject.Key<String> POS = MassifObject.key("pos");
    /** Returns the list of of map positions defining the line. */
    public static final MassifObject.Key<String> POSES = MassifObject.key("poses");
    /** Returns the geographic position of a position-anchored object. */
    public static final MassifObject.Key<String> POSITION = MassifObject.key("position");
    /** Returns the altitude of a position-anchored object. */
    public static final MassifObject.Key<Double> POSITION_ALTITUDE = MassifObject.key("positionAltitude");
    /** Returns whether this layer goes through the post-process effect. */
    public static final MassifObject.Key<Boolean> POST_PROCESSED = MassifObject.key("postProcessed");
    /** Returns the postcode of the address. */
    public static final MassifObject.Key<String> POSTCODE = MassifObject.key("postcode");
    /** Returns the state of the preloading flag of this layer. */
    public static final MassifObject.Key<Boolean> PRELOADING = MassifObject.key("preloading");
    /** Returns wether to prevent duplicate elements */
    public static final MassifObject.Key<Boolean> PREVENT_DUPLICATES = MassifObject.key("preventDuplicates");
    public static final MassifObject.Key<String> PROFILE = MassifObject.key("profile");
    /** Returns the progress of the action. */
    public static final MassifObject.Key<Double> PROGRESS = MassifObject.key("progress");
    /** Returns the projection of the feature collection of the search service. */
    public static final MassifObject.Key<MassifObject> PROJECTION = MassifObject.key("projection");
    /** Returns the properties of the feature. */
    public static final MassifObject.Key<String> PROPERTIES = MassifObject.key("properties");
    /** Returns how finely the atmosphere is integrated. */
    public static final MassifObject.Key<String> QUALITY = MassifObject.key("quality");
    /** Returns the text-based query of the request. */
    public static final MassifObject.Key<String> QUERY = MassifObject.key("query");
    /** Returns the red component of this map color. */
    public static final MassifObject.Key<Long> R = MassifObject.key("r");
    /** Returns the angular radius of a circular arc. */
    public static final MassifObject.Key<Double> RADIUS = MassifObject.key("radius");
    /** Returns where the fog reaches full strength. */
    public static final MassifObject.Key<Double> RANGE_END = MassifObject.key("rangeEnd");
    /** Returns where the fog starts. */
    public static final MassifObject.Key<Double> RANGE_START = MassifObject.key("rangeStart");
    /** Returns the rank of the result. The rank is a normalized number between 0 and 1, 1 meaning a perfect match. */
    public static final MassifObject.Key<Double> RANK = MassifObject.key("rank");
    /** Returns the raster tile event listener. */
    public static final MassifObject.Key<MassifObject> RASTER_TILE_EVENT_LISTENER = MassifObject.key("rasterTileEventListener");
    /** Returns raw result */
    public static final MassifObject.Key<String> RAW_RESULT = MassifObject.key("rawResult");
    /** Returns what caused the movement. */
    public static final MassifObject.Key<String> REASON = MassifObject.key("reason");
    /** Returns the regular expression used to search all the fields. If empty, then the regular expression is not used. */
    public static final MassifObject.Key<String> REGEX_FILTER = MassifObject.key("regexFilter");
    /** Returns the region name included in the address. */
    public static final MassifObject.Key<String> REGION = MassifObject.key("region");
    /** Returns the relative speed of the animation. */
    public static final MassifObject.Key<Double> RELATIVE_SPEED = MassifObject.key("relativeSpeed");
    /** Returns the render projection mode. */
    public static final MassifObject.Key<String> RENDER_PROJECTION_MODE = MassifObject.key("renderProjectionMode");
    /** Returns the relative rendering scale of the label. */
    public static final MassifObject.Key<Double> RENDER_SCALE = MassifObject.key("renderScale");
    /** Returns the renderer layer filter. The filter is given as ECMA regular expression that is applied to qualified layer names. */
    public static final MassifObject.Key<String> RENDERER_LAYER_FILTER = MassifObject.key("rendererLayerFilter");
    /** Returns true if the tile should be replaced with parent tile. */
    public static final MassifObject.Key<Boolean> REPLACE_WITH_PARENT = MassifObject.key("replaceWithParent");
    /** Returns the target grid resolution used for contour tracing. */
    public static final MassifObject.Key<Long> RESOLUTION = MassifObject.key("resolution");
    /** Returns the state of the restricted panning flag. */
    public static final MassifObject.Key<Boolean> RESTRICTED_PANNING = MassifObject.key("restrictedPanning");
    public static final MassifObject.Key<Long> RIGHT = MassifObject.key("right");
    /** Returns the background color of the right part of the popup. */
    public static final MassifObject.Key<Integer> RIGHT_COLOR = MassifObject.key("rightColor");
    /** Returns the image of the right part of the popup. */
    public static final MassifObject.Key<MassifObject> RIGHT_IMAGE = MassifObject.key("rightImage");
    /** Returns the margins of the right part of the popup. */
    public static final MassifObject.Key<String> RIGHT_MARGINS = MassifObject.key("rightMargins");
    /** Returns the list of map position lists defining the rings of the polygon. */
    public static final MassifObject.Key<String> RINGS = MassifObject.key("rings");
    /** Returns the location of the root billboard. If this billboard has a location, this method is equavalent to the Billboard::getGeometry method. If this billboard is attached to another billboard, the hierarchy is traveled recursively and the location of the root billboard is returned. */
    public static final MassifObject.Key<MassifObject> ROOT_GEOMETRY = MassifObject.key("rootGeometry");
    /** Returns the state of the map rotatability flag. */
    public static final MassifObject.Key<Boolean> ROTATABLE = MassifObject.key("rotatable");
    /** Returns true if the interaction included a rotate action. */
    public static final MassifObject.Key<Boolean> ROTATE_ACTION = MassifObject.key("rotateAction");
    /** Returns the map rotation in degrees. 0 means looking north, 90 means west, -90 means east and 180 means south. */
    public static final MassifObject.Key<Double> ROTATION = MassifObject.key("rotation");
    /** Returns the rotation angle of this model. This is deprecated. Use getRotation instead. */
    public static final MassifObject.Key<Double> ROTATION_ANGLE = MassifObject.key("rotationAngle");
    /** Returns the rotation axis of this model. If rotation angle is 0, then the axis is irrelevant. */
    public static final MassifObject.Key<String> ROTATION_AXIS = MassifObject.key("rotationAxis");
    /** Returns the state of rotation gestures. */
    public static final MassifObject.Key<Boolean> ROTATION_GESTURES = MassifObject.key("rotationGestures");
    /** Returns the scale of this model. */
    public static final MassifObject.Key<Double> SCALE = MassifObject.key("scale");
    /** Returns the state of the scale with DPI flag. */
    public static final MassifObject.Key<Boolean> SCALE_WITH_DPI = MassifObject.key("scaleWithDPI");
    /** Returns the scaling mode of the label. */
    public static final MassifObject.Key<String> SCALING_MODE = MassifObject.key("scalingMode");
    /** Returns the screen bounds, so that the popup can be clipped if neccessary. */
    public static final MassifObject.Key<String> SCREEN_BOUNDS = MassifObject.key("screenBounds");
    /** Returns the screen height. */
    public static final MassifObject.Key<Long> SCREEN_HEIGHT = MassifObject.key("screenHeight");
    /** Returns the drag position in screen coordinates. */
    public static final MassifObject.Key<String> SCREEN_POS = MassifObject.key("screenPos");
    /** Returns the screen size of the sprite. */
    public static final MassifObject.Key<Double> SCREEN_SIZE = MassifObject.key("screenSize");
    /** Returns the screen width. */
    public static final MassifObject.Key<Long> SCREEN_WIDTH = MassifObject.key("screenWidth");
    /** Returns whether seamless tile edges are enabled. */
    public static final MassifObject.Key<Boolean> SEAMLESS_EDGES_ENABLED = MassifObject.key("seamlessEdgesEnabled");
    /** Returns the state of seamless horizontal panning flag. */
    public static final MassifObject.Key<Boolean> SEAMLESS_PANNING = MassifObject.key("seamlessPanning");
    /** Returns whether seamless tile edge handling is enabled. */
    public static final MassifObject.Key<Boolean> SEAMLESS_TILE_EDGES_ENABLED = MassifObject.key("seamlessTileEdgesEnabled");
    /** Returns the search radius (in meters). */
    public static final MassifObject.Key<Double> SEARCH_RADIUS = MassifObject.key("searchRadius");
    /** Returns true if the directions are read as separate segments rather than as a path. */
    public static final MassifObject.Key<Boolean> SEGMENTED = MassifObject.key("segmented");
    /** Returns the selected vector element. If no element is currently selected, null is returned. */
    public static final MassifObject.Key<MassifObject> SELECTED_VECTOR_ELEMENT = MassifObject.key("selectedVectorElement");
    public static final MassifObject.Key<Long> SERVER_PACKAGE_LIST_AGE = MassifObject.key("serverPackageListAge");
    public static final MassifObject.Key<MassifObject> SERVER_PACKAGE_LIST_META_INFO = MassifObject.key("serverPackageListMetaInfo");
    public static final MassifObject.Key<String> SERVER_PACKAGES = MassifObject.key("serverPackages");
    /** Returns the custom fragment shader source. */
    public static final MassifObject.Key<String> SHADER_SOURCE = MassifObject.key("shaderSource");
    /** Returns the shadow depth bias. */
    public static final MassifObject.Key<Double> SHADOW_BIAS = MassifObject.key("shadowBias");
    /** Returns the number of shadow cascades. */
    public static final MassifObject.Key<Long> SHADOW_CASCADES = MassifObject.key("shadowCascades");
    /** Returns the shadow caster margin in tiles. */
    public static final MassifObject.Key<Long> SHADOW_CASTER_MARGIN = MassifObject.key("shadowCasterMargin");
    /** Returns the shading color of areas that face away from the light source. */
    public static final MassifObject.Key<Integer> SHADOW_COLOR = MassifObject.key("shadowColor");
    /** Returns the shadow distance. */
    public static final MassifObject.Key<Double> SHADOW_DISTANCE = MassifObject.key("shadowDistance");
    /** Returns the shadow map resolution. */
    public static final MassifObject.Key<Long> SHADOW_MAP_SIZE = MassifObject.key("shadowMapSize");
    /** Returns the shadow normal offset. */
    public static final MassifObject.Key<Double> SHADOW_NORMAL_OFFSET = MassifObject.key("shadowNormalOffset");
    /** Returns the shadow softness. */
    public static final MassifObject.Key<Double> SHADOW_SOFTNESS = MassifObject.key("shadowSoftness");
    /** Returns the shadow strength. */
    public static final MassifObject.Key<Double> SHADOW_STRENGTH = MassifObject.key("shadowStrength");
    /** Returns the state of internal debug message logging. */
    public static final MassifObject.Key<Boolean> SHOW_DEBUG = MassifObject.key("showDebug");
    /** Returns the state of error logging. */
    public static final MassifObject.Key<Boolean> SHOW_ERROR = MassifObject.key("showError");
    /** Returns the state of general info logging. */
    public static final MassifObject.Key<Boolean> SHOW_INFO = MassifObject.key("showInfo");
    /** Returns the state of warning logging. */
    public static final MassifObject.Key<Boolean> SHOW_WARN = MassifObject.key("showWarn");
    /** Returns the color for sides of the 3d polygon. */
    public static final MassifObject.Key<Integer> SIDE_COLOR = MassifObject.key("sideColor");
    /** Returns the simplification tolerance in tile pixels. */
    public static final MassifObject.Key<Double> SIMPLIFY_TOLERANCE = MassifObject.key("simplifyTolerance");
    /** Returns whether single-pass segmented rendering is enabled (Milestone 6, optional). */
    public static final MassifObject.Key<Boolean> SINGLE_PASS_RENDERING_ENABLED = MassifObject.key("singlePassRenderingEnabled");
    /** Returns the size of the data */
    public static final MassifObject.Key<String> SIZE = MassifObject.key("size");
    /** Returns the size-related animation type. */
    public static final MassifObject.Key<String> SIZE_ANIMATION_TYPE = MassifObject.key("sizeAnimationType");
    /** Returns the sky color. */
    public static final MassifObject.Key<Integer> SKY_COLOR = MassifObject.key("skyColor");
    /** Returns the sky options. May be null. */
    public static final MassifObject.Key<MassifObject> SKY_OPTIONS = MassifObject.key("skyOptions");
    /** Returns the edge softness of a disc sprite. */
    public static final MassifObject.Key<Double> SOFTNESS = MassifObject.key("softness");
    /** Returns wether result features are sorted by distance */
    public static final MassifObject.Key<Boolean> SORT_BY_DISTANCE = MassifObject.key("sortByDistance");
    /** Returns the current source projection. If source projection is set, all geometry coordinates will be converted from given coordinate system to WGS84. */
    public static final MassifObject.Key<MassifObject> SOURCE_PROJECTION = MassifObject.key("sourceProjection");
    /** Returns the color of the sky at the zenith, beyond the atmosphere. */
    public static final MassifObject.Key<Integer> SPACE_COLOR = MassifObject.key("spaceColor");
    /** Returns how brightly stars are drawn beyond the atmosphere. */
    public static final MassifObject.Key<Double> STAR_INTENSITY = MassifObject.key("starIntensity");
    /** Returns the street name included in the address. */
    public static final MassifObject.Key<String> STREET = MassifObject.key("street");
    /** Returns the name of street. */
    public static final MassifObject.Key<String> STREET_NAME = MassifObject.key("streetName");
    /** Returns the stretching factor of the line. */
    public static final MassifObject.Key<Double> STRETCH_FACTOR = MassifObject.key("stretchFactor");
    /** Returns the string value of this variant. */
    public static final MassifObject.Key<String> STRING = MassifObject.key("string");
    /** Returns the encoded tile mask value. This should not be displayed to the user. */
    public static final MassifObject.Key<String> STRING_VALUE = MassifObject.key("stringValue");
    /** Returns the color of the stroke surrounding the button. */
    public static final MassifObject.Key<Integer> STROKE_COLOR = MassifObject.key("strokeColor");
    /** Returns the width of the stroke surrounding the button. */
    public static final MassifObject.Key<String> STROKE_WIDTH = MassifObject.key("strokeWidth");
    /** Returns the style of this balloon popup. */
    public static final MassifObject.Key<MassifObject> STYLE = MassifObject.key("style");
    /** Returns the asset name defining the current style name. */
    public static final MassifObject.Key<String> STYLE_ASSET_NAME = MassifObject.key("styleAssetName");
    /** Returns the ordered list of style layer names as declared by the style (the project JSON "layers" array, or the Layer elements of a Mapnik XML style). This defines both the draw order and which layers exist. CompositeVectorTileLayer uses it to place external data sources in the layer order: a source whose name is not in this list has no slot in the style and is not drawn, so this is the way to check a style before wiring sources into it. */
    public static final MassifObject.Key<String> STYLE_LAYER_NAMES = MassifObject.key("styleLayerNames");
    /** Returns the current style name. */
    public static final MassifObject.Key<String> STYLE_NAME = MassifObject.key("styleName");
    /** Returns the list of all available style parameters. */
    public static final MassifObject.Key<String> STYLE_PARAMETERS = MassifObject.key("styleParameters");
    /** Returns the current style set used by the decoder. */
    public static final MassifObject.Key<MassifObject> STYLE_SET = MassifObject.key("styleSet");
    /** Returns the subdomains for {s} tag. The default is ["a", "b", "c", "d"]. */
    public static final MassifObject.Key<String> SUBDOMAINS = MassifObject.key("subdomains");
    /** Returns the sun altitude in degrees above the horizon. */
    public static final MassifObject.Key<Double> SUN_ALTITUDE = MassifObject.key("sunAltitude");
    /** Returns the sun azimuth in degrees. */
    public static final MassifObject.Key<Double> SUN_AZIMUTH = MassifObject.key("sunAzimuth");
    /** Returns the sun (directional light) color. */
    public static final MassifObject.Key<Integer> SUN_COLOR = MassifObject.key("sunColor");
    /** Returns whether the built-in shader draws a sun disc. */
    public static final MassifObject.Key<Boolean> SUN_DISC_ENABLED = MassifObject.key("sunDiscEnabled");
    /** Returns the sun light intensity. */
    public static final MassifObject.Key<Double> SUN_INTENSITY = MassifObject.key("sunIntensity");
    /** Returns the custom terrain surface fragment shader source, or an empty string if no shaded surface is drawn. */
    public static final MassifObject.Key<String> SURFACE_SHADER_SOURCE = MassifObject.key("surfaceShaderSource");
    /** Returns whether the switch is holding the ground flat while the tiles 3D needs load. */
    public static final MassifObject.Key<Boolean> SWITCHING = MassifObject.key("switching");
    /** Returns the state of the synchronized refresh flag. */
    public static final MassifObject.Key<Boolean> SYNCHRONIZED_REFRESH = MassifObject.key("synchronizedRefresh");
    /** Returns the user-defined tag associated with the button. */
    public static final MassifObject.Key<String> TAG = MassifObject.key("tag");
    /** Returns the current target projection. If target projection is set, all geometry coordinates will be converted from WGS84 to target projection coordinate system. */
    public static final MassifObject.Key<MassifObject> TARGET_PROJECTION = MassifObject.key("targetProjection");
    /** Returns true if the effect needs the terrain depth pre-pass (uTerrainDepthTex). */
    public static final MassifObject.Key<Boolean> TERRAIN_DEPTH_REQUIRED = MassifObject.key("terrainDepthRequired");
    /** Returns whether the sun lights the 3D terrain surface. */
    public static final MassifObject.Key<Boolean> TERRAIN_LIGHTING_ENABLED = MassifObject.key("terrainLightingEnabled");
    /** Returns the terrain options whose elevation manager the label stubs read. */
    public static final MassifObject.Key<MassifObject> TERRAIN_OPTIONS = MassifObject.key("terrainOptions");
    /** Returns whether the layer may shade the 3D terrain's own elevation texture instead of loading a DEM tile set of its own. */
    public static final MassifObject.Key<Boolean> TERRAIN_PAINT_ENABLED = MassifObject.key("terrainPaintEnabled");
    /** Returns whether the terrain paint shades from the elevation source's own maximum zoom. */
    public static final MassifObject.Key<Boolean> TERRAIN_PAINT_FULL_DETAIL_ENABLED = MassifObject.key("terrainPaintFullDetailEnabled");
    /** Returns the text of this button. */
    public static final MassifObject.Key<String> TEXT = MassifObject.key("text");
    /** Returns the color of the text. */
    public static final MassifObject.Key<Integer> TEXT_COLOR = MassifObject.key("textColor");
    /** Returns the text field variable to use. */
    public static final MassifObject.Key<String> TEXT_FIELD = MassifObject.key("textField");
    /** Returns the name of the text font. */
    public static final MassifObject.Key<String> TEXT_FONT_NAME = MassifObject.key("textFontName");
    /** Returns the size of the text font. */
    public static final MassifObject.Key<Long> TEXT_FONT_SIZE = MassifObject.key("textFontSize");
    /** Returns the margins of the text. */
    public static final MassifObject.Key<String> TEXT_MARGINS = MassifObject.key("textMargins");
    /** Returns the opacity a label keeps while its anchor is behind 3D content. */
    public static final MassifObject.Key<Double> TEXT_OCCLUSION_OPACITY = MassifObject.key("textOcclusionOpacity");
    /** Returns the tile texture cache capacity. */
    public static final MassifObject.Key<Long> TEXTURE_CACHE_CAPACITY = MassifObject.key("textureCacheCapacity");
    /** Returns the tile the event concerns, which is only meaningful for a failure. */
    public static final MassifObject.Key<String> TILE = MassifObject.key("tile");
    /** Returns the current relative tile blending speed. */
    public static final MassifObject.Key<Double> TILE_BLENDING_SPEED = MassifObject.key("tileBlendingSpeed");
    /** Returns the tile cache capacity. */
    public static final MassifObject.Key<Long> TILE_CACHE_CAPACITY = MassifObject.key("tileCacheCapacity");
    /** Returns the number of tiles the download will fetch. */
    public static final MassifObject.Key<Long> TILE_COUNT = MassifObject.key("tileCount");
    /** Returns the tile decoder assigned to this layer. */
    public static final MassifObject.Key<MassifObject> TILE_DECODER = MassifObject.key("tileDecoder");
    /** Returns the tile size used for drawing map tiles. */
    public static final MassifObject.Key<Long> TILE_DRAW_SIZE = MassifObject.key("tileDrawSize");
    /** Returns whether cross-LOD tile edge stitching is enabled. */
    public static final MassifObject.Key<Boolean> TILE_EDGE_STITCHING_ENABLED = MassifObject.key("tileEdgeStitchingEnabled");
    /** Returns the current tile filter mode. */
    public static final MassifObject.Key<String> TILE_FILTER_MODE = MassifObject.key("tileFilterMode");
    /** Returns the binary format the tiles are decoded as. */
    public static final MassifObject.Key<String> TILE_FORMAT = MassifObject.key("tileFormat");
    /** Returns the internal tile id of this map tile. */
    public static final MassifObject.Key<Long> TILE_ID = MassifObject.key("tileId");
    /** Returns the factor on the screen size a tile may cover before it is refined. */
    public static final MassifObject.Key<Double> TILE_LODFACTOR = MassifObject.key("tileLODFactor");
    /** Returns how many zoom levels a tile may lose to foreshortening. */
    public static final MassifObject.Key<Double> TILE_LODFORESHORTENING_LIMIT = MassifObject.key("tileLODForeshorteningLimit");
    /** Returns the tile load listener. */
    public static final MassifObject.Key<MassifObject> TILE_LOAD_LISTENER = MassifObject.key("tileLoadListener");
    /** Returns the encoded tile mask of the package. This is available for map packages but not for routing packages. This should not be displayed to the user. */
    public static final MassifObject.Key<MassifObject> TILE_MASK = MassifObject.key("tileMask");
    /** Returns the current tile substitution policy. */
    public static final MassifObject.Key<String> TILE_SUBSTITUTION_POLICY = MassifObject.key("tileSubstitutionPolicy");
    /** Returns the number of threads used by the tile task pool. */
    public static final MassifObject.Key<Long> TILE_THREAD_POOL_SIZE = MassifObject.key("tileThreadPoolSize");
    /** Returns the tilt angle in degrees. 0 means looking directly at the horizon, 90 means looking directly down. */
    public static final MassifObject.Key<Double> TILT = MassifObject.key("tilt");
    /** Returns true if the interaction included a tilt action. */
    public static final MassifObject.Key<Boolean> TILT_ACTION = MassifObject.key("tiltAction");
    /** Returns true if tilting gesture direction is reversed (and same as with Google Maps). */
    public static final MassifObject.Key<Boolean> TILT_GESTURE_REVERSED = MassifObject.key("tiltGestureReversed");
    /** Returns the tilt range constraint. */
    public static final MassifObject.Key<String> TILT_RANGE = MassifObject.key("tiltRange");
    /** Returns the time approximate duration of the instruction. */
    public static final MassifObject.Key<Double> TIME = MassifObject.key("time");
    /** Returns the current timeout value. */
    public static final MassifObject.Key<Long> TIMEOUT = MassifObject.key("timeout");
    /** Returns the title of this balloon popup. */
    public static final MassifObject.Key<String> TITLE = MassifObject.key("title");
    /** Returns the color of the title. */
    public static final MassifObject.Key<Integer> TITLE_COLOR = MassifObject.key("titleColor");
    /** Returns the title field variable to use. */
    public static final MassifObject.Key<String> TITLE_FIELD = MassifObject.key("titleField");
    /** Returns the name of the title font. */
    public static final MassifObject.Key<String> TITLE_FONT_NAME = MassifObject.key("titleFontName");
    /** Returns the size of the title font. */
    public static final MassifObject.Key<Long> TITLE_FONT_SIZE = MassifObject.key("titleFontSize");
    /** Returns the margins of the title. */
    public static final MassifObject.Key<String> TITLE_MARGINS = MassifObject.key("titleMargins");
    /** Returns the state of the title wrap parameter. */
    public static final MassifObject.Key<Boolean> TITLE_WRAP = MassifObject.key("titleWrap");
    public static final MassifObject.Key<Long> TOP = MassifObject.key("top");
    /** Returns the total distance of the path. */
    public static final MassifObject.Key<Double> TOTAL_DISTANCE = MassifObject.key("totalDistance");
    /** Returns the approximate total duration of the path. */
    public static final MassifObject.Key<Double> TOTAL_TIME = MassifObject.key("totalTime");
    /** Returns the height of the triangle at the bottom of the popup. */
    public static final MassifObject.Key<Long> TRIANGLE_HEIGHT = MassifObject.key("triangleHeight");
    /** Returns the width of the triangle at the bottom of the popup. */
    public static final MassifObject.Key<Long> TRIANGLE_WIDTH = MassifObject.key("triangleWidth");
    /** Returns the turn angle of the action. */
    public static final MassifObject.Key<Double> TURN_ANGLE = MassifObject.key("turnAngle");
    /** Returns the type of the matching point. */
    public static final MassifObject.Key<String> TYPE = MassifObject.key("type");
    /** Returns the conversion ratio between internal map units and screen density independent pixels (DP or DIP). This parameter is dependent on the zoom level, DPI and other screen parameters. */
    public static final MassifObject.Key<Double> UNIT_TO_DPCOEF = MassifObject.key("unitToDPCoef");
    /** Returns the conversion ratio between internal map units and screen pixels. This parameter is dependent on the zoom level and other screen parameters. */
    public static final MassifObject.Key<Double> UNIT_TO_PXCOEF = MassifObject.key("unitToPXCoef");
    /** Returns the layer task priority of this layer. */
    public static final MassifObject.Key<Long> UPDATE_PRIORITY = MassifObject.key("updatePriority");
    /** Returns the state of the user input flag. */
    public static final MassifObject.Key<Boolean> USER_INPUT = MassifObject.key("userInput");
    /** Returns the underlying variant. */
    public static final MassifObject.Key<String> VARIANT = MassifObject.key("variant");
    /** Returns the current edit event listener for the layer. */
    public static final MassifObject.Key<MassifObject> VECTOR_EDIT_EVENT_LISTENER = MassifObject.key("vectorEditEventListener");
    /** Returns the clicked vector element. */
    public static final MassifObject.Key<MassifObject> VECTOR_ELEMENT = MassifObject.key("vectorElement");
    /** Returns the drag mode. */
    public static final MassifObject.Key<String> VECTOR_ELEMENT_DRAG_MODE = MassifObject.key("vectorElementDragMode");
    /** Returns the vector element event listener. */
    public static final MassifObject.Key<MassifObject> VECTOR_ELEMENT_EVENT_LISTENER = MassifObject.key("vectorElementEventListener");
    /** Returns the vector tile event listener. */
    public static final MassifObject.Key<MassifObject> VECTOR_TILE_EVENT_LISTENER = MassifObject.key("vectorTileEventListener");
    /** Returns the package version. This should not be displayed to the user. */
    public static final MassifObject.Key<Long> VERSION = MassifObject.key("version");
    /** Returns the vertical offset of the billboard. */
    public static final MassifObject.Key<Double> VERTICAL_OFFSET = MassifObject.key("verticalOffset");
    /** Returns the altitude the fog has fully faded out at. */
    public static final MassifObject.Key<Double> VERTICAL_RANGE_END = MassifObject.key("verticalRangeEnd");
    /** Returns the altitude the fog starts fading out at. */
    public static final MassifObject.Key<Double> VERTICAL_RANGE_START = MassifObject.key("verticalRangeStart");
    /** Returns the minimum view distance, in meters. */
    public static final MassifObject.Key<Double> VIEW_DISTANCE = MassifObject.key("viewDistance");
    /** Returns the factor applied to the view distance. */
    public static final MassifObject.Key<Double> VIEW_DISTANCE_FACTOR = MassifObject.key("viewDistanceFactor");
    /** Returns a view state. */
    public static final MassifObject.Key<String> VIEW_STATE = MassifObject.key("viewState");
    /** Returns the visibility of the object. */
    public static final MassifObject.Key<Boolean> VISIBLE = MassifObject.key("visible");
    /** Returns the visible zoom range of this layer. */
    public static final MassifObject.Key<String> VISIBLE_ZOOM_RANGE = MassifObject.key("visibleZoomRange");
    /** Returns the width of the bitmap. */
    public static final MassifObject.Key<String> WIDTH = MassifObject.key("width");
    /** Returns the x coordinate of this map position. */
    public static final MassifObject.Key<String> X = MassifObject.key("x");
    /** Returns the y coordinate of this map position. */
    public static final MassifObject.Key<String> Y = MassifObject.key("y");
    /** Returns the state of Z coordinate serialization. */
    public static final MassifObject.Key<String> Z = MassifObject.key("z");
    /** Returns the zoom level. The value returned is never negative, 0 means absolutely zoomed out and all other values describe some level of zoom. */
    public static final MassifObject.Key<String> ZOOM = MassifObject.key("zoom");
    /** Returns the distance between the focus and the camera position, when the zoom level is set to 0. This parameter depends on the screen size, DPI, tile draw size and field of view settings. */
    public static final MassifObject.Key<Double> ZOOM0_DISTANCE = MassifObject.key("zoom0Distance");
    /** Returns true if the interaction included a zoom action. */
    public static final MassifObject.Key<Boolean> ZOOM_ACTION = MassifObject.key("zoomAction");
    /** Returns the state of zoom gestures. */
    public static final MassifObject.Key<Boolean> ZOOM_GESTURES = MassifObject.key("zoomGestures");
    /** Gets the current zoom level bias for this layer. */
    public static final MassifObject.Key<Double> ZOOM_LEVEL_BIAS = MassifObject.key("zoomLevelBias");
    /** Returns the zoom range constraint. */
    public static final MassifObject.Key<String> ZOOM_RANGE = MassifObject.key("zoomRange");

    // --- methods ---------------------------------------------------------

    public static final String METHOD_ADD = "add";
    public static final String METHOD_ADD_FEATURE = "addFeature";
    public static final String METHOD_ADD_LOCALE = "addLocale";
    public static final String METHOD_CALCULATE_ADDRESSES = "calculateAddresses";
    public static final String METHOD_CALCULATE_ROUTE = "calculateRoute";
    public static final String METHOD_CLEAR = "clear";
    public static final String METHOD_CLEAR_TILE_CACHES = "clearTileCaches";
    public static final String METHOD_CREATE_LAYER = "createLayer";
    public static final String METHOD_DELETE_LAYER = "deleteLayer";
    public static final String METHOD_FIND_FEATURES = "findFeatures";
    public static final String METHOD_FIT_BOUNDS = "fitBounds";
    public static final String METHOD_FLY_TO = "flyTo";
    public static final String METHOD_GET = "get";
    public static final String METHOD_GET_ELEVATION = "getElevation";
    public static final String METHOD_GET_ELEVATIONS = "getElevations";
    public static final String METHOD_GET_FEATURE = "getFeature";
    public static final String METHOD_GET_INSTRUCTION = "getInstruction";
    public static final String METHOD_GET_META_DATA_ELEMENT = "getMetaDataElement";
    public static final String METHOD_GET_POINTS = "getPoints";
    public static final String METHOD_GET_STYLE_PARAMETER = "getStyleParameter";
    public static final String METHOD_INSERT = "insert";
    public static final String METHOD_LOAD_TILE = "loadTile";
    public static final String METHOD_MAP_TO_SCREEN = "mapToScreen";
    public static final String METHOD_MATCH_ROUTE = "matchRoute";
    public static final String METHOD_MOVE_TO = "moveTo";
    public static final String METHOD_REFRESH = "refresh";
    public static final String METHOD_REMOVE = "remove";
    public static final String METHOD_REMOVE_FEATURE = "removeFeature";
    public static final String METHOD_SCREEN_TO_MAP = "screenToMap";
    public static final String METHOD_SET = "set";
    public static final String METHOD_SET_CONFIGURATION_PARAMETER = "setConfigurationParameter";
    public static final String METHOD_SET_CUSTOM_PARAMETER = "setCustomParameter";
    public static final String METHOD_SET_LAYER_GEO_JSON = "setLayerGeoJSON";
    public static final String METHOD_SET_META_DATA_ELEMENT = "setMetaDataElement";
    public static final String METHOD_SET_STYLE_PARAMETER = "setStyleParameter";
    public static final String METHOD_SET_STYLE_PARAMETERS = "setStyleParameters";
    public static final String METHOD_START_DOWNLOAD_AREA = "startDownloadArea";
    public static final String METHOD_STOP_ALL_DOWNLOADS = "stopAllDownloads";
    public static final String METHOD_STOP_FLIGHT = "stopFlight";
    public static final String METHOD_UPDATE_FEATURE = "updateFeature";

    // --- events ----------------------------------------------------------

    public static final String EVENT_DOWNLOAD_COMPLETED = "download.completed";
    public static final String EVENT_DOWNLOAD_FAILED = "download.failed";
    public static final String EVENT_DOWNLOAD_PROGRESS = "download.progress";
    public static final String EVENT_DOWNLOAD_STARTED = "download.started";
    public static final String EVENT_MAP_CLICKED = "map.clicked";
    public static final String EVENT_MAP_IDLE = "map.idle";
    public static final String EVENT_MAP_INTERACTION = "map.interaction";
    public static final String EVENT_MAP_MOVED = "map.moved";
    public static final String EVENT_MAP_STABLE = "map.stable";
    public static final String EVENT_VECTORELEMENT_CLICKED = "vectorelement.clicked";
    public static final String EVENT_VECTORTILE_CLICKED = "vectortile.clicked";

    // --- kinds and spec types --------------------------------------------

    public static final String KIND_ASSETS = "assets";
    public static final String KIND_ELEMENT = "element";
    public static final String KIND_ELEMENTSTYLE = "elementstyle";
    public static final String KIND_FEATURE = "feature";
    public static final String KIND_GEOCODING = "geocoding";
    public static final String KIND_GEOMETRY = "geometry";
    public static final String KIND_LAYER = "layer";
    public static final String KIND_OPTIONS = "options";
    public static final String KIND_ROUTING = "routing";
    public static final String KIND_SEARCH = "search";
    public static final String KIND_SOURCE = "source";
    public static final String KIND_STYLE = "style";
    public static final String KIND_STYLESET = "styleset";
    public static final String TYPE_ASSETS_BUNDLE = "bundle";
    public static final String TYPE_ASSETS_DIR = "dir";
    public static final String TYPE_ASSETS_ZIP = "zip";
    public static final String TYPE_ELEMENT_BALLOON = "balloon";
    public static final String TYPE_ELEMENT_LINE = "line";
    public static final String TYPE_ELEMENT_MARKER = "marker";
    public static final String TYPE_ELEMENT_POINT = "point";
    public static final String TYPE_ELEMENT_POLYGON = "polygon";
    public static final String TYPE_ELEMENT_TEXT = "text";
    public static final String TYPE_ELEMENTSTYLE_BALLOON = "balloon";
    public static final String TYPE_ELEMENTSTYLE_LINE = "line";
    public static final String TYPE_ELEMENTSTYLE_MARKER = "marker";
    public static final String TYPE_ELEMENTSTYLE_POINT = "point";
    public static final String TYPE_ELEMENTSTYLE_POLYGON = "polygon";
    public static final String TYPE_ELEMENTSTYLE_TEXT = "text";
    public static final String TYPE_FEATURE_FEATURE = "feature";
    public static final String TYPE_GEOCODING_MULTI_OSM_OFFLINE = "multi-osm-offline";
    public static final String TYPE_GEOCODING_MULTI_OSM_OFFLINE_REVERSE = "multi-osm-offline-reverse";
    public static final String TYPE_GEOMETRY_LINE = "line";
    public static final String TYPE_GEOMETRY_POINT = "point";
    public static final String TYPE_GEOMETRY_POLYGON = "polygon";
    public static final String TYPE_LAYER_COMPOSITE_VECTOR = "composite-vector";
    public static final String TYPE_LAYER_ELEMENTS = "elements";
    public static final String TYPE_LAYER_HILLSHADE = "hillshade";
    public static final String TYPE_LAYER_RASTER = "raster";
    public static final String TYPE_LAYER_SOLID = "solid";
    public static final String TYPE_LAYER_VECTOR = "vector";
    public static final String TYPE_OPTIONS_FOG = "fog";
    public static final String TYPE_OPTIONS_LIGHT = "light";
    public static final String TYPE_OPTIONS_SKY = "sky";
    public static final String TYPE_OPTIONS_TERRAIN = "terrain";
    public static final String TYPE_ROUTING_MULTI_VALHALLA_OFFLINE = "multi-valhalla-offline";
    public static final String TYPE_ROUTING_VALHALLA_OFFLINE = "valhalla-offline";
    public static final String TYPE_ROUTING_VALHALLA_ONLINE = "valhalla-online";
    public static final String TYPE_SEARCH_REQUEST = "request";
    public static final String TYPE_SEARCH_VECTORTILE = "vectortile";
    public static final String TYPE_SOURCE_ASSETS = "assets";
    public static final String TYPE_SOURCE_COMBINED = "combined";
    public static final String TYPE_SOURCE_GEOJSON = "geojson";
    public static final String TYPE_SOURCE_HTTP = "http";
    public static final String TYPE_SOURCE_LOCAL = "local";
    public static final String TYPE_SOURCE_MAPTILER = "maptiler";
    public static final String TYPE_SOURCE_MBTILES = "mbtiles";
    public static final String TYPE_SOURCE_MEMORY_CACHE = "memory-cache";
    public static final String TYPE_SOURCE_MERGED_MBVT = "merged-mbvt";
    public static final String TYPE_SOURCE_MULTI = "multi";
    public static final String TYPE_SOURCE_ORDERED = "ordered";
    public static final String TYPE_SOURCE_PERSISTENT_CACHE = "persistent-cache";
    public static final String TYPE_STYLE_MBVT = "mbvt";
    public static final String TYPE_STYLESET_CARTOCSS = "cartocss";
    public static final String TYPE_STYLESET_PROJECT = "project";

    private ApiNames() {
    }
}
