/*
 * Copyright (c) 2016 CartoDB. All rights reserved.
 * Copying and using this code is allowed only according
 * to license terms, as given in https://cartodb.com/terms/
 */

#ifndef _MASSIF_API_METHODS_H_
#define _MASSIF_API_METHODS_H_

#include "api/Context.h"
#include "core/Variant.h"

#include <string>
#include <vector>

namespace massif {
    class MapBounds;
    class MapPos;
    class MapTile;
    class Projection;

    namespace api {

    /**
     * A call's arguments, as a positional JSON array. Each getter reports whether the argument
     * was there and of the right shape, so a thunk validates as it reads.
     */
    class CallArgs {
    public:
        CallArgs();

        /**
         * Parses a JSON array. An empty string is an empty argument list.
         * @return False when the JSON does not parse or is not an array.
         */
        static bool parse(const std::string& json, CallArgs& args);

        int count() const;

        bool getBool(int index, bool& value) const;
        bool getLong(int index, long long& value) const;
        bool getDouble(int index, double& value) const;
        bool getString(int index, std::string& value) const;
        /** Another object, by its handle; only reads the number - Context::getObject checks the class. */
        bool getHandle(int index, Handle& value) const;
        /**
         * A position, as [x, y] or [x, y, z], converted from the caller's projection (WGS84 unless
         * named) into the object's own. With toCaller, a thunk never sees a projection.
         */
        bool getPos(int index, MapPos& value) const;
        /** An array of positions, converted the same way. */
        bool getPositions(int index, std::vector<MapPos>& value) const;
        /** The same, but stopping at WGS84, for an SDK method that reprojects internally (else it converts twice). */
        bool getPosWgs84(int index, MapPos& value) const;
        bool getPositionsWgs84(int index, std::vector<MapPos>& value) const;
        /** Bounds, as a pair of positions, converted the same way. */
        bool getBounds(int index, MapBounds& value) const;
        /** The other direction: a position a thunk PRODUCES, ready to hand back. */
        MapPos toCaller(const MapPos& value) const;
        /** A tile, as [x, y, zoom]. */
        bool getTile(int index, MapTile& value) const;
        /** The raw argument, for a thunk that takes free-form JSON. */
        Variant get(int index) const;

        /** The caller's and the object's projections. Set by Context::call; either null leaves positions alone. */
        void setProjections(const std::shared_ptr<Projection>& caller,
                            const std::shared_ptr<Projection>& object);

    private:
        Variant _array;
        std::shared_ptr<Projection> _caller;
        std::shared_ptr<Projection> _object;
    };

    /**
     * One method's implementation. The context lets a thunk register an object result, addressed
     * by handle - how a binary blob crosses without being copied into a string.
     * @return RESULT_OK, or a code the caller reports. RESULT_BAD_SPEC for a bad argument list.
     */
    typedef Result (*MethodInvoke)(Context& context, void* obj, const CallArgs& args,
                                   PropertyValue& result);

    /** What a .i file declares: generated by scripts/gen-api-tables.py into MethodDecls.inc, checked against the registry. */
    struct MethodDecl {
        const char* cppClass;
        const char* name;
        int argCount;
    };

    struct EventDecl {
        const char* cppClass;
        const char* name;
    };

    // Methods an object can run by name; hand-registered, since each needs its argument decoding written anyway.
    namespace Methods {

        /** Reports any method the .i files declare and this build did not register, or vice versa. */
        void checkDeclarations();


        /** Adds a method to a class. Registering the same name twice replaces it (a plugin can specialise one). */
        void registerMethod(const char* cppClass, const char* name, MethodInvoke invoke);

        /**
         * Looks a method up, walking the class' base chain, so a method declared on
         * TileDataSource is callable on any source.
         * @return The implementation, or null.
         */
        MethodInvoke findMethod(const char* cppClass, const std::string& name);

        /** Registers the SDK's own methods. Called once, lazily, by the binding. */
        void registerBuiltins();

    }

} }

#endif
