/*
 * Copyright (c) 2016 CartoDB. All rights reserved.
 * Copying and using this code is allowed only according
 * to license terms, as given in https://cartodb.com/terms/
 */

#ifndef _MASSIF_API_SPECBUILDERS_H_
#define _MASSIF_API_SPECBUILDERS_H_

#include "api/Context.h"
#include "api/Spec.h"
#include "api/StructCodec.h"
#include "core/Variant.h"

#include <memory>
#include <set>
#include <string>

namespace massif { namespace api {

    /** Reads one spec key; an absent key returns the fallback - the caller decides what is required. */
    std::string stringAt(const Variant& spec, const char* key,
                         const std::string& fallback = std::string());
    int intAt(const Variant& spec, const char* key, int fallback);
    double floatAt(const Variant& spec, const char* key, double fallback);
    bool boolAt(const Variant& spec, const char* key, bool fallback);
    Variant variantAt(const Variant& spec, const char* key);

    /** A colour, in any spelling StructCodec::decodeColor takes. Unreadable falls back too. */
    Color colorAt(const Variant& spec, const char* key, int fallback);

    /** A by-value struct, through the same codec a property uses. Absent decodes to a default. */
    template <typename T>
    T structAt(const Variant& spec, const char* key) {
        T value;
        StructCodec::decode(variantAt(spec, key).toString(), value);
        return value;
    }

    /**
     * Resolves a reference that is either a registry id or an inline spec of another kind.
     * requiredClass is what the caller will cast to, so a wrong-class id is refused here.
     */
    Result childOf(Context& context, const Variant& spec, const char* key, const char* kind,
                   const char* requiredClass, std::shared_ptr<void>& out);

    /** One spec value as a property value: a scalar as itself, an array or object as JSON. */
    PropertyValue specValue(const Variant& value);

    /** Applies every unconsumed spec key as a property of this object, e.g. a style builder with no handle. */
    void applySpecProperties(Context& context, const ObjectRef& object, const Variant& spec,
                             std::set<std::string>& consumed);

    /**
     * Applies one key as a writable OBJECT property, its value a nested spec or a registry id.
     * @return false when the class has no writable object property of that name, so the caller
     *         falls through to its own value handling; true when it was this one's to apply.
     */
    bool applyObjectSpecProperty(Context& context, const ObjectRef& object, const Variant& spec,
                                 const std::string& key);

    /** The kinds the generated builders cover, nullptr-terminated; checked against the factories at startup. */
    extern const char* const SPEC_KINDS[];

    /** Which kind builds a class - see SPEC_KIND_OF_CLASS. Generated, nullptr-terminated. */
    struct SpecKindEntry {
        const char* cppClass;
        const char* kind;
    };
    extern const SpecKindEntry SPEC_KIND_OF_CLASS[];

    /** The kind whose factory builds `cppClass`, or null when nothing declares one. */
    const char* specKindOf(const char* cppClass);

    /**
     * Builds a class that declares a !spec in its .i, from its own constructor. Generated by
     * scripts/gen-api-tables.py.
     * @return RESULT_UNKNOWN_TYPE when no declared class of that kind has that type.
     */
    Result buildFromConstructor(Context& context, const std::string& kind, const Variant& spec,
                                ObjectRef& object, std::set<std::string>& consumed);

} }

#endif
