import { type ContourOptions, isContourLayer, rewriteContourFilter } from './contour.js';
import { Coverage } from './coverage.js';
import { Untranslatable, expandTokens, translateExpression } from './expression.js';
import { translateFilter, zoomPredicates } from './filter.js';
import { HANDLED_ELSEWHERE, followsLine, resolvePlacement } from './placement.js';
import { KNOWN_GAPS, LAYER_SYMBOLIZER, PROPERTY_MAP, VALUE_MAP } from './properties.js';
import { type SpriteSet, extractIcon } from './sprite.js';
import type { CartoProperty, Json, MapboxLayer, MapboxStyle, PropertyTable } from './types.js';

export interface ConvertResult {
    mss: string;
    project: string;
    coverage: Coverage;
}

/** MapBox text-anchor -> the CartoCSS (horizontal, vertical) alignment pair. */
const TEXT_ANCHOR: Record<string, readonly [string, string]> = {
    center: ['middle', 'middle'],
    left: ['left', 'middle'],
    right: ['right', 'middle'],
    top: ['middle', 'top'],
    bottom: ['middle', 'bottom'],
    'top-left': ['left', 'top'],
    'top-right': ['right', 'top'],
    'bottom-left': ['left', 'bottom'],
    'bottom-right': ['right', 'bottom'],
};

/** Attachment names are identifiers in the CartoCSS grammar. */
function attachmentName(layerId: string): string {
    const cleaned = layerId.replace(/[^A-Za-z0-9_]/g, '_');
    return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

export interface ConvertOptions {
    contour?: ContourOptions;
    /** Loaded sprite sheets and where to write the sliced icons. Icons are dropped without them. */
    sprites?: { sheets: SpriteSet; outDir: string };
    /** Resolve SDF sprites to plain bitmaps, for an SDK without marker-sdf. Loses size and halo. */
    flattenSdf?: boolean;
}

export function convert(style: MapboxStyle, table: PropertyTable, options: ConvertOptions = {}): ConvertResult {
    const coverage = new Coverage();
    const allowed = new Map<string, CartoProperty>(table.properties.map((p) => [p.cartocss, p]));
    const layers = style.layers ?? [];

    const mapBlock: string[] = [];
    const blocks: string[] = [];
    // Source-layer name -> the index of the first MapBox layer that draws it.
    const order = new Map<string, number>();

    layers.forEach((layer, index) => {
        if (layer.type === 'background') {
            mapBlock.push(...backgroundProperties(layer, coverage));
            return;
        }

        const symbolizer = LAYER_SYMBOLIZER[layer.type];
        if (!symbolizer) {
            coverage.drop(`layer type "${layer.type}"`, 'unsupported layer type', layer.id);
            return;
        }

        const sourceLayer = layer['source-layer'];
        if (!sourceLayer) {
            coverage.drop(`layer "${layer.id}"`, 'no source-layer', layer.id);
            return;
        }
        if (!order.has(sourceLayer)) order.set(sourceLayer, index);

        const declarations = layerDeclarations(layer, symbolizer, allowed, coverage, options);
        if (declarations.length === 0) return;

        let selector: string;
        try {
            // `selector = *predicate` with a skipper, so bracketed tests can abut the layer name -
            // but `when(...)` is a bare word and would glue onto it (`#aviationwhen(...)`).
            let filter = layer.filter ?? null;
            if (options.contour && isContourLayer(layer)) {
                filter = rewriteContourFilter(filter, options.contour, () =>
                    coverage.approximate(
                        `contour nth_line test rewritten as div >= ${options.contour!.majorDiv}: ` +
                        'only the major/minor split survives, the base interval is not in the style',
                    ));
            }
            const predicates = [
                ...zoomPredicates(layer.minzoom, layer.maxzoom),
                ...translateFilter(filter),
            ].map((p) => (p.startsWith('when(') ? ` ${p}` : p));
            selector = `#${sourceLayer}${predicates.join('')}::${attachmentName(layer.id)}`;
        } catch (error) {
            const why = error instanceof Untranslatable ? error.what : String(error);
            coverage.drop(`filter on "${layer.id}"`, `untranslatable filter: ${why}`, layer.id);
            return;
        }

        blocks.push(`${selector} {\n${declarations.map((d) => `  ${d}`).join('\n')}\n}`);
    });

    reportInterleaving(layers, order, coverage);

    const header = [
        '/* Generated by massif-style mapbox2css. Do not edit by hand:',
        '   re-run the converter against the source style instead. */',
    ];
    if (style.name) header.push(`/* Source style: ${style.name} */`);

    const mss = [
        ...header,
        '',
        ...(mapBlock.length > 0 ? [`Map {\n${mapBlock.map((d) => `  ${d}`).join('\n')}\n}`, ''] : []),
        ...blocks,
        '',
    ].join('\n');

    // loadMapProject REVERSES this array (layerNames.insert(begin)), and MapBox layers run
    // bottom-to-top, so the project list is the draw order reversed.
    const projectLayers = [...order.entries()].sort((a, b) => a[1] - b[1]).map(([name]) => name).reverse();
    const project = JSON.stringify({ styles: ['style.mss'], layers: projectLayers }, null, 2) + '\n';

    return { mss, project, coverage };
}

function backgroundProperties(layer: MapboxLayer, coverage: Coverage): string[] {
    const out: string[] = [];
    for (const [name, value] of Object.entries(layer.paint ?? {})) {
        const target = PROPERTY_MAP.background[name];
        if (!target) {
            coverage.drop(name, KNOWN_GAPS[name] ?? 'not mapped', layer.id);
            continue;
        }
        const translated = tryTranslate(value, name, layer.id, coverage);
        if (translated !== null) {
            out.push(`${target}: ${translated};`);
            coverage.emit(target);
        }
    }
    return out;
}

function layerDeclarations(
    layer: MapboxLayer,
    symbolizer: string,
    allowed: Map<string, CartoProperty>,
    coverage: Coverage,
    options: ConvertOptions,
): string[] {
    const table = PROPERTY_MAP[layer.type] ?? {};
    const out: string[] = [];
    // A symbol layer's icon is a SECOND symbolizer in the same rule, so marker-* declarations sit
    // beside the text-* ones rather than replacing them.
    const iconDeclarations = layer.type === 'symbol' ? markerDeclarations(layer, coverage, options) : [];

    if (symbolizer === 'text') {
        out.push(`text-placement: '${resolvePlacement(layer, 'text')}';`);
        coverage.emit('text-placement');
    }

    for (const [name, value] of Object.entries({ ...layer.layout, ...layer.paint })) {
        if (name === 'visibility') {
            if (value === 'none') return []; // the whole layer is off
            continue;
        }
        if (HANDLED_ELSEWHERE.has(name)) continue;
        // text-field may be the legacy "{field}" token form rather than an expression.
        if (name === 'text-field' && typeof value === 'string' && value.includes('{')) {
            out.push(`text-name: ${expandTokens(value)};`);
            coverage.emit('text-name');
            continue;
        }

        // MapBox names one anchor; CartoCSS splits it into a horizontal and a vertical alignment.
        // The senses agree - see the default derivation in TextSymbolizer.cpp, where a text pushed
        // right (dx > 0) defaults to alignment 'left', i.e. the edge nearest the anchor.
        if (name === 'text-anchor' && typeof value === 'string') {
            const anchor = TEXT_ANCHOR[value];
            if (!anchor) {
                coverage.drop(name, `unknown anchor "${value}"`, layer.id);
                continue;
            }
            out.push(`text-horizontal-alignment: '${anchor[0]}';`, `text-vertical-alignment: '${anchor[1]}';`);
            coverage.emit('text-horizontal-alignment');
            coverage.emit('text-vertical-alignment');
            continue;
        }

        // Everything MapBox measures in ems of the text size. CartoCSS takes pixels, so each one
        // is multiplied by text-size - the expression form included, or a zoom-driven size would
        // silently pin the value to one zoom.
        if (name === 'text-offset' && Array.isArray(value) && value.length === 2) {
            const dx = ems(value[0], layer, coverage, name);
            const dy = ems(value[1], layer, coverage, name);
            if (dx === null || dy === null) continue;
            out.push(`text-dx: ${dx};`, `text-dy: ${dy};`);
            coverage.emit('text-dx');
            coverage.emit('text-dy');
            continue;
        }

        // text-max-width is 10 ems by default; taken as pixels it wrapped every name onto one word
        // per line. A line-placed label is laid out along the line and MapLibre never wraps it.
        if (name === 'text-max-width') {
            if (followsLine(layer)) {
                out.push('text-wrap-width: 0;');
                coverage.emit('text-wrap-width');
                continue;
            }
            const width = ems(value, layer, coverage, name);
            if (width === null) continue;
            out.push(`text-wrap-width: ${width};`);
            coverage.emit('text-wrap-width');
            continue;
        }

        // The modern spelling of *-allow-overlap. 'cooperative' has no equivalent and is the
        // conservative 'never' here.
        if (name === 'text-overlap' || name === 'icon-overlap') {
            const target = name === 'text-overlap' ? 'text-allow-overlap' : 'marker-allow-overlap';
            out.push(`${target}: ${value === 'always'};`);
            coverage.emit(target);
            continue;
        }

        // MapBox places the LOWEST sort key first; CartoCSS's culler takes the highest priority.
        if (name === 'symbol-sort-key') {
            const translated = tryTranslate(value, name, layer.id, coverage);
            if (translated === null) continue;
            out.push(`text-placement-priority: (0 - ${translated});`);
            coverage.emit('text-placement-priority');
            continue;
        }

        if (name === 'text-letter-spacing') {
            const spacing = ems(value, layer, coverage, name);
            if (spacing === null) continue;
            out.push(`text-character-spacing: ${spacing};`);
            coverage.emit('text-character-spacing');
            continue;
        }

        // text-line-height is a TOTAL line height in ems; text-line-spacing is what is added on top
        // of the font's own, which already is MapBox's 1.2 default.
        if (name === 'text-line-height' && typeof value === 'number') {
            const spacing = ems(value - 1.2, layer, coverage, name);
            if (spacing === null) continue;
            out.push(`text-line-spacing: ${spacing};`);
            coverage.emit('text-line-spacing');
            continue;
        }

        // MapBox dash lengths are multiples of the line width; CartoCSS's are pixels.
        if (name === 'line-dasharray' && Array.isArray(value) && value.every((v) => typeof v === 'number')) {
            const width = layer.paint?.['line-width'];
            const scale = typeof width === 'number' ? width : 1;
            if (typeof width !== 'number') {
                coverage.approximate('line-dasharray scaled by width 1: line-width is not constant');
            }
            out.push(`line-dasharray: ${(value as number[]).map((v) => v * scale).join(',')};`);
            coverage.emit('line-dasharray');
            continue;
        }

        // A fill's outline is a second symbolizer on the same rule, not a polygon property.
        if (name === 'fill-outline-color') {
            const translated = tryTranslate(value, name, layer.id, coverage);
            if (translated !== null) {
                out.push(`line-color: ${translated};`, 'line-width: 1;');
                coverage.emit('line-color');
            }
            continue;
        }

        const target = table[name];
        if (!target) {
            coverage.drop(name, KNOWN_GAPS[name] ?? 'not mapped', layer.id);
            continue;
        }
        if (!allowed.has(target)) {
            // The table above claims a property the decoder does not bind - a bug here, not in the
            // source style. Say so rather than blaming the style.
            coverage.drop(name, `maps to "${target}", absent from the generated allowlist`, layer.id);
            continue;
        }

        const translated = tryTranslate(value, name, layer.id, coverage);
        if (translated === null) continue;
        out.push(`${target}: ${remapValue(target, translated)};`);
        coverage.emit(target);
    }

    // MapBox wraps at 10 ems whether or not the layer says so; CartoCSS's wrap-width defaults to 0,
    // which is no wrapping at all - so an unstated max-width has to be written out.
    if (symbolizer === 'text' && !followsLine(layer) && !out.some((d) => d.startsWith('text-wrap-width:'))) {
        const width = ems(DEFAULT_TEXT_MAX_WIDTH, layer, coverage, 'text-max-width');
        if (width !== null) {
            out.push(`text-wrap-width: ${width};`);
            coverage.emit('text-wrap-width');
        }
    }

    // text-name is what makes a text symbolizer exist at all; without it every other text property
    // is dropped with the rule - but an icon-only layer still has its marker to draw.
    if (symbolizer === 'text' && !out.some((d) => d.startsWith('text-name:'))) {
        if (out.length > 0 && iconDeclarations.length === 0) {
            coverage.drop(`layer "${layer.id}"`, 'symbol layer with neither text-field nor a usable icon', layer.id);
        }
        return iconDeclarations;
    }
    return [...out, ...iconDeclarations];
}

/** MapBox's icon-* onto marker-*, once the sprite has been sliced into its own file. */
function markerDeclarations(layer: MapboxLayer, coverage: Coverage, options: ConvertOptions): string[] {
    const image = layer.layout?.['icon-image'];
    if (image === undefined) return [];
    if (typeof image !== 'string') {
        coverage.drop('icon-image', 'data-driven icon name', layer.id);
        return [];
    }
    if (!options.sprites) {
        coverage.drop('icon-image', 'no sprite loaded (pass --sprite or let the style provide one)', layer.id);
        return [];
    }

    const icon = extractIcon(options.sprites.sheets, image, options.sprites.outDir, options.flattenSdf);
    if (!icon) {
        coverage.drop('icon-image', `"${image}" is not in the sprite`, layer.id);
        return [];
    }

    const out = [
        `marker-file: url('${icon.file}');`,
        `marker-placement: '${resolvePlacement(layer, 'icon')}';`,
    ];
    coverage.emit('marker-file');
    coverage.emit('marker-placement');

    const sdf = icon.sdf && !options.flattenSdf;
    if (sdf) {
        out.push('marker-sdf: true;');
        coverage.emit('marker-sdf');
    }

    // icon-size scales the sprite's own size. A distance field is SCALED rather than resampled, so
    // a zoom-driven size survives; a flattened bitmap can only take a constant.
    const size = layer.layout?.['icon-size'];
    const sizeExpr = size === undefined
        ? String(round(icon.width))
        : sdf
            ? scaledSize(size, icon.width, name('icon-size', layer, coverage))
            : typeof size === 'number' ? String(round(icon.width * size)) : null;
    if (sizeExpr === null) {
        coverage.drop('icon-size', 'a flattened bitmap cannot take a zoom-driven size (drop --sdf-flatten)', layer.id);
        out.push(`marker-width: ${round(icon.width)};`);
    } else {
        out.push(`marker-width: ${sizeExpr};`);
    }
    coverage.emit('marker-width');

    // An SDF icon carries no colour of its own, so marker-color IS the icon colour and MapBox
    // defaults it to black. A plain sprite already has its colours and must not be tinted.
    if (icon.sdf) {
        emitTranslated(out, coverage, layer, 'icon-color', 'marker-color', '#000000', !sdf);
    }
    emitTranslated(out, coverage, layer, 'icon-opacity', 'marker-opacity', undefined, !sdf);

    // Halos are grown from the field, so they only exist in SDF mode.
    if (sdf) {
        emitTranslated(out, coverage, layer, 'icon-halo-color', 'marker-halo-fill', undefined, false);
        emitTranslated(out, coverage, layer, 'icon-halo-width', 'marker-halo-radius', undefined, false);
    }
    if (layer.layout?.['icon-allow-overlap'] === true) {
        out.push('marker-allow-overlap: true;');
        coverage.emit('marker-allow-overlap');
    }
    return out;
}

function round(value: number): number {
    return Math.round(value * 100) / 100;
}

/** MapBox defaults for a layer that never states them. */
const DEFAULT_TEXT_SIZE = 16;
const DEFAULT_TEXT_MAX_WIDTH = 10;

/** A value in ems of the layer's own text-size, as the pixels CartoCSS wants. */
function ems(value: Json, layer: MapboxLayer, coverage: Coverage, from: string): string | null {
    const size = layer.layout?.['text-size'] ?? DEFAULT_TEXT_SIZE;
    if (typeof value === 'number' && typeof size === 'number') return String(round(value * size));

    const valueExpr = typeof value === 'number' ? String(round(value)) : tryTranslate(value, from, layer.id, coverage);
    const sizeExpr = typeof size === 'number' ? String(size) : tryTranslate(size, 'text-size', layer.id, coverage);
    return valueExpr === null || sizeExpr === null ? null : `(${valueExpr} * ${sizeExpr})`;
}

/** icon-size is a multiplier on the sprite's own width. */
function scaledSize(size: Json, width: number, translated: string | null): string {
    if (typeof size === 'number') return String(round(width * size));
    return translated === null ? String(round(width)) : `(${translated} * ${round(width)})`;
}

/** Translates a MapBox paint/layout value onto a CartoCSS property, or reports why it could not. */
function emitTranslated(
    out: string[],
    coverage: Coverage,
    layer: MapboxLayer,
    from: string,
    to: string,
    fallback: string | undefined,
    constantOnly: boolean,
): void {
    const value = layer.paint?.[from] ?? layer.layout?.[from];
    if (value === undefined) {
        if (fallback !== undefined) {
            out.push(`${to}: ${fallback};`);
            coverage.emit(to);
        }
        return;
    }
    if (constantOnly && typeof value !== 'string' && typeof value !== 'number') {
        coverage.drop(from, `a flattened bitmap needs a constant ${from}`, layer.id);
        return;
    }
    const translated = name(from, layer, coverage);
    if (translated !== null) {
        out.push(`${to}: ${translated};`);
        coverage.emit(to);
    }
}

/** The translated form of a layer property, counting the drop itself when it has none. */
function name(property: string, layer: MapboxLayer, coverage: Coverage): string | null {
    const value = layer.paint?.[property] ?? layer.layout?.[property];
    if (value === undefined) return null;
    return tryTranslate(value, property, layer.id, coverage);
}

function tryTranslate(value: Json, name: string, layerId: string, coverage: Coverage): string | null {
    const notes: string[] = [];
    try {
        // text-font is a list; CartoCSS takes the first face name.
        const translated = Array.isArray(value) && name === 'text-font' && typeof value[0] === 'string'
            ? translateExpression(value[0], notes)
            : translateExpression(value, notes);
        notes.forEach((note) => coverage.approximate(note));
        return translated;
    } catch (error) {
        coverage.drop(name, describe(error), layerId);
        return null;
    }
}

function remapValue(target: string, translated: string): string {
    const map = VALUE_MAP[target];
    if (!map) return translated;
    const bare = translated.replace(/^'|'$/g, '');
    return map[bare] !== undefined ? `'${map[bare]}'` : translated;
}

/**
 * One entry in the project's `layers` pulls EVERY attachment of that name, so two MapBox layers on
 * different source-layers cannot be interleaved. Report each inversion rather than let the style
 * quietly draw in the wrong order.
 */
function reportInterleaving(layers: MapboxLayer[], order: Map<string, number>, coverage: Coverage): void {
    let inversions = 0;
    let previous = -1;
    for (const layer of layers) {
        const sourceLayer = layer['source-layer'];
        if (!sourceLayer || !order.has(sourceLayer)) continue;
        const position = order.get(sourceLayer)!;
        if (position < previous) inversions++;
        previous = position;
    }
    if (inversions > 0) {
        coverage.note(
            `${inversions} layer(s) draw out of order: a CartoCSS project entry pulls every ` +
            `attachment of its source-layer, so interleaved source-layers cannot be preserved.`,
        );
    }
}

function describe(error: unknown): string {
    return error instanceof Untranslatable ? `untranslatable: ${error.what}` : String(error);
}
