import { type ContourOptions, isContourLayer, rewriteContourFilter } from './contour.js';
import { Coverage } from './coverage.js';
import { Untranslatable, expandTokens, translateExpression } from './expression.js';
import { translateFilter, zoomPredicates } from './filter.js';
import { KNOWN_GAPS, LAYER_SYMBOLIZER, PROPERTY_MAP, VALUE_MAP } from './properties.js';
import { type SpriteSet, extractIcon } from './sprite.js';
import type { CartoProperty, Json, MapboxLayer, MapboxStyle, PropertyTable } from './types.js';

export interface ConvertResult {
    mss: string;
    project: string;
    coverage: Coverage;
}

/** MapBox text-anchor -> the CartoCSS (horizontal, vertical) alignment pair. */
const TEXT_ANCHOR: Record<string, readonly [string, string]> = {
    center: ['middle', 'middle'],
    left: ['left', 'middle'],
    right: ['right', 'middle'],
    top: ['middle', 'top'],
    bottom: ['middle', 'bottom'],
    'top-left': ['left', 'top'],
    'top-right': ['right', 'top'],
    'bottom-left': ['left', 'bottom'],
    'bottom-right': ['right', 'bottom'],
};

/** Attachment names are identifiers in the CartoCSS grammar. */
function attachmentName(layerId: string): string {
    const cleaned = layerId.replace(/[^A-Za-z0-9_]/g, '_');
    return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

export interface ConvertOptions {
    contour?: ContourOptions;
    /** Loaded sprite sheets and where to write the sliced icons. Icons are dropped without them. */
    sprites?: { sheets: SpriteSet; outDir: string };
}

export function convert(style: MapboxStyle, table: PropertyTable, options: ConvertOptions = {}): ConvertResult {
    const coverage = new Coverage();
    const allowed = new Map<string, CartoProperty>(table.properties.map((p) => [p.cartocss, p]));
    const layers = style.layers ?? [];

    const mapBlock: string[] = [];
    const blocks: string[] = [];
    // Source-layer name -> the index of the first MapBox layer that draws it.
    const order = new Map<string, number>();

    layers.forEach((layer, index) => {
        if (layer.type === 'background') {
            mapBlock.push(...backgroundProperties(layer, coverage));
            return;
        }

        const symbolizer = LAYER_SYMBOLIZER[layer.type];
        if (!symbolizer) {
            coverage.drop(`layer type "${layer.type}"`, 'unsupported layer type', layer.id);
            return;
        }

        const sourceLayer = layer['source-layer'];
        if (!sourceLayer) {
            coverage.drop(`layer "${layer.id}"`, 'no source-layer', layer.id);
            return;
        }
        if (!order.has(sourceLayer)) order.set(sourceLayer, index);

        const declarations = layerDeclarations(layer, symbolizer, allowed, coverage, options);
        if (declarations.length === 0) return;

        let selector: string;
        try {
            // `selector = *predicate` with a skipper, so bracketed tests can abut the layer name -
            // but `when(...)` is a bare word and would glue onto it (`#aviationwhen(...)`).
            let filter = layer.filter ?? null;
            if (options.contour && isContourLayer(layer)) {
                filter = rewriteContourFilter(filter, options.contour, () =>
                    coverage.approximate(
                        `contour nth_line test rewritten as div >= ${options.contour!.majorDiv}: ` +
                        'only the major/minor split survives, the base interval is not in the style',
                    ));
            }
            const predicates = [
                ...zoomPredicates(layer.minzoom, layer.maxzoom),
                ...translateFilter(filter),
            ].map((p) => (p.startsWith('when(') ? ` ${p}` : p));
            selector = `#${sourceLayer}${predicates.join('')}::${attachmentName(layer.id)}`;
        } catch (error) {
            const why = error instanceof Untranslatable ? error.what : String(error);
            coverage.drop(`filter on "${layer.id}"`, `untranslatable filter: ${why}`, layer.id);
            return;
        }

        blocks.push(`${selector} {\n${declarations.map((d) => `  ${d}`).join('\n')}\n}`);
    });

    reportInterleaving(layers, order, coverage);

    const header = [
        '/* Generated by massif-style mapbox2css. Do not edit by hand:',
        '   re-run the converter against the source style instead. */',
    ];
    if (style.name) header.push(`/* Source style: ${style.name} */`);

    const mss = [
        ...header,
        '',
        ...(mapBlock.length > 0 ? [`Map {\n${mapBlock.map((d) => `  ${d}`).join('\n')}\n}`, ''] : []),
        ...blocks,
        '',
    ].join('\n');

    // loadMapProject REVERSES this array (layerNames.insert(begin)), and MapBox layers run
    // bottom-to-top, so the project list is the draw order reversed.
    const projectLayers = [...order.entries()].sort((a, b) => a[1] - b[1]).map(([name]) => name).reverse();
    const project = JSON.stringify({ styles: ['style.mss'], layers: projectLayers }, null, 2) + '\n';

    return { mss, project, coverage };
}

function backgroundProperties(layer: MapboxLayer, coverage: Coverage): string[] {
    const out: string[] = [];
    for (const [name, value] of Object.entries(layer.paint ?? {})) {
        const target = PROPERTY_MAP.background[name];
        if (!target) {
            coverage.drop(name, KNOWN_GAPS[name] ?? 'not mapped', layer.id);
            continue;
        }
        const translated = tryTranslate(value, name, layer.id, coverage);
        if (translated !== null) {
            out.push(`${target}: ${translated};`);
            coverage.emit(target);
        }
    }
    return out;
}

function layerDeclarations(
    layer: MapboxLayer,
    symbolizer: string,
    allowed: Map<string, CartoProperty>,
    coverage: Coverage,
    options: ConvertOptions,
): string[] {
    const table = PROPERTY_MAP[layer.type] ?? {};
    const out: string[] = [];
    // A symbol layer's icon is a SECOND symbolizer in the same rule, so marker-* declarations sit
    // beside the text-* ones rather than replacing them.
    const iconDeclarations = layer.type === 'symbol' ? markerDeclarations(layer, coverage, options) : [];

    for (const [name, value] of Object.entries({ ...layer.layout, ...layer.paint })) {
        if (name === 'visibility') {
            if (value === 'none') return []; // the whole layer is off
            continue;
        }
        // text-field may be the legacy "{field}" token form rather than an expression.
        if (name === 'text-field' && typeof value === 'string' && value.includes('{')) {
            out.push(`text-name: ${expandTokens(value)};`);
            coverage.emit('text-name');
            continue;
        }

        // MapBox names one anchor; CartoCSS splits it into a horizontal and a vertical alignment.
        // The senses agree - see the default derivation in TextSymbolizer.cpp, where a text pushed
        // right (dx > 0) defaults to alignment 'left', i.e. the edge nearest the anchor.
        if (name === 'text-anchor' && typeof value === 'string') {
            const anchor = TEXT_ANCHOR[value];
            if (!anchor) {
                coverage.drop(name, `unknown anchor "${value}"`, layer.id);
                continue;
            }
            out.push(`text-horizontal-alignment: '${anchor[0]}';`, `text-vertical-alignment: '${anchor[1]}';`);
            coverage.emit('text-horizontal-alignment');
            coverage.emit('text-vertical-alignment');
            continue;
        }

        // MapBox offsets in ems of the text size; CartoCSS dx/dy are pixels. Only resolvable when
        // the size is a plain number, which is why this is not a VALUE_MAP entry.
        if (name === 'text-offset' && Array.isArray(value) && value.length === 2) {
            const size = layer.layout?.['text-size'];
            if (typeof size !== 'number' || typeof value[0] !== 'number' || typeof value[1] !== 'number') {
                coverage.drop(name, 'offset in ems needs a constant text-size to become pixels', layer.id);
                continue;
            }
            out.push(`text-dx: ${value[0] * size};`, `text-dy: ${value[1] * size};`);
            coverage.emit('text-dx');
            coverage.emit('text-dy');
            continue;
        }

        // MapBox dash lengths are multiples of the line width; CartoCSS's are pixels.
        if (name === 'line-dasharray' && Array.isArray(value) && value.every((v) => typeof v === 'number')) {
            const width = layer.paint?.['line-width'];
            const scale = typeof width === 'number' ? width : 1;
            if (typeof width !== 'number') {
                coverage.approximate('line-dasharray scaled by width 1: line-width is not constant');
            }
            out.push(`line-dasharray: ${(value as number[]).map((v) => v * scale).join(',')};`);
            coverage.emit('line-dasharray');
            continue;
        }

        // A fill's outline is a second symbolizer on the same rule, not a polygon property.
        if (name === 'fill-outline-color') {
            const translated = tryTranslate(value, name, layer.id, coverage);
            if (translated !== null) {
                out.push(`line-color: ${translated};`, 'line-width: 1;');
                coverage.emit('line-color');
            }
            continue;
        }

        const target = table[name];
        if (!target) {
            coverage.drop(name, KNOWN_GAPS[name] ?? 'not mapped', layer.id);
            continue;
        }
        if (!allowed.has(target)) {
            // The table above claims a property the decoder does not bind - a bug here, not in the
            // source style. Say so rather than blaming the style.
            coverage.drop(name, `maps to "${target}", absent from the generated allowlist`, layer.id);
            continue;
        }

        const translated = tryTranslate(value, name, layer.id, coverage);
        if (translated === null) continue;
        out.push(`${target}: ${remapValue(target, translated)};`);
        coverage.emit(target);
    }

    // text-name is what makes a text symbolizer exist at all; without it every other text property
    // is dropped with the rule - but an icon-only layer still has its marker to draw.
    if (symbolizer === 'text' && !out.some((d) => d.startsWith('text-name:'))) {
        if (out.length > 0 && iconDeclarations.length === 0) {
            coverage.drop(`layer "${layer.id}"`, 'symbol layer with neither text-field nor a usable icon', layer.id);
        }
        return iconDeclarations;
    }
    return [...out, ...iconDeclarations];
}

/** MapBox's icon-* onto marker-*, once the sprite has been sliced into its own file. */
function markerDeclarations(layer: MapboxLayer, coverage: Coverage, options: ConvertOptions): string[] {
    const image = layer.layout?.['icon-image'];
    if (image === undefined) return [];
    if (typeof image !== 'string') {
        coverage.drop('icon-image', 'data-driven icon name', layer.id);
        return [];
    }
    if (!options.sprites) {
        coverage.drop('icon-image', 'no sprite loaded (pass --sprite or let the style provide one)', layer.id);
        return [];
    }

    const icon = extractIcon(options.sprites.sheets, image, options.sprites.outDir);
    if (!icon) {
        coverage.drop('icon-image', `"${image}" is not in the sprite`, layer.id);
        return [];
    }

    const out = [`marker-file: url('${icon.file}');`];
    coverage.emit('marker-file');

    // icon-size scales the sprite's own size; CartoCSS wants the result in pixels.
    const size = layer.layout?.['icon-size'];
    const scale = typeof size === 'number' ? size : 1;
    if (size !== undefined && typeof size !== 'number') {
        coverage.drop('icon-size', 'non-constant icon-size cannot become marker-width', layer.id);
    }
    out.push(`marker-width: ${round(icon.width * scale)};`, `marker-height: ${round(icon.height * scale)};`);
    coverage.emit('marker-width');
    coverage.emit('marker-height');

    // An SDF sprite was rasterised to white, so marker-color IS the icon colour; MapBox defaults it
    // to black. A plain sprite already carries its colours and must not be tinted.
    if (icon.sdf) {
        const color = layer.paint?.['icon-color'];
        const translated = typeof color === 'string' || color === undefined
            ? (color ?? '#000000')
            : null;
        if (translated === null) {
            coverage.drop('icon-color', 'non-constant icon-color cannot tint a marker', layer.id);
        } else {
            out.push(`marker-color: ${translated};`);
            coverage.emit('marker-color');
        }
    }

    const opacity = layer.paint?.['icon-opacity'];
    if (typeof opacity === 'number') {
        out.push(`marker-opacity: ${opacity};`);
        coverage.emit('marker-opacity');
    }
    if (layer.layout?.['icon-allow-overlap'] === true) {
        out.push('marker-allow-overlap: true;');
        coverage.emit('marker-allow-overlap');
    }
    return out;
}

function round(value: number): number {
    return Math.round(value * 100) / 100;
}

function tryTranslate(value: Json, name: string, layerId: string, coverage: Coverage): string | null {
    const notes: string[] = [];
    try {
        // text-font is a list; CartoCSS takes the first face name.
        const translated = Array.isArray(value) && name === 'text-font' && typeof value[0] === 'string'
            ? translateExpression(value[0], notes)
            : translateExpression(value, notes);
        notes.forEach((note) => coverage.approximate(note));
        return translated;
    } catch (error) {
        coverage.drop(name, describe(error), layerId);
        return null;
    }
}

function remapValue(target: string, translated: string): string {
    const map = VALUE_MAP[target];
    if (!map) return translated;
    const bare = translated.replace(/^'|'$/g, '');
    return map[bare] !== undefined ? `'${map[bare]}'` : translated;
}

/**
 * One entry in the project's `layers` pulls EVERY attachment of that name, so two MapBox layers on
 * different source-layers cannot be interleaved. Report each inversion rather than let the style
 * quietly draw in the wrong order.
 */
function reportInterleaving(layers: MapboxLayer[], order: Map<string, number>, coverage: Coverage): void {
    let inversions = 0;
    let previous = -1;
    for (const layer of layers) {
        const sourceLayer = layer['source-layer'];
        if (!sourceLayer || !order.has(sourceLayer)) continue;
        const position = order.get(sourceLayer)!;
        if (position < previous) inversions++;
        previous = position;
    }
    if (inversions > 0) {
        coverage.note(
            `${inversions} layer(s) draw out of order: a CartoCSS project entry pulls every ` +
            `attachment of its source-layer, so interleaved source-layers cannot be preserved.`,
        );
    }
}

function describe(error: unknown): string {
    return error instanceof Untranslatable ? `untranslatable: ${error.what}` : String(error);
}
