import { Coverage } from './coverage.js';
import { Untranslatable, translateExpression } from './expression.js';
import { translateFilter, zoomPredicates } from './filter.js';
import { KNOWN_GAPS, LAYER_SYMBOLIZER, PROPERTY_MAP, VALUE_MAP } from './properties.js';
import type { CartoProperty, Json, MapboxLayer, MapboxStyle, PropertyTable } from './types.js';

export interface ConvertResult {
    mss: string;
    project: string;
    coverage: Coverage;
}

/** Attachment names are identifiers in the CartoCSS grammar. */
function attachmentName(layerId: string): string {
    const cleaned = layerId.replace(/[^A-Za-z0-9_]/g, '_');
    return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

export function convert(style: MapboxStyle, table: PropertyTable): ConvertResult {
    const coverage = new Coverage();
    const allowed = new Map<string, CartoProperty>(table.properties.map((p) => [p.cartocss, p]));
    const layers = style.layers ?? [];

    const mapBlock: string[] = [];
    const blocks: string[] = [];
    // Source-layer name -> the index of the first MapBox layer that draws it.
    const order = new Map<string, number>();

    layers.forEach((layer, index) => {
        if (layer.type === 'background') {
            mapBlock.push(...backgroundProperties(layer, coverage));
            return;
        }

        const symbolizer = LAYER_SYMBOLIZER[layer.type];
        if (!symbolizer) {
            coverage.drop(`layer type "${layer.type}"`, 'unsupported layer type', layer.id);
            return;
        }

        const sourceLayer = layer['source-layer'];
        if (!sourceLayer) {
            coverage.drop(`layer "${layer.id}"`, 'no source-layer', layer.id);
            return;
        }
        if (!order.has(sourceLayer)) order.set(sourceLayer, index);

        const declarations = layerDeclarations(layer, symbolizer, allowed, coverage);
        if (declarations.length === 0) return;

        let selector: string;
        try {
            selector = [
                `#${sourceLayer}`,
                ...zoomPredicates(layer.minzoom, layer.maxzoom),
                ...translateFilter(layer.filter ?? null),
                `::${attachmentName(layer.id)}`,
            ].join('');
        } catch (error) {
            const why = error instanceof Untranslatable ? error.what : String(error);
            coverage.drop(`filter on "${layer.id}"`, `untranslatable filter: ${why}`, layer.id);
            return;
        }

        blocks.push(`${selector} {\n${declarations.map((d) => `  ${d}`).join('\n')}\n}`);
    });

    reportInterleaving(layers, order, coverage);

    const header = [
        '/* Generated by massif-style mapbox2css. Do not edit by hand:',
        '   re-run the converter against the source style instead. */',
    ];
    if (style.name) header.push(`/* Source style: ${style.name} */`);

    const mss = [
        ...header,
        '',
        ...(mapBlock.length > 0 ? [`Map {\n${mapBlock.map((d) => `  ${d}`).join('\n')}\n}`, ''] : []),
        ...blocks,
        '',
    ].join('\n');

    // loadMapProject REVERSES this array (layerNames.insert(begin)), and MapBox layers run
    // bottom-to-top, so the project list is the draw order reversed.
    const projectLayers = [...order.entries()].sort((a, b) => a[1] - b[1]).map(([name]) => name).reverse();
    const project = JSON.stringify({ styles: ['style.mss'], layers: projectLayers }, null, 2) + '\n';

    return { mss, project, coverage };
}

function backgroundProperties(layer: MapboxLayer, coverage: Coverage): string[] {
    const out: string[] = [];
    for (const [name, value] of Object.entries(layer.paint ?? {})) {
        const target = PROPERTY_MAP.background[name];
        if (!target) {
            coverage.drop(name, KNOWN_GAPS[name] ?? 'not mapped', layer.id);
            continue;
        }
        try {
            out.push(`${target}: ${translateExpression(value)};`);
            coverage.emit(target);
        } catch (error) {
            coverage.drop(name, describe(error), layer.id);
        }
    }
    return out;
}

function layerDeclarations(
    layer: MapboxLayer,
    symbolizer: string,
    allowed: Map<string, CartoProperty>,
    coverage: Coverage,
): string[] {
    const table = PROPERTY_MAP[layer.type] ?? {};
    const out: string[] = [];

    for (const [name, value] of Object.entries({ ...layer.layout, ...layer.paint })) {
        if (name === 'visibility') {
            if (value === 'none') return []; // the whole layer is off
            continue;
        }
        // A fill's outline is a second symbolizer on the same rule, not a polygon property.
        if (name === 'fill-outline-color') {
            const translated = tryTranslate(value, name, layer.id, coverage);
            if (translated !== null) {
                out.push(`line-color: ${translated};`, 'line-width: 1;');
                coverage.emit('line-color');
            }
            continue;
        }

        const target = table[name];
        if (!target) {
            coverage.drop(name, KNOWN_GAPS[name] ?? 'not mapped', layer.id);
            continue;
        }
        if (!allowed.has(target)) {
            // The table above claims a property the decoder does not bind - a bug here, not in the
            // source style. Say so rather than blaming the style.
            coverage.drop(name, `maps to "${target}", absent from the generated allowlist`, layer.id);
            continue;
        }

        const translated = tryTranslate(value, name, layer.id, coverage);
        if (translated === null) continue;
        out.push(`${target}: ${remapValue(target, translated)};`);
        coverage.emit(target);
    }

    // text-name is what makes a text symbolizer exist at all; without it the translator drops the
    // rule and every other text property with it.
    if (symbolizer === 'text' && !out.some((d) => d.startsWith('text-name:'))) {
        if (out.length > 0) {
            coverage.drop(`layer "${layer.id}"`, 'symbol layer with no text-field (icon-only)', layer.id);
        }
        return [];
    }
    return out;
}

function tryTranslate(value: Json, name: string, layerId: string, coverage: Coverage): string | null {
    try {
        // text-font is a list; CartoCSS takes the first face name.
        if (Array.isArray(value) && name === 'text-font' && typeof value[0] === 'string') {
            return translateExpression(value[0]);
        }
        return translateExpression(value);
    } catch (error) {
        coverage.drop(name, describe(error), layerId);
        return null;
    }
}

function remapValue(target: string, translated: string): string {
    const map = VALUE_MAP[target];
    if (!map) return translated;
    const bare = translated.replace(/^'|'$/g, '');
    return map[bare] !== undefined ? `'${map[bare]}'` : translated;
}

/**
 * One entry in the project's `layers` pulls EVERY attachment of that name, so two MapBox layers on
 * different source-layers cannot be interleaved. Report each inversion rather than let the style
 * quietly draw in the wrong order.
 */
function reportInterleaving(layers: MapboxLayer[], order: Map<string, number>, coverage: Coverage): void {
    let inversions = 0;
    let previous = -1;
    for (const layer of layers) {
        const sourceLayer = layer['source-layer'];
        if (!sourceLayer || !order.has(sourceLayer)) continue;
        const position = order.get(sourceLayer)!;
        if (position < previous) inversions++;
        previous = position;
    }
    if (inversions > 0) {
        coverage.note(
            `${inversions} layer(s) draw out of order: a CartoCSS project entry pulls every ` +
            `attachment of its source-layer, so interleaved source-layers cannot be preserved.`,
        );
    }
}

function describe(error: unknown): string {
    return error instanceof Untranslatable ? `untranslatable: ${error.what}` : String(error);
}
