// Generated by scripts/gen-api-constants.py. Do not edit.
//
// The facade's strings as typed constants. In Swift these arrive as MassifProperty.opacity
// and friends, so nothing has to spell a string out.

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/** A property path segment. */
typedef NSString *MassifProperty NS_TYPED_ENUM;

/** Encodes this map color into 32-bit integer value (ARGB format). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyARGB;
/** Returns the dots per inch value. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDPI;
/** Returns the value used for converting display independent pixels (dp) to pixels (px). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDPToPX;
/** Returns the vertical field of view angle. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFOVY;
/** Returns the current set of HTTP headers used. Initially this set is empty and can be changed with setHTTPHeaders. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHTTPHeaders;
/** Returns true/false based whether the TMS tiling scheme is used. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTMSScheme;
/** Returns the tile data source of the associated UTF grid. By default this is null. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyUTFGridDataSource;
/** Returns the UTF grid event listener. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyUTFGridEventListener;
/** Returns true if Z-buffering is enabled for 2D geometry. By default it is disabled and used only for billboards. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyZBuffering;
/** Returns the alpha component of this map color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyA;
/** Returns the shading color used to accentuate rugged terrain like sharp cliffs and gorges. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAccentColor;
/** Returns the accuracy of the points in the request. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAccuracy;
/** Returns the action of the instruction. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAction;
/** Returns the altitude of a direction-anchored object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAltitude;
/** Returns the ambient light color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAmbientColor;
/** Returns the ambient light intensity. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAmbientIntensity;
/** Returns the color of the ambient light. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAmbientLightColor;
/** Returns the horizontal anchor point of the label. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAnchorPointX;
/** Returns the vertical anchor point of the label. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAnchorPointY;
/** Returns the screen position of the anchor point of this popup in pixels. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAnchorScreenPos;
/** Returns the angular size of the sprite. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAngularSize;
/** Returns the cluster animation flag value. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAnimatedClusters;
/** Returns the animation duration, in seconds. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAnimationDuration;
/** Returns true if the interaction has started an animation. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAnimationStarted;
/** Returns the animation style of the billboard. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAnimationStyle;
/** Returns the number of elements in the array. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyArraySize;
/** Returns the aspect ratio of the map screen. Equal to width / height. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAspectRatio;
FOUNDATION_EXPORT MassifProperty const MassifPropertyAssetNames;
/** Returns the style asset package. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAssetPackage;
/** Returns the horizontal attaching anchor point of the billoard. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAttachAnchorPointX;
/** Returns the vertical attaching anchor point of the billoard. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAttachAnchorPointY;
/** Returns the azimuth of a direction-anchored object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyAzimuth;
/** Returns the blue component of this map color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyB;
/** Returns the background bitmap. May be null. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBackgroundBitmap;
/** Returns the background color of the button. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBackgroundColor;
/** Returns the balloon popup event listener. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBalloonPopupEventListener;
/** Returns the base billboard this billboard is attached to. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBaseBillboard;
/** Returns the base contour interval in meters. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBaseInterval;
/** Returns the base projection. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBaseProjection;
/** Returns the base URL template containing tags. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBaseURL;
/** Returns whether the part of the curve below the horizon is drawn. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBelowHorizonVisible;
/** Returns the billboard/label terrain occlusion state. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBillboardOcclusionEnabled;
/** Returns the billboard/label terrain occlusion tolerance. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBillboardOcclusionTolerance;
/** Returns the bitmap of the sprite. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBitmap;
/** Returns the bitmap scaling factor. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBitmapScale;
/** Returns the boolean value of this variant. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBool;
/** Returns the color of the border. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBorderColor;
/** Returns the width of the border. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBorderWidth;
FOUNDATION_EXPORT MassifProperty const MassifPropertyBottom;
/** Returns the bounds of this billboard or the base billboard, if there is one. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBounds;
/** Returns the state of the 'break lines' flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBreakLines;
/** Returns the current display order of the buildings. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBuildingRenderOrder;
/** Returns the clicked button. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyButton;
/** Returns the margins for the buttons of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyButtonMargins;
/** Returns the width of the button. If this value is -1, then button width is calculated automatically based on button text. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyButtonWidth;
/** Returns the bytes per pixel parameter of this bitmap. Valid values are 1, 2, 3 and 4. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyBytesPerPixel;
/** Returns the state of the camera changed flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCameraChanged;
/** Returns the duration of the camera terrain-following correction animation. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCameraClampDuration;
/** Returns the camera terrain clearance: the minimum height the camera is kept above the terrain surface, in meters. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCameraClearance;
FOUNDATION_EXPORT MassifProperty const MassifPropertyCapacity;
/** Returns the CartoCSS string used for the style. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCartoCSS;
/** Returns the current CartoCSS style set used by the decoder. If decoder uses non-CartoCSS style set, null is returned. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCartoCSSStyle;
/** Returns the state of the causes overlap flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCausesOverlap;
/** Returns the object event listener. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCelestialEventListener;
/** Calculates the center map position of this map envelope object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCenter;
FOUNDATION_EXPORT MassifProperty const MassifPropertyCenterPos;
/** Returns the clear color used by the renderer before drawing anything else. By default, this is white. It should be set to (0, 0, 0, 0) if transparent MapView is needed. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClearColor;
/** Returns the click handler layer filter. The filter is given as ECMA regular expression that is applied to qualified layer names. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClickHandlerLayerFilter;
/** Returns the click info. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClickInfo;
/** Returns the click position. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClickPos;
/** Returns the click radius of the curve. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClickRadius;
/** Returns the click size of the marker. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClickSize;
/** Returns the click type. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClickType;
/** Returns the click type detection state. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClickTypeDetection;
/** Returns the width of the line used for click detection. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClickWidth;
/** Returns the current callback used for creating cluster elements. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyClusterElementBuilder;
/** Returns the color of the object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyColor;
/** Returns the color format of this bitmap. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyColorFormat;
/** Returns the current compiled style set used by the decoder. If decoder uses non-compiled style set, null is returned. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCompiledStyle;
/** Returns the contour line color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyContourColor;
/** Returns whether GPU contour lines are drawn over the hillshade. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyContourEnabled;
/** Returns the spacing between contour lines in meters. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyContourInterval;
/** Returns the contour line half-width in screen pixels. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyContourWidth;
/** Returns the contrast of the hillshade overlay. This is the equivalent of MapLibre's 'hillshade-exaggeration' paint property: it controls the slope response curve and the overall strength of the shading, not the relief itself. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyContrast;
/** Returns the convex hull of this map envelope. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyConvexHull;
/** Returns the corner radius of the button. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCornerRadius;
/** Returns the current layer count. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCount;
/** Returns the culling delay of the layer in milliseconds. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCullDelay;
/** Returns the custom backend service URL. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyCustomServiceURL;
/** Returns tile data as binary data. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyData;
/** Returns the extent of the tiles in this data source. The bounds are in coordinate system of the projection of the data source. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDataExtent;
/** Returns the original data source that the cache uses. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDataSource;
/** Returns the state of the tile border debug overlay. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDebugTileBorders;
/** Returns the default layer buffer in tile pixels. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDefaultLayerBuffer;
/** Calculates the difference vector between the maximum and minimum map positions of this map bounds object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDelta;
/** Returns the clip-space depth bias used when depth-testing draped 2D geometry against the terrain. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDepthBias;
/** Returns the description of this balloon popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDescription;
/** Returns the color of the description. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDescriptionColor;
/** Returns the description field variable to use. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDescriptionField;
/** Returns the name of the description font. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDescriptionFontName;
/** Returns the size of the description font. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDescriptionFontSize;
/** Returns the margins of the description. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDescriptionMargins;
/** Returns the state of the description wrap parameter. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDescriptionWrap;
/** Returns the full path of the directory containing the assets. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDirPath;
/** Returns true if the object is anchored by direction, false if by geographic position. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDirectionAnchored;
/** Returns the distance of a direction-anchored object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDistance;
/** Returns the floating point value of this variant. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDouble;
/** Returns the double click detection state. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDoubleClickDetection;
/** Returns the double click max duration in seconds. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDoubleClickMaxDuration;
/** Returns whether polygon fills are draped as a render-to-texture surface. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDrapeFillsEnabled;
/** Returns whether vt tile lines are also draped (in addition to fills). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDrapeLinesEnabled;
/** Returns the per-tile drape texture resolution, 0 when it follows the screen. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDrapeResolution;
/** Returns the draw distance value. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDrawDistance;
/** Returns the click duration in seconds. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyDuration;
/** Returns the corresponding matching edge index in the matching result. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyEdgeIndex;
/** Returns the 2D click position on the clicked popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyElementClickPos;
/** Returns the info tag of the clicked element. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyElementInfo;
/** Returns the list of vector elements. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyElements;
/** Returns whether the normal map encodes absolute elevation (so a custom normal-map lighting shader can call getElevation()). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyElevationEncodingEnabled;
/** Returns whether elevation tile prefetching is enabled. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyElevationPrefetchEnabled;
/** Returns whether the fog is drawn at all. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyEnabled;
/** Gets the current encoding type. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyEncoding;
/** Returns the number of threads used by the envelope task pool. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyEnvelopeThreadPoolSize;
/** Returns the normal vector tile should be exagerated based on the zoom level. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyExagerateHeightScaleEnabled;
/** Returns the per-frame relief exaggeration factor, i.e. the vertical exaggeration of the slope. Unlike height scale this is a shader uniform applied at render time (no tile re-decode), so it can be animated smoothly. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyExaggeration;
/** Returns the fade animation type. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFadeAnimationType;
/** Returns the far plane distance. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFar;
/** Returns the clicked feature. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeature;
/** Returns the position on the clicked feature, that is close to the click position. For points it will always be the center position, for lines it will be the closest point on the line, for billboards it will be the anchor point and for polygons it's equal to getClickPos(). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeatureClickPos;
/** Returns the feature collection of the search service. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeatureCollection;
/** Returns the number of features in this container. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeatureCount;
/** Returns the id of the clicked feature. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeatureId;
/** Returns the value of feature id override flag. This is intended for cases when feature ids in tile are not globally unique. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeatureIdOverride;
/** Returns the name of the layer of the clicked feature. Note that this is the layer name in the tile, not the name of style layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeatureLayerName;
/** Returns the position of the clicked feature. For a MultiPoint this is the point that was clicked, not the centre of the whole set - which getFeatureClickPos deliberately does not cover, and which a caller otherwise has to reconstruct from getFeaturePosIndex plus a downcast. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeaturePos;
/** In case of MultiPoint PointGeometry this will return the index of the clicked position */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFeaturePosIndex;
/** Returns the vertial field of view angle. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFieldOfViewY;
/** Returns the string based search expression. If empty, then search expression is not used. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFilterExpression;
/** Returns the state of the flippable flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFlippable;
/** Returns the focus point offset (from screen center) in pixels. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFocusPointOffset;
/** Returns the fog (atmosphere) options. May be null. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFogOptions;
/** Returns the font's color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFontColor;
/** Returns the font's name. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFontName;
/** Returns the font's size. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFontSize;
/** Returns the fragment shader source of the effect. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFragmentShader;
/** Returns the frame count defined in the Torque style. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFrameCount;
/** Returns the time of this map tile. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFrameNr;
/** Returns how fast a free roam drag turns the view. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFreeRoamLookSensitivity;
/** Returns the free roam mode. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFreeRoamMode;
/** Returns how far a first person move drag travels. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyFreeRoamMoveSpeed;
/** Returns the green component of this map color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyG;
/** Returns the geometry object that defines the location of this billboard. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyGeometry;
/** Returns the number of geometry objects in this multi geometry container. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyGeometryCount;
/** Returns the feature's geometry as a GeoJSON string, in its own coordinates. Serialising a geometry otherwise means constructing a GeoJSONGeometryWriter in the binding, which every binding then does differently and, in a scripting one, slowly. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyGeometryGeoJSON;
/** Returns the active geometry simplifier of the data source. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyGeometrySimplifier;
/** Returns the geometry tag associated with the instructions. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyGeometryTag;
/** Returns the ground color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyGroundColor;
/** Returns the height of the bitmap. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHeight;
/** Returns the height scale of the hillshade overlay. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHeightScale;
/** Returns the state of the allow overlap flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHideIfOverlapped;
/** Returns the color of the upper atmosphere. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHighColor;
/** Returns the shading color of areas that faces towards the light source. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHighlightColor;
/** Returns the hillshade rendering method. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHillshadeMethod;
/** Returns the list of map position lists defining the inner rings of the polygon (holes). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHoles;
/** Returns the elevation angle the fog is still at full strength at. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHorizonAngle;
/** Returns how far up the sky the fog is blended in. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHorizonBlend;
/** Returns the horizon color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHorizonColor;
/** Returns the horizontal offset of the billboard. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyHorizontalOffset;
/** Returns the internal id of this vector element. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyId;
/** Returns the illumination direction of the layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyIlluminationDirection;
/** Returns wheter the illumination direction should change with the map rotation. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyIlluminationMapRotationEnabled;
/** Returns the optional instruction description. This info is dependent on the routing engine (can be empty) and may be localized. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyInstruction;
/** Returns the number of turn-by-turn instructions. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyInstructionCount;
/** Returns the turn-by-turn instruction list. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyInstructions;
/** Returns the interpolated color at the click position. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyInterpolatedColor;
/** Returns the state of the kinetic panning flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyKineticPan;
/** Returns the state of the kinetic rotation flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyKineticRotation;
/** Returns the state of kinetic zoom flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyKineticZoom;
/** Returns the current relative label blending speed. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLabelBlendingSpeed;
/** Returns the contour interval used for label stubs. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLabelInterval;
/** Returns the current display order of the labels. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLabelRenderOrder;
/** Returns whether only short label stubs are generated instead of full contour lines. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLabelStubsEnabled;
/** Returns the layer of the raster tile. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLayer;
/** Returns the current relative layer blending speed. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLayerBlendingSpeed;
/** Returns the name of the generated vector tile layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLayerName;
/** Returns the layers to filter while decoding tiles. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLayers;
/** Returns wether layers are processed in reversed order to process labels. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLayersLabelsProcessedInReverseOrder;
FOUNDATION_EXPORT MassifProperty const MassifPropertyLeft;
/** Returns the background color of the left part of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLeftColor;
/** Returns the image of the left part of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLeftImage;
/** Returns the margins of the left part of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLeftMargins;
/** Returns whether the legacy (pre-MapLibre-parity) height scale formula is used. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLegacyHeightScaleEnabled;
/** Calculates the length of this map range. Defined as max - min. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLength;
/** Returns the length of the arrow after the maneuver point. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLengthAfter;
/** Returns the length of the arrow before the maneuver point. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLengthBefore;
/** Returns the light (sun) options. May be null. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLightOptions;
/** Returns the end point type of the line. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLineEndType;
/** Returns the join type of the line. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLineJoinType;
/** Returns the line style. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLineStyle;
/** Returns the list of assets stored in the directory, ignoring the base asset package. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLocalAssetNames;
/** Returns the current log listener. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLogEventListener;
/** Returns the integer value of this variant. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLong;
/** Returns the long click duration in seconds. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyLongClickDuration;
/** Returns the color of the main light. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMainLightColor;
/** Returns the direction of the main light. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMainLightDirection;
/** Returns the map renderer listener. Can be null. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMapRendererListener;
/** Returns the tile id of the clicked feature. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMapTile;
/** Returns the list with details of the matched edges. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMatchingEdges;
/** Returns the list with details of the matched points. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMatchingPoints;
/** Returns the maximum (north east) map position of this map envelope object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMax;
/** Returns the maximum age of the tile data, tile data will expire after that point. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaxAge;
/** Returns true/false based on whether the max-age header check is used. If this is enabled, SDK will automatically refresh the tiles when tiles have expired. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaxAgeHeaderCheck;
/** Gets the current maximum overzoom level for this datasource. Over it the datasource will not be "drawn" */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaxOverzoomLevel;
/** Returns the maximum number of results the search service returns. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaxResults;
/** Returns how many zoom levels below the camera a tile may coarsen to. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaxTileZoomCoarsening;
/** Returns the maximum visible tile zoom offset, relative to the camera zoom level. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaxTileZoomOffset;
/** Gets the current maximum underzoom level for this layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaxUnderzoomLevel;
/** Returns the maximum zoom level supported by this data source. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaxZoom;
/** Returns the maximum zoom level when clusters are shown. If zoom level is greater, then clusters are replaced with individual elements. Default is 24. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMaximumClusterZoom;
/** Returns the terrain mesh resolution. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMeshResolution;
/** Returns a copy of the layer meta data map. The changes you make to this map are NOT reflected in the actual meta data of the layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMetaData;
/** Calculate the midrange value. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMidrange;
/** Returns the minimum (south west) map position of this map envelope object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMin;
/** Returns the minimum zoom at which contour geometry is generated. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMinVisibleZoom;
/** Returns the minimum zoom level supported by this data source. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMinZoom;
/** Returns the current minimum distance between clusters (in device-independent pixels). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyMinimumClusterDistance;
/** Returns the model asset of the object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyModelAsset;
/** Returns the name of the effect. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyName;
/** Returns the near plane distance. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyNear;
/** Returns the color of the nearest pixel to the click position. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyNearestColor;
/** Returns the style layers that are kept out of the terrain drape bake. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyNoDrapeLayerFilter;
FOUNDATION_EXPORT MassifProperty const MassifPropertyNormalMapLightingShader;
/** Creates a new map vector by normalizing this map vector. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyNormalized;
/** Returns all the keys in the object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyObjectKeys;
/** Returns the opacity of this layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyOpacity;
/** Returns the orientation mode of the label. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyOrientationMode;
/** Returns true if the interaction included a map pan action. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPanAction;
/** Returns the map panning bounds constraints. Map bounds minimum and maximum points are in the base projection's coordinate system. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPanBounds;
/** Returns the panning mode. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPanningMode;
/** Returns the panning speed mode. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPanningSpeedMode;
/** Returns the phase-in duration of the animation. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPhaseInDuration;
/** Returns the phase-out duration of the animation. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPhaseOutDuration;
/** Returns the pivot mode. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPivotMode;
/** Returns the placement priority of the billboard. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPlacementPriority;
/** Returns the number of points in the path. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPointCount;
/** Returns the index of the first geometry point in external point array. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPointIndex;
/** Returns the point style. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPointStyle;
/** Returns the measured points of the request. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPoints;
/** Returns the polygon style. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPolygonStyle;
/** Returns the clicked popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPopup;
/** Returns the handler used for the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPopupHandler;
/** Returns the position of the point. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPos;
/** Returns the list of of map positions defining the line. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPoses;
/** Returns the geographic position of a position-anchored object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPosition;
/** Returns the altitude of a position-anchored object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPositionAltitude;
/** Returns whether this layer goes through the post-process effect. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPostProcessed;
/** Returns the state of the preloading flag of this layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPreloading;
/** Returns wether to prevent duplicate elements */
FOUNDATION_EXPORT MassifProperty const MassifPropertyPreventDuplicates;
FOUNDATION_EXPORT MassifProperty const MassifPropertyProfile;
/** Returns the projection of the feature collection of the search service. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyProjection;
/** Returns the properties of the feature. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyProperties;
/** Returns the red component of this map color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyR;
/** Returns the angular radius of a circular arc. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRadius;
/** Returns where the fog reaches full strength. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRangeEnd;
/** Returns where the fog starts. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRangeStart;
/** Returns the raster tile event listener. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRasterTileEventListener;
/** Returns raw result */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRawResult;
/** Returns the regular expression used to search all the fields. If empty, then the regular expression is not used. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRegexFilter;
/** Returns the relative speed of the animation. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRelativeSpeed;
/** Returns the render projection mode. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRenderProjectionMode;
/** Returns the relative rendering scale of the label. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRenderScale;
/** Returns the renderer layer filter. The filter is given as ECMA regular expression that is applied to qualified layer names. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRendererLayerFilter;
/** Returns true if the tile should be replaced with parent tile. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyReplaceWithParent;
/** Returns the target grid resolution used for contour tracing. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyResolution;
/** Returns the state of the restricted panning flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRestrictedPanning;
FOUNDATION_EXPORT MassifProperty const MassifPropertyRight;
/** Returns the background color of the right part of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRightColor;
/** Returns the image of the right part of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRightImage;
/** Returns the margins of the right part of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRightMargins;
/** Returns the list of map position lists defining the rings of the polygon. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRings;
/** Returns the location of the root billboard. If this billboard has a location, this method is equavalent to the Billboard::getGeometry method. If this billboard is attached to another billboard, the hierarchy is traveled recursively and the location of the root billboard is returned. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRootGeometry;
/** Returns the state of the map rotatability flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRotatable;
/** Returns true if the interaction included a rotate action. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRotateAction;
/** Returns the rotation angle of this billboard. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRotation;
/** Returns the rotation angle of this model. This is deprecated. Use getRotation instead. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRotationAngle;
/** Returns the rotation axis of this model. If rotation angle is 0, then the axis is irrelevant. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyRotationAxis;
/** Returns the scale of this model. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyScale;
/** Returns the state of the scale with DPI flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyScaleWithDPI;
/** Returns the scaling mode of the label. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyScalingMode;
/** Returns the screen bounds, so that the popup can be clipped if neccessary. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyScreenBounds;
/** Returns the screen height. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyScreenHeight;
/** Returns the screen size of the sprite. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyScreenSize;
/** Returns the screen width. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyScreenWidth;
/** Returns whether seamless tile edges are enabled. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySeamlessEdgesEnabled;
/** Returns the state of seamless horizontal panning flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySeamlessPanning;
/** Returns whether seamless tile edge handling is enabled. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySeamlessTileEdgesEnabled;
/** Returns the search radius for proximity search (in meters). The default is 0. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySearchRadius;
/** Returns true if the directions are read as separate segments rather than as a path. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySegmented;
/** Returns the custom fragment shader source. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShaderSource;
/** Returns the shadow depth bias. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowBias;
/** Returns the number of shadow cascades. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowCascades;
/** Returns the shadow caster margin in tiles. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowCasterMargin;
/** Returns the shading color of areas that face away from the light source. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowColor;
/** Returns the shadow distance. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowDistance;
/** Returns the shadow map resolution. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowMapSize;
/** Returns the shadow normal offset. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowNormalOffset;
/** Returns the shadow softness. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowSoftness;
/** Returns the shadow strength. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShadowStrength;
/** Returns the state of internal debug message logging. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShowDebug;
/** Returns the state of error logging. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShowError;
/** Returns the state of general info logging. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShowInfo;
/** Returns the state of warning logging. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyShowWarn;
/** Returns the color for sides of the 3d polygon. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySideColor;
/** Returns the simplification tolerance in tile pixels. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySimplifyTolerance;
/** Returns whether single-pass segmented rendering is enabled (Milestone 6, optional). */
FOUNDATION_EXPORT MassifProperty const MassifPropertySinglePassRenderingEnabled;
/** Returns the size of the data */
FOUNDATION_EXPORT MassifProperty const MassifPropertySize;
/** Returns the size-related animation type. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySizeAnimationType;
/** Returns the sky color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySkyColor;
/** Returns the sky options. May be null. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySkyOptions;
/** Returns the edge softness of a disc sprite. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySoftness;
/** Returns wether result features are sorted by distance */
FOUNDATION_EXPORT MassifProperty const MassifPropertySortByDistance;
/** Returns the current source projection. If source projection is set, all geometry coordinates will be converted from given coordinate system to WGS84. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySourceProjection;
/** Returns the color of the sky at the zenith, beyond the atmosphere. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySpaceColor;
/** Returns how brightly stars are drawn beyond the atmosphere. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStarIntensity;
/** Returns the name of street. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStreetName;
/** Returns the stretching factor of the line. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStretchFactor;
/** Returns the string value of this variant. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyString;
/** Returns the color of the stroke surrounding the button. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStrokeColor;
/** Returns the width of the stroke surrounding the button. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStrokeWidth;
/** Returns the style of this balloon popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStyle;
/** Returns the asset name defining the current style name. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStyleAssetName;
/** Returns the ordered list of style layer names as declared by the style (the project JSON "layers" array, or the Layer elements of a Mapnik XML style). This defines both the draw order and which layers exist. CompositeVectorTileLayer uses it to place external data sources in the layer order: a source whose name is not in this list has no slot in the style and is not drawn, so this is the way to check a style before wiring sources into it. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStyleLayerNames;
/** Returns the current style name. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStyleName;
/** Returns the list of all available style parameters. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStyleParameters;
/** Returns the current style set used by the decoder. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyStyleSet;
/** Returns the subdomains for {s} tag. The default is ["a", "b", "c", "d"]. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySubdomains;
/** Returns the sun altitude in degrees above the horizon. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySunAltitude;
/** Returns the sun azimuth in degrees. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySunAzimuth;
/** Returns the sun (directional light) color. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySunColor;
/** Returns whether the built-in shader draws a sun disc. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySunDiscEnabled;
/** Returns the sun light intensity. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySunIntensity;
/** Returns the custom terrain surface fragment shader source, or an empty string if no shaded surface is drawn. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySurfaceShaderSource;
/** Returns the state of the synchronized refresh flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertySynchronizedRefresh;
/** Returns the user-defined tag associated with the button. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTag;
/** Returns the current target projection. If target projection is set, all geometry coordinates will be converted from WGS84 to target projection coordinate system. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTargetProjection;
/** Returns true if the effect needs the terrain depth pre-pass (uTerrainDepthTex). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTerrainDepthRequired;
/** Returns whether the sun lights the 3D terrain surface. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTerrainLightingEnabled;
/** Returns the terrain options whose elevation manager the label stubs read. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTerrainOptions;
/** Returns whether the layer may shade the 3D terrain's own elevation texture instead of loading a DEM tile set of its own. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTerrainPaintEnabled;
/** Returns whether the terrain paint shades from the elevation source's own maximum zoom. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTerrainPaintFullDetailEnabled;
/** Returns the text of this button. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyText;
/** Returns the color of the text. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTextColor;
/** Returns the text field variable to use. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTextField;
/** Returns the name of the text font. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTextFontName;
/** Returns the size of the text font. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTextFontSize;
/** Returns the margins of the text. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTextMargins;
/** Returns the opacity a label keeps while its anchor is behind 3D content. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTextOcclusionOpacity;
/** Returns the tile texture cache capacity. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTextureCacheCapacity;
/** Returns the current relative tile blending speed. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileBlendingSpeed;
/** Returns the tile cache capacity. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileCacheCapacity;
/** Returns the tile decoder assigned to this layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileDecoder;
/** Returns the tile size used for drawing map tiles. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileDrawSize;
/** Returns whether cross-LOD tile edge stitching is enabled. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileEdgeStitchingEnabled;
/** Returns the current tile filter mode. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileFilterMode;
/** Returns the binary format the tiles are decoded as. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileFormat;
/** Returns the internal tile id of this map tile. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileId;
/** Returns the factor on the screen size a tile may cover before it is refined. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileLODFactor;
/** Returns how many zoom levels a tile may lose to foreshortening. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileLODForeshorteningLimit;
/** Returns the tile load listener. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileLoadListener;
/** Returns the current tile substitution policy. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileSubstitutionPolicy;
/** Returns the number of threads used by the tile task pool. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTileThreadPoolSize;
/** Returns the camera tilt angle. A NEGATIVE tilt means the view looks above the horizon. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTilt;
/** Returns true if the interaction included a tilt action. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTiltAction;
/** Returns true if tilting gesture direction is reversed (and same as with Google Maps). */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTiltGestureReversed;
/** Returns the tilt range constraint. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTiltRange;
/** Returns the time approximate duration of the instruction. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTime;
/** Returns the current timeout value. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTimeout;
/** Returns the title of this balloon popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTitle;
/** Returns the color of the title. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTitleColor;
/** Returns the title field variable to use. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTitleField;
/** Returns the name of the title font. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTitleFontName;
/** Returns the size of the title font. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTitleFontSize;
/** Returns the margins of the title. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTitleMargins;
/** Returns the state of the title wrap parameter. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTitleWrap;
FOUNDATION_EXPORT MassifProperty const MassifPropertyTop;
/** Returns the total distance of the path. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTotalDistance;
/** Returns the approximate total duration of the path. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTotalTime;
/** Returns the height of the triangle at the bottom of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTriangleHeight;
/** Returns the width of the triangle at the bottom of the popup. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTriangleWidth;
/** Returns the turn angle of the action. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyTurnAngle;
/** Returns the type of the matching point. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyType;
/** Returns the conversion ratio between internal map units and screen density independent pixels (DP or DIP). This parameter is dependent on the zoom level, DPI and other screen parameters. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyUnitToDPCoef;
/** Returns the conversion ratio between internal map units and screen pixels. This parameter is dependent on the zoom level and other screen parameters. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyUnitToPXCoef;
/** Returns the layer task priority of this layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyUpdatePriority;
/** Returns the state of the user input flag. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyUserInput;
/** Returns the clicked vector element. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyVectorElement;
/** Returns the vector element event listener. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyVectorElementEventListener;
/** Returns the vector tile event listener. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyVectorTileEventListener;
/** Returns the vertical offset of the billboard. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyVerticalOffset;
/** Returns the absolute view distance, in meters. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyViewDistance;
/** Returns the factor applied to the view distance. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyViewDistanceFactor;
/** Returns a view state. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyViewState;
/** Returns the visibility of the object. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyVisible;
/** Returns the visible zoom range of this layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyVisibleZoomRange;
/** Returns the width of the bitmap. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyWidth;
/** Returns the x coordinate of this map position. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyX;
/** Returns the y coordinate of this map position. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyY;
/** Returns the state of Z coordinate serialization. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyZ;
/** Returns the zoom level of this map tile. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyZoom;
/** Returns the distance between the focus and the camera position, when the zoom level is set to 0. This parameter depends on the screen size, DPI, tile draw size and field of view settings. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyZoom0Distance;
/** Returns true if the interaction included a zoom action. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyZoomAction;
/** Returns the state of zoom gestures. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyZoomGestures;
/** Gets the current zoom level bias for this layer. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyZoomLevelBias;
/** Returns the zoom range constraint. */
FOUNDATION_EXPORT MassifProperty const MassifPropertyZoomRange;

/** A method name. */
typedef NSString *MassifMethod NS_TYPED_ENUM;

FOUNDATION_EXPORT MassifMethod const MassifMethodAdd;
FOUNDATION_EXPORT MassifMethod const MassifMethodCalculateRoute;
FOUNDATION_EXPORT MassifMethod const MassifMethodClear;
FOUNDATION_EXPORT MassifMethod const MassifMethodClearTileCaches;
FOUNDATION_EXPORT MassifMethod const MassifMethodCreateLayer;
FOUNDATION_EXPORT MassifMethod const MassifMethodDeleteLayer;
FOUNDATION_EXPORT MassifMethod const MassifMethodFindFeatures;
FOUNDATION_EXPORT MassifMethod const MassifMethodGetElevation;
FOUNDATION_EXPORT MassifMethod const MassifMethodGetElevations;
FOUNDATION_EXPORT MassifMethod const MassifMethodGetFeature;
FOUNDATION_EXPORT MassifMethod const MassifMethodGetInstruction;
FOUNDATION_EXPORT MassifMethod const MassifMethodGetPoints;
FOUNDATION_EXPORT MassifMethod const MassifMethodGetStyleParameter;
FOUNDATION_EXPORT MassifMethod const MassifMethodLoadTile;
FOUNDATION_EXPORT MassifMethod const MassifMethodRefresh;
FOUNDATION_EXPORT MassifMethod const MassifMethodRemove;
FOUNDATION_EXPORT MassifMethod const MassifMethodSetCustomParameter;
FOUNDATION_EXPORT MassifMethod const MassifMethodSetLayerGeoJSON;
FOUNDATION_EXPORT MassifMethod const MassifMethodSetStyleParameter;

/** An event name. */
typedef NSString *MassifEvent NS_TYPED_ENUM;

FOUNDATION_EXPORT MassifEvent const MassifEventMapClicked;
FOUNDATION_EXPORT MassifEvent const MassifEventMapIdle;
FOUNDATION_EXPORT MassifEvent const MassifEventMapInteraction;
FOUNDATION_EXPORT MassifEvent const MassifEventMapMoved;
FOUNDATION_EXPORT MassifEvent const MassifEventMapStable;
FOUNDATION_EXPORT MassifEvent const MassifEventVectorelementClicked;
FOUNDATION_EXPORT MassifEvent const MassifEventVectortileClicked;

/** An object kind. */
typedef NSString *MassifKind NS_TYPED_ENUM;

FOUNDATION_EXPORT MassifKind const MassifKindAssets;
FOUNDATION_EXPORT MassifKind const MassifKindElement;
FOUNDATION_EXPORT MassifKind const MassifKindElementstyle;
FOUNDATION_EXPORT MassifKind const MassifKindFeature;
FOUNDATION_EXPORT MassifKind const MassifKindGeometry;
FOUNDATION_EXPORT MassifKind const MassifKindLayer;
FOUNDATION_EXPORT MassifKind const MassifKindOptions;
FOUNDATION_EXPORT MassifKind const MassifKindRouting;
FOUNDATION_EXPORT MassifKind const MassifKindSearch;
FOUNDATION_EXPORT MassifKind const MassifKindSource;
FOUNDATION_EXPORT MassifKind const MassifKindStyle;
FOUNDATION_EXPORT MassifKind const MassifKindStyleset;

/** The types a kind can build. */
typedef NSString *MassifSpecType NS_TYPED_ENUM;

FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeAssetsDir;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeAssetsZip;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeElementBalloon;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeElementMarker;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeElementstyleBalloon;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeElementstyleMarker;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeFeatureFeature;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeGeometryPoint;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeLayerCompositeVector;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeLayerElements;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeLayerHillshade;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeLayerRaster;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeLayerSolid;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeLayerVector;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeOptionsFog;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeOptionsLight;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeOptionsSky;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeOptionsTerrain;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeRoutingValhallaOffline;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeRoutingValhallaOnline;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSearchRequest;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSearchVectortile;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSourceAssets;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSourceCombined;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSourceGeojson;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSourceHttp;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSourceLocal;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSourceMemoryCache;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeSourceOrdered;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeStyleMbvt;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeStylesetCartocss;
FOUNDATION_EXPORT MassifSpecType const MassifSpecTypeStylesetProject;

NS_ASSUME_NONNULL_END
