#!/usr/bin/env python3
"""
Cross-builds GDAL (and PROJ under it) for the Android ABIs, into one prefix per ABI.

    python3 build-gdal-android.py --ndk $ANDROID_NDK_HOME
    python3 build-android.py --profile "standard+gdal" \
        --cmake-options "CMAKE_PREFIX_PATH=<baseDir>/build/gdal/{abi}"

No submodule and nothing in libs-external: the sources are release tarballs fetched here, and the
SDK only ever sees an install prefix through find_package(GDAL). That keeps GDAL out of the default
build entirely - it is not a subproject, so nothing links it unless the gdal profile asks.

What is built, per ABI:

  sqlite3   from the amalgamation already in libs-external, so PROJ has a target sqlite to link.
  PROJ      with TIFF and CURL off - those are only needed for downloading datum grids at runtime,
            which an offline SDK does not do.
  GDAL      static, no apps, no bindings, internal libtiff/libgeotiff/libjson, and the driver set
            below. GDAL_USE_INTERNAL_LIBS is what keeps this to three builds instead of six.

proj.db is generated by PROJ's own build (it needs a HOST sqlite3 for that, hence --host-sqlite3)
and copied next to the prefix. It is NOT optional: GDALRasterTileDataSource calls
importFromEPSG(3857) on every construction, and in PROJ 6+ every EPSG lookup goes through that
database. See docs/features/gdal-ogr.md for how it reaches the device.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tarfile
import urllib.request

# ABI -> the NDK's own name for it. Same strings build-android.py passes.
ABIS = ['arm64-v8a', 'armeabi-v7a', 'x86_64', 'x86']

PROJ_VERSION = '9.4.1'
GDAL_VERSION = '3.9.2'

PROJ_URL = 'https://download.osgeo.org/proj/proj-%s.tar.gz'
GDAL_URL = 'https://github.com/OSGeo/gdal/releases/download/v%s/gdal-%s.tar.gz'

# Raster and vector drivers the SDK's two data sources actually need. Everything else is off:
# GDAL's optional drivers pull in third-party libraries we are deliberately not vendoring.
RASTER_DRIVERS = ['GTiff', 'VRT', 'MEM', 'RAW']
VECTOR_DRIVERS = ['Shapefile', 'GeoJSON', 'GPKG', 'SQLite', 'MEM', 'VRT']


def run(cmd, cwd=None):
    print('==> %s' % ' '.join(cmd))
    subprocess.check_call(cmd, cwd=cwd)


def fetch(url, dest):
    """Downloads and unpacks a release tarball once; a present directory is reused."""
    if os.path.isdir(dest):
        print('==> reusing %s' % dest)
        return dest
    archive = dest + '.tar.gz'
    if not os.path.exists(archive):
        print('==> fetching %s' % url)
        urllib.request.urlretrieve(url, archive)
    print('==> unpacking %s' % archive)
    with tarfile.open(archive) as tar:
        tar.extractall(os.path.dirname(dest))
    return dest


def toolchain_args(args, abi):
    """The same toolchain settings build-android.py configures the SDK with - they have to match,
    or the objects are ABI-compatible but the STL is not."""
    return [
        '-DCMAKE_TOOLCHAIN_FILE=%s/build/cmake/android.toolchain.cmake' % args.ndk,
        '-DCMAKE_SYSTEM_NAME=Android',
        '-DANDROID_ABI=%s' % abi,
        '-DANDROID_NDK=%s' % args.ndk,
        '-DANDROID_PLATFORM=android-%d' % args.api,
        '-DANDROID_STL=c++_static',
        '-DCMAKE_BUILD_TYPE=Release',
        '-DBUILD_SHARED_LIBS=OFF',
    ]


def build_sqlite(args, abi, prefix, workDir):
    """PROJ needs a target sqlite3 to link. The amalgamation is already in the tree, so this is a
    four-line CMake project rather than a fourth download."""
    src = os.path.join(args.base, 'libs-external', 'sqlite')
    if not os.path.exists(os.path.join(src, 'sqlite3.c')):
        sys.exit('sqlite amalgamation not found at %s' % src)
    stage = os.path.join(workDir, 'sqlite-%s' % abi)
    os.makedirs(stage, exist_ok=True)
    with open(os.path.join(stage, 'CMakeLists.txt'), 'w') as f:
        f.write(
            'cmake_minimum_required(VERSION 3.16)\n'
            'project(sqlite3 C)\n'
            'add_library(sqlite3 STATIC "%s/sqlite3.c")\n'
            'target_include_directories(sqlite3 PUBLIC "%s")\n'
            'install(TARGETS sqlite3 ARCHIVE DESTINATION lib)\n'
            'install(FILES "%s/sqlite3.h" "%s/sqlite3ext.h" DESTINATION include)\n'
            % (src, src, src, src))
    build = os.path.join(stage, 'build')
    run(['cmake', '-S', stage, '-B', build, '-DCMAKE_INSTALL_PREFIX=%s' % prefix]
        + toolchain_args(args, abi))
    run(['cmake', '--build', build, '--target', 'install', '--parallel', str(args.jobs)])


def build_proj(args, abi, prefix, workDir):
    src = fetch(PROJ_URL % PROJ_VERSION, os.path.join(workDir, 'proj-%s' % PROJ_VERSION))
    build = os.path.join(workDir, 'proj-build-%s' % abi)
    run(['cmake', '-S', src, '-B', build,
         '-DCMAKE_INSTALL_PREFIX=%s' % prefix,
         '-DCMAKE_PREFIX_PATH=%s' % prefix,
         # Cross-building PROJ needs a HOST sqlite3 binary: its build RUNS one to generate proj.db.
         '-DEXE_SQLITE3=%s' % args.host_sqlite3,
         '-DSQLITE3_INCLUDE_DIR=%s/include' % prefix,
         '-DSQLITE3_LIBRARY=%s/lib/libsqlite3.a' % prefix,
         '-DENABLE_TIFF=OFF',      # only for downloading datum grids, which we do not do
         '-DENABLE_CURL=OFF',
         '-DBUILD_TESTING=OFF',
         '-DBUILD_APPS=OFF',
         '-DBUILD_PROJSYNC=OFF']
        + toolchain_args(args, abi))
    run(['cmake', '--build', build, '--target', 'install', '--parallel', str(args.jobs)])


def build_gdal(args, abi, prefix, workDir):
    src = fetch(GDAL_URL % (GDAL_VERSION, GDAL_VERSION),
                os.path.join(workDir, 'gdal-%s' % GDAL_VERSION))
    build = os.path.join(workDir, 'gdal-build-%s' % abi)
    options = ['cmake', '-S', src, '-B', build,
               '-DCMAKE_INSTALL_PREFIX=%s' % prefix,
               '-DCMAKE_PREFIX_PATH=%s' % prefix,
               '-DPROJ_ROOT=%s' % prefix,
               # Internal libtiff/libgeotiff/libjson: three builds instead of six, and no more
               # third-party sources to keep patched.
               '-DGDAL_USE_INTERNAL_LIBS=ON',
               '-DGDAL_USE_EXTERNAL_LIBS=OFF',
               '-DBUILD_APPS=OFF',
               '-DBUILD_TESTING=OFF',
               '-DBUILD_PYTHON_BINDINGS=OFF',
               '-DBUILD_JAVA_BINDINGS=OFF',
               '-DBUILD_CSHARP_BINDINGS=OFF',
               '-DGDAL_BUILD_OPTIONAL_DRIVERS=OFF',
               '-DOGR_BUILD_OPTIONAL_DRIVERS=OFF']
    options += ['-DGDAL_ENABLE_DRIVER_%s=ON' % d.upper() for d in RASTER_DRIVERS]
    options += ['-DOGR_ENABLE_DRIVER_%s=ON' % d.upper() for d in VECTOR_DRIVERS]
    run(options + toolchain_args(args, abi))
    run(['cmake', '--build', build, '--target', 'install', '--parallel', str(args.jobs)])


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser(description='Cross-build GDAL for Android')
    parser.add_argument('--ndk', default=os.environ.get('ANDROID_NDK_HOME'),
                        help='NDK root (default: $ANDROID_NDK_HOME)')
    parser.add_argument('--abi', dest='abis', action='append', choices=ABIS,
                        help='ABI to build, repeatable (default: all)')
    parser.add_argument('--api', type=int, default=21,
                        help='Android API level. MUST match what build-android.py uses')
    parser.add_argument('--output', default=os.path.join(here, '..', 'build', 'gdal'),
                        help='Where the per-ABI prefixes go')
    parser.add_argument('--host-sqlite3', default=shutil.which('sqlite3'),
                        help="Host sqlite3 BINARY - PROJ's build runs it to generate proj.db")
    parser.add_argument('--jobs', type=int, default=os.cpu_count() or 4)
    args = parser.parse_args()

    args.base = os.path.abspath(os.path.join(here, '..'))
    if not args.ndk or not os.path.isdir(args.ndk):
        sys.exit('NDK not found - pass --ndk or set ANDROID_NDK_HOME')
    if not args.host_sqlite3:
        sys.exit("No host sqlite3 on PATH - PROJ's build needs one to generate proj.db")

    abis = args.abis or ABIS
    workDir = os.path.abspath(os.path.join(args.output, '_work'))
    os.makedirs(workDir, exist_ok=True)

    for abi in abis:
        prefix = os.path.abspath(os.path.join(args.output, abi))
        print('\n=== %s -> %s ===\n' % (abi, prefix))
        build_sqlite(args, abi, prefix, workDir)
        build_proj(args, abi, prefix, workDir)
        build_gdal(args, abi, prefix, workDir)

    # One copy is enough: proj.db is architecture-independent, and the app ships one of it.
    db = os.path.join(args.output, abis[0], 'share', 'proj', 'proj.db')
    if os.path.exists(db):
        shutil.copyfile(db, os.path.join(args.output, 'proj.db'))
        print('\nproj.db -> %s (%.1f MB) - ship this with the app, see docs/features/gdal-ogr.md'
              % (os.path.join(args.output, 'proj.db'), os.path.getsize(db) / 1e6))
    else:
        print('\nWARNING: no proj.db at %s - GDAL will fail every EPSG lookup' % db)

    print('\nDone. Build the SDK with:')
    print('  python3 build-android.py --profile "standard+gdal" \\')
    print('      --cmake-options "CMAKE_PREFIX_PATH=%s/{abi}"' % os.path.abspath(args.output))


if __name__ == '__main__':
    main()
