#!/usr/bin/env python3
"""
Turns massif-api.json into completing constants for the languages that have no literal types.

Three outputs, one idea: the facade's strings become real symbols, so an editor can offer them.

  Objective-C / Swift   MassifApiNames.h   NS_TYPED_ENUM - Swift sees `.opacity`, not a string
  Java / Kotlin         ApiNames.java      Key<T> constants, so the VALUE type is checked too
  C                     massif_api_names.h an enum of ids, which also skips the string lookup

Property NAMES rather than full paths, deliberately: a path is a name joined by dots, and the same
"opacity" works on every class that has one - which is how the facade itself behaves. The
class-scoped, path-aware version of this only exists in TypeScript, where literal types make it
free (see docs/internals/api-autocompletion.md).

  python3 scripts/gen-api-constants.py
"""

import argparse
import json
import os
import re

# Java's Key<T> needs a boxed type per property type. ENUM is a String because the facade takes
# the constant's NAME; COLOR is an int because that is what the SDK stores (0xAARRGGBB).
JAVA_TYPES = {
  'BOOL': 'Boolean', 'INT': 'Long', 'FLOAT': 'Double', 'COLOR': 'Integer',
  'STRING': 'String', 'ENUM': 'String', 'STRUCT': 'String', 'VARIANT': 'String',
  'OBJECT': 'MassifObject',
}


def camel(name):
  """opacity -> Opacity, map.clicked -> MapClicked, composite-vector -> CompositeVector."""
  parts = re.split(r'[^A-Za-z0-9]+', name)
  return ''.join(part[:1].upper() + part[1:] for part in parts if part)


def screaming(name):
  """rangeStart -> RANGE_START, map.clicked -> MAP_CLICKED."""
  name = re.sub(r'[^A-Za-z0-9]+', '_', name)
  return re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', name).upper()


def collect(schema):
  """Distinct names, with a doc and (for a property) the type they carry."""
  properties, methods, events = {}, {}, {}
  for entry in schema['classes'].values():
    for prop in entry['properties']:
      known = properties.setdefault(prop['name'], {'type': prop['type'], 'doc': prop.get('doc'),
                                                   'classes': []})
      known['classes'].append(entry)
      # The same name on two classes may carry different types - "source" is an OBJECT on a layer
      # and a STRING nowhere, but "size" is a FLOAT here and an INT there. Widen to a string key
      # rather than pick one and be wrong half the time.
      if known['type'] != prop['type']:
        known['type'] = 'STRUCT'
      if not known['doc']:
        known['doc'] = prop.get('doc')
    for method in entry['methods']:
      methods.setdefault(method['name'], method)
    for event in entry['events']:
      events.setdefault(event['name'], event)
  return properties, methods, events


def emitObjC(schema, properties, methods, events, outPath):
  """
  NS_TYPED_ENUM: ObjC gets completing constants, and SWIFT gets `.opacity`.

  This is the cheapest win of the set - one generated header, and neither language sees a raw
  string again. The Swift side is a struct with static members, so it completes and type-checks
  without any Swift code being generated at all.
  """
  lines = [
    '// Generated by scripts/gen-api-constants.py. Do not edit.\n',
    '//\n',
    '// The facade\'s strings as typed constants. In Swift these arrive as MassifProperty.opacity\n',
    '// and friends, so nothing has to spell a string out.\n\n',
    '#import <Foundation/Foundation.h>\n\n',
    'NS_ASSUME_NONNULL_BEGIN\n\n',
  ]
  groups = [
    ('MassifProperty', 'a property path segment', sorted(properties),
     lambda n: properties[n].get('doc')),
    ('MassifMethod', 'a method name', sorted(methods), lambda n: None),
    ('MassifEvent', 'an event name', sorted(events), lambda n: None),
    ('MassifKind', 'an object kind', sorted(schema['kinds']), lambda n: None),
  ]
  for typeName, what, names, docOf in groups:
    lines.append('/** %s. */\n' % what.capitalize())
    lines.append('typedef NSString *%s NS_TYPED_ENUM;\n\n' % typeName)
    for name in names:
      doc = docOf(name)
      if doc:
        lines.append('/** %s */\n' % doc)
      lines.append('FOUNDATION_EXPORT %s const %s%s;\n' % (typeName, typeName, camel(name)))
    lines.append('\n')

  # The spec types, per kind, so "which types does a source have" is answerable in the editor.
  lines.append('/** The types a kind can build. */\ntypedef NSString *MassifSpecType NS_TYPED_ENUM;\n\n')
  for spec in schema['specs']:
    lines.append('FOUNDATION_EXPORT MassifSpecType const MassifSpecType%s%s;\n'
                 % (camel(spec['kind']), camel(spec['type'])))
  lines.append('\nNS_ASSUME_NONNULL_END\n')
  write(outPath, ''.join(lines))

  # The .m, because a typed enum needs its constants to exist somewhere.
  body = [
    '// Generated by scripts/gen-api-constants.py. Do not edit.\n\n',
    '#import "MassifApiNames.h"\n\n',
  ]
  for typeName, _, names, _ in groups:
    for name in names:
      body.append('%s const %s%s = @"%s";\n' % (typeName, typeName, camel(name), name))
  for spec in schema['specs']:
    body.append('MassifSpecType const MassifSpecType%s%s = @"%s";\n'
                % (camel(spec['kind']), camel(spec['type']), spec['type']))
  write(outPath[:-2] + '.m', ''.join(body))


def emitJava(schema, properties, methods, events, outPath, package):
  """
  Key<T> constants: completion, and the VALUE type checked with it.

  Java has no literal types, so a plain String constant would complete and then let a colour be
  passed to a float. Key<T> makes set(Key<Double>, double) the only overload that compiles.
  """
  lines = [
    '// Generated by scripts/gen-api-constants.py. Do not edit.\n',
    'package %s;\n\n' % package,
    '/**\n',
    ' * The facade\'s names, as constants an editor can complete.\n',
    ' *\n',
    ' * A {@link MassifObject.Key} carries the value type with it, so the compiler rejects a\n',
    ' * colour written to a float. A path is these joined by dots - "fogOptions." + RANGE_START -\n',
    ' * and the plain string still works for anything this file predates.\n',
    ' */\n',
    'public final class ApiNames {\n\n',
  ]
  for name in sorted(properties):
    prop = properties[name]
    javaType = JAVA_TYPES.get(prop['type'], 'String')
    if prop.get('doc'):
      lines.append('    /** %s */\n' % prop['doc'])
    lines.append('    public static final MassifObject.Key<%s> %s = MassifObject.key("%s");\n'
                 % (javaType, screaming(name), name))
  lines.append('\n    // --- methods ---------------------------------------------------------\n\n')
  for name in sorted(methods):
    lines.append('    public static final String METHOD_%s = "%s";\n' % (screaming(name), name))
  lines.append('\n    // --- events ----------------------------------------------------------\n\n')
  for name in sorted(events):
    lines.append('    public static final String EVENT_%s = "%s";\n' % (screaming(name), name))
  lines.append('\n    // --- kinds and spec types --------------------------------------------\n\n')
  for kind in sorted(schema['kinds']):
    lines.append('    public static final String KIND_%s = "%s";\n' % (screaming(kind), kind))
  for spec in schema['specs']:
    lines.append('    public static final String TYPE_%s_%s = "%s";\n'
                 % (screaming(spec['kind']), screaming(spec['type']), spec['type']))
  lines.append('\n    private ApiNames() {\n    }\n}\n')
  write(outPath, ''.join(lines))


def emitC(schema, properties, methods, events, outPath):
  """
  An enum of ids, plus the string table that maps them back.

  The C ABI is the one place this is not only about completion: an id skips the per-call string
  lookup, so a caller in a loop pays an array index instead of a hash.
  """
  lines = [
    '/* Generated by scripts/gen-api-constants.py. Do not edit. */\n',
    '#ifndef MASSIF_API_NAMES_H\n#define MASSIF_API_NAMES_H\n\n',
    '#ifdef __cplusplus\nextern "C" {\n#endif\n\n',
    '/* Property names, as ids. massif_property_name() maps one back to its string. */\n',
    'typedef enum {\n',
  ]
  names = sorted(properties)
  # A DIFFERENT prefix for the sentinel: there is a property called "count", and
  # MASSIF_PROP_COUNT was a redefinition of it.
  seen = {}
  for index, name in enumerate(names):
    symbol = 'MASSIF_PROP_%s' % screaming(name)
    if symbol in seen:
      print('warning: %s and %s both spell %s' % (seen[symbol], name, symbol))
    seen[symbol] = name
    lines.append('    %s = %d,\n' % (symbol, index))
  lines.append('    MASSIF_PROPERTY_TOTAL = %d\n} massif_property;\n\n' % len(names))
  lines.append('/* The string a property id stands for, or NULL when the id is out of range. */\n')
  lines.append('const char* massif_property_name(massif_property property);\n\n')
  for prefix, group in (('MASSIF_METHOD', sorted(methods)), ('MASSIF_EVENT', sorted(events)),
                        ('MASSIF_KIND', sorted(schema['kinds']))):
    for name in group:
      lines.append('#define %s_%s "%s"\n' % (prefix, screaming(name), name))
    lines.append('\n')
  lines.append('#ifdef __cplusplus\n}\n#endif\n\n#endif\n')
  write(outPath, ''.join(lines))

  body = ['/* Generated by scripts/gen-api-constants.py. Do not edit. */\n',
          '#include "massif_api_names.h"\n#include <stddef.h>\n\n',
          'static const char* const kNames[] = {\n']
  for name in names:
    body.append('    "%s",\n' % name)
  body.append('};\n\n')
  body.append('const char* massif_property_name(massif_property property) {\n')
  body.append('    if (property < 0 || property >= MASSIF_PROPERTY_TOTAL) {\n        return NULL;\n    }\n')
  body.append('    return kNames[property];\n}\n')
  write(outPath[:-2] + '.c', ''.join(body))


def write(path, content):
  os.makedirs(os.path.dirname(path), exist_ok=True)
  if os.path.exists(path):
    with open(path) as f:
      if f.read() == content:
        return
  with open(path, 'w') as f:
    f.write(content)


here = os.path.dirname(os.path.abspath(__file__))
parser = argparse.ArgumentParser()
parser.add_argument('--schema', default=os.path.join(here, '../docs/api/massif-api.json'))
parser.add_argument('--objc', default=os.path.join(here, '../ios/objc/api/MassifApiNames.h'))
parser.add_argument('--java', default=os.path.join(
    here, '../android/java/com/massifmaps/api/ApiNames.java'))
parser.add_argument('--package', default='com.massifmaps.api')
parser.add_argument('--c', dest='cHeader', default=os.path.join(here, '../all/native/api/massif_api_names.h'))
args = parser.parse_args()

with open(args.schema) as f:
  schema = json.load(f)
properties, methods, events = collect(schema)
emitObjC(schema, properties, methods, events, args.objc)
emitJava(schema, properties, methods, events, args.java, args.package)
emitC(schema, properties, methods, events, args.cHeader)
print('%d property names, %d methods, %d events, %d kinds, %d spec types'
      % (len(properties), len(methods), len(events), len(schema['kinds']), len(schema['specs'])))
