#!/usr/bin/env python3
"""Emit the facade API's property table from the Swig attribute macros.

The macros in all/modules/**/*.i already declare every settable property of every wrapped class,
so the facade's `set`/`get` paths are derived from them rather than hand-listed - a new setter
becomes a new path on the next build, and nothing is ever maintained twice.

Output is data only: path, value type, flags and the accessor NAMES. Binding those names to real
member functions needs the class headers and belongs with the target resolution, not here.
"""

import argparse
import os
import re
import sys

# Macro -> whether the declared value is an object reference rather than a value.
ATTRIBUTE_MACROS = {
    'attribute': False,
    'attributeval': False,
    'attributestring': False,
    'attributestring_polymorphic': True,
    'staticattribute': False,
    'staticattributestring': False,
    'staticattributestring_polymorphic': True,
}

BOOL_TYPES = {'bool'}
INT_TYPES = {'int', 'long', 'long long', 'short', 'char', 'signed char', 'unsigned char',
             'unsigned int', 'unsigned long', 'unsigned short', 'size_t', 'std::size_t'}
FLOAT_TYPES = {'float', 'double'}

TYPE_NAMES = ['BOOL', 'INT', 'FLOAT', 'COLOR', 'ENUM', 'STRING', 'OBJECT', 'STRUCT']

FLAG_READONLY = 1
FLAG_STATIC = 2


def splitArgs(text):
  """Split a macro argument list on top-level commas, respecting <> and ()."""
  args, depth, current = [], 0, ''
  for ch in text:
    if ch in '<([':
      depth += 1
    elif ch in '>)]':
      depth -= 1
    if ch == ',' and depth == 0:
      args.append(current.strip())
      current = ''
    else:
      current += ch
  if current.strip():
    args.append(current.strip())
  return args


def stripArgMacro(cppType):
  # %arg(...) only exists to hide commas from the Swig preprocessor.
  match = re.match(r'^%arg\s*\((.*)\)$', cppType.strip())
  return match.group(1).strip() if match else cppType.strip()


def classifyType(cppType, polymorphic):
  if polymorphic:
    return 'OBJECT'
  cppType = stripArgMacro(cppType)
  if cppType in BOOL_TYPES:
    return 'BOOL'
  if cppType in INT_TYPES:
    return 'INT'
  if cppType in FLOAT_TYPES:
    return 'FLOAT'
  if cppType == 'massif::Color':
    return 'COLOR'
  if cppType == 'std::string':
    return 'STRING'
  if cppType.startswith('std::shared_ptr<'):
    return 'OBJECT'
  # namespace and enum share a name by convention: massif::PanningMode::PanningMode
  match = re.match(r'^massif::(\w+)::(\w+)$', cppType)
  if match and match.group(1) == match.group(2):
    return 'ENUM'
  return 'STRUCT'


def decapitalize(name):
  # java.beans.Introspector rule: an acronym keeps its case, so HTTPHeaders stays HTTPHeaders
  # while RangeStart becomes rangeStart. Predictable is what matters - readable spellings are
  # the alias table's job.
  if len(name) > 1 and name[0].isupper() and name[1].isupper():
    return name
  return name[0].lower() + name[1:] if name else name


def parseModules(sourceDirs):
  entries = []
  pattern = re.compile(r'^\s*[%!](' + '|'.join(sorted(ATTRIBUTE_MACROS, key=len, reverse=True)) +
                       r')\s*\((.*)\)\s*$')
  for sourceDir in sourceDirs:
    if not os.path.isdir(sourceDir):
      continue
    for root, _, fileNames in os.walk(sourceDir):
      for fileName in sorted(fileNames):
        if not fileName.endswith('.i'):
          continue
        with open(os.path.join(root, fileName)) as f:
          for line in f:
            match = pattern.match(line.rstrip('\n'))
            if not match:
              continue
            macro, args = match.group(1), splitArgs(match.group(2))
            if len(args) < 4:
              print('warning: %s: cannot parse %s(%s)' % (fileName, macro, match.group(2)))
              continue
            cppClass, cppType, name, getter = args[0], args[1], args[2], args[3]
            setter = args[4] if len(args) > 4 and args[4] else ''
            flags = 0
            if not setter:
              flags |= FLAG_READONLY
            if macro.startswith('static'):
              flags |= FLAG_STATIC
            entries.append({
              'cppClass': cppClass,
              'path': decapitalize(name),
              'type': classifyType(cppType, ATTRIBUTE_MACROS[macro]),
              'flags': flags,
              'getter': getter,
              'setter': setter,
            })
  return entries


def emit(entries, outPath):
  byClass = {}
  for entry in entries:
    byClass.setdefault(entry['cppClass'], {})[entry['path']] = entry

  lines = [
    '// Generated by scripts/gen-api-tables.py. Do not edit.\n',
    '// One row per Swig attribute macro; see all/native/api/PropertyTable.h.\n',
    '\n',
  ]
  for cppClass in sorted(byClass):
    symbol = re.sub(r'\W', '_', cppClass)
    lines.append('static const PropertyEntry kProps_%s[] = {\n' % symbol)
    for path in sorted(byClass[cppClass]):
      entry = byClass[cppClass][path]
      lines.append('    { "%s", PT_%s, %d, "%s", "%s" },\n' %
                   (path, entry['type'], entry['flags'], entry['getter'], entry['setter']))
    lines.append('};\n\n')

  lines.append('static const ClassEntry kClasses[] = {\n')
  for cppClass in sorted(byClass):
    symbol = re.sub(r'\W', '_', cppClass)
    lines.append('    { "%s", kProps_%s, %d },\n' % (cppClass, symbol, len(byClass[cppClass])))
  lines.append('};\n')

  if not os.path.isdir(os.path.dirname(outPath)):
    os.makedirs(os.path.dirname(outPath))
  with open(outPath, 'w') as f:
    f.writelines(lines)
  return byClass


parser = argparse.ArgumentParser()
parser.add_argument('--sourcedir', dest='sourceDir', default='../all/modules;../android/modules',
                    help='input directories containing subdirectories of Swig wrappers')
parser.add_argument('--outdir', dest='outDir', default='../generated/api',
                    help='output directory for the generated tables')
args = parser.parse_args()

entries = parseModules(args.sourceDir.split(';'))
if not entries:
  print('No attribute macros found - is --sourcedir right?')
  sys.exit(-1)

byClass = emit(entries, os.path.join(args.outDir, 'PropertyTable.inc'))

counts = {}
for entry in entries:
  counts[entry['type']] = counts.get(entry['type'], 0) + 1
readOnly = sum(1 for entry in entries if entry['flags'] & FLAG_READONLY)
print('%d properties over %d classes (%d read-only)' % (len(entries), len(byClass), readOnly))
print('  ' + '  '.join('%s=%d' % (name, counts[name]) for name in TYPE_NAMES if name in counts))
