#!/usr/bin/env python3
"""
Turns massif-api.json into a TypeScript declaration file.

The facade takes strings, so nothing in it completes on its own. TypeScript is the one target
where the fix is total: a literal-type union completes AND checks, so `set(h, "opacty", 1)` is a
compile error rather than a warning in the log.

The whole property closure is 1,169 paths (see docs/internals/api-autocompletion.md), which is
nothing for a union - the reflex worry about generating one does not survive the measurement.

  python3 scripts/gen-api-typescript.py --schema docs/api/massif-api.json \\
      --out bindings/typescript/massif.d.ts
"""

import argparse
import json
import os

# How far a dotted path may walk into object properties. The closure converges at 3; 4 adds 26
# paths out of 1,195 and doubles nothing, so this is a cap for safety rather than a real limit.
MAX_DEPTH = 3

SCALARS = {
  'BOOL': 'boolean',
  'INT': 'number',
  'FLOAT': 'number',
  'COLOR': 'number',
  'STRING': 'string',
  'VARIANT': 'Json',
}

# The by-value structs the codec moves as JSON. Anything not here is opaque: it has no accessor
# either, so a path that reaches one cannot be read in any language.
STRUCTS = {
  'massif::MapPos': 'Position',
  'massif::MapVec': 'Position',
  'massif::ScreenPos': '[number, number]',
  'massif::MapRange': '[number, number]',
  'massif::MapBounds': 'Bounds',
  'massif::MapTile': 'Tile',
  'massif::ClickInfo': 'ClickInfo',
  'std::vector<std::string>': 'string[]',
  'std::map<std::string, std::string>': 'Record<string, string>',
  'std::map<std::string, massif::Variant>': 'Record<string, Json>',
}

PRELUDE = '''// Generated by scripts/gen-api-typescript.py. Do not edit.
//
// Types for the Massif Maps facade API. Every function here is one of the six verbs underneath;
// the types exist so an editor can complete a property path, a spec key, a method name and an
// event name, and so a wrong value is a compile error.

export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };

/** [lon, lat] or [lon, lat, altitude], in the object's own projection. */
export type Position = [number, number] | [number, number, number];
export type Bounds = [Position, Position];
/** [x, y, zoom]. */
export type Tile = [number, number, number];
export interface ClickInfo { clickType: number; }

/**
 * A registered object.
 *
 * The number is the handle the C++ side uses; the phantom member is erased at runtime and exists
 * so a source handle cannot be passed where a layer handle belongs.
 */
export type Handle<C extends ClassName = ClassName> = number & { readonly __massif: C };
'''


def tsName(cppClass):
  return cppClass.replace('massif::', '')


def enumType(name, enums):
  """A string union of the constant names, which is what an app should be writing."""
  values = enums.get(name)
  if not values:
    return 'number'
  return ' | '.join('"%s"' % value['name'] for value in values)


def valueType(prop, enums):
  if prop['type'] in SCALARS:
    return SCALARS[prop['type']]
  if prop['type'] == 'ENUM':
    return enumType(prop.get('enum', ''), enums)
  if prop['type'] == 'OBJECT':
    return 'Handle<"%s">' % prop['objectClass']
  if prop['type'] == 'STRUCT':
    # Json, not unknown: these interfaces carry a Json index signature and an
    # opaque struct has to satisfy it.
    return STRUCTS.get(prop['cppType'], 'Json')
  return 'unknown'


def ownProperties(cppClass, classes):
  """A class' properties plus every base's, nearest first."""
  out, seen = [], set()
  while cppClass:
    entry = classes.get(cppClass)
    if not entry:
      break
    for prop in entry['properties']:
      if prop['name'] not in seen:
        seen.add(prop['name'])
        out.append(prop)
    cppClass = entry['base']
  return out


def closure(cppClass, classes, enums, depth=MAX_DEPTH, prefix='', stack=()):
  """Every legal dotted path from a class, with the type at the end of it."""
  if depth == 0 or cppClass in stack:
    return {}
  paths = {}
  for prop in ownProperties(cppClass, classes):
    path = prefix + prop['name']
    paths[path] = (valueType(prop, enums), prop.get('doc'), prop['readOnly'])
    if prop['type'] == 'OBJECT':
      paths.update(closure(prop['objectClass'], classes, enums, depth - 1,
                           path + '.', stack + (cppClass,)))
  return paths


ARG_TYPES = {
  'bool': 'boolean', 'int': 'number', 'float': 'number', 'string': 'string',
  'tile': 'Tile', 'pos': 'Position', 'positions': 'Position[]', 'handle': 'Handle', 'json': 'Json',
}
RETURN_TYPES = {
  'void': 'void', 'bool': 'boolean', 'int': 'number', 'float': 'number', 'string': 'string',
  'json': 'Json', 'doubles': 'number[]',
}


def methodSignature(method):
  args = ', '.join('%s: %s' % (a['name'], ARG_TYPES.get(a['type'], 'unknown'))
                   for a in method['args'])
  if method['returns'] == 'object':
    result = 'Handle<"%s">' % method['returnClass'] if method['returnClass'] else 'Handle'
  else:
    result = RETURN_TYPES.get(method['returns'], 'unknown')
  return '(%s) => %s' % (args, result)


def emit(schema, outPath):
  classes, enums = schema['classes'], schema['enums']
  named = sorted(classes)
  lines = [PRELUDE, '\n']

  lines.append('export type ClassName =\n')
  for cppClass in named:
    lines.append('  | "%s"\n' % cppClass)
  lines.append('  ;\n\n')

  # Enums, as string unions plus the numeric value the C++ side actually stores.
  if enums:
    lines.append('// --- enums ---------------------------------------------------------------\n\n')
    for name, values in sorted(enums.items()):
      lines.append('export type %s =\n' % tsName(name).replace('::', ''))
      for value in values:
        if value.get('doc'):
          lines.append('  /** %s */\n' % value['doc'])
        lines.append('  | "%s"\n' % value['name'])
      lines.append('  ;\n\n')

  lines.append('// --- properties ----------------------------------------------------------\n')
  lines.append('//\n// One entry per class: every path reachable from it, and the type at the '
               'end.\n\n')
  lines.append('export interface PropertyTypes {\n')
  total = 0
  for cppClass in named:
    paths = closure(cppClass, classes, enums)
    total += len(paths)
    lines.append('  "%s": {\n' % cppClass)
    for path in sorted(paths):
      valueTypeName, doc, readOnly = paths[path]
      if doc:
        lines.append('    /** %s%s */\n' % ('(read-only) ' if readOnly else '', doc))
      lines.append('    %s"%s": %s;\n' % ('readonly ' if readOnly else '', path, valueTypeName))
    lines.append('  };\n')
  lines.append('}\n\n')

  lines.append('''export type Path<C extends ClassName> = keyof PropertyTypes[C] & string;
export type ValueAt<C extends ClassName, P extends Path<C>> = PropertyTypes[C][P];

/*
 * The paths that are NOT read-only.
 *
 * `readonly` on an interface member only stops direct assignment - it does nothing about
 * set(handle, path, value), where the path is just a string. This is the standard
 * writable-keys probe: two identical mapped types that differ only in `readonly` are assignable
 * to each other exactly when the key is writable.
 */
type IfWritable<T, K extends keyof T, Yes, No> =
  (<G>() => G extends { [Q in K]: T[K] } ? 1 : 2) extends
  (<G>() => G extends { readonly [Q in K]: T[K] } ? 1 : 2) ? No : Yes;

export type WritablePath<C extends ClassName> = {
  [K in keyof PropertyTypes[C]]-?: IfWritable<PropertyTypes[C], K, K, never>
}[keyof PropertyTypes[C]] & string;

''')

  # --- specs -----------------------------------------------------------------------------------
  lines.append('// --- specs ---------------------------------------------------------------\n')
  lines.append('//\n// A spec\'s keys are its constructor parameters plus any writable property\n'
               '// of the class it builds - the factory consumes what it needs and the rest is\n'
               '// applied as properties, at any nesting depth.\n\n')
  byKind = {}
  for spec in schema['specs']:
    byKind.setdefault(spec['kind'], []).append(spec)
  for kind in sorted(byKind):
    names = []
    for spec in sorted(byKind[kind], key=lambda s: s['type']):
      name = '%sSpec_%s' % (kind.capitalize().replace('-', ''), spec['type'].replace('-', '_'))
      names.append(name)
      # One entry per KEY. A constructor argument and a writable property can share a name
      # (a source's "url", a popup's "description"), and declaring it twice is a type error.
      keys = {}
      for prop in ownProperties(spec['cppClass'], classes):
        if prop['readOnly']:
          continue
        key = spec['aliases'].get(prop['name'], prop['name'])
        keys[key] = [valueType(prop, enums), prop.get('doc')]
      # Every CONSTRUCTOR argument too, across all overloads. One that is neither aliased nor a
      # writable property - LocalVectorDataSource's projection - appears nowhere else, and its
      # absence made the spec type quietly wrong rather than merely incomplete.
      for overload in spec.get('constructors', []):
        for param in overload:
          if param['type'] == 'OBJECT':
            # A child may be built inline OR named by the id it was registered under.
            childType = '%sSpec | string' % param['childKind'].capitalize().replace('-', '') \
                if param['childKind'] else 'string | Record<string, Json>'
          else:
            childType = valueType({'type': param['type'], 'cppType': param['cppType'],
                                   'enum': param['cppType']}, enums)
          if param['key'] in keys and keys[param['key']][0] != childType:
            keys[param['key']][0] = '%s | %s' % (keys[param['key']][0], childType)
          elif param['key'] not in keys:
            keys[param['key']] = [childType, None]
      lines.append('export interface %s {\n' % name)
      lines.append('  type: "%s";\n' % spec['type'])
      for key in sorted(keys):
        valueTypeName, doc = keys[key]
        if doc:
          lines.append('  /** %s */\n' % doc)
        lines.append('  %s?: %s;\n' % (key, valueTypeName))
      # NO index signature. One would make every spec accept every key, so a typo - maxZom for
      # maxZoom - would type-check, which is most of what these types are for. A key from a
      # newer SDK is passed with a cast instead.
      lines.append('}\n\n')
    union = '%sSpec' % kind.capitalize().replace('-', '')
    lines.append('export type %s = %s;\n\n' % (union, ' | '.join(names) if names else 'never'))

  # A kind whose objects come from a HAND-WRITTEN factory ("projection", "data") declares no
  # constructible types, so no interface was emitted for it - but a constructor child can still
  # point at one. An open shape rather than a dangling name: the keys are real, they are simply
  # not in the schema, and inventing a per-kind special case here is what the generator exists
  # to avoid.
  referenced = {param['childKind']
                for spec in schema['specs']
                for overload in spec.get('constructors', [])
                for param in overload
                if param.get('childKind')}
  for kind in sorted(referenced - set(byKind)):
    lines.append('/** Built by a hand-written factory, so its keys are not in the schema. */\n')
    lines.append('export type %sSpec = { type: string; [key: string]: Json | undefined };\n\n'
                 % kind.capitalize().replace('-', ''))

  lines.append('export interface SpecOf {\n')
  for kind in sorted(byKind):
    lines.append('  "%s": %sSpec;\n' % (kind, kind.capitalize().replace('-', '')))
  lines.append('}\n')
  lines.append('export type Kind = keyof SpecOf & string;\n\n')

  # --- methods and events ----------------------------------------------------------------------
  lines.append('// --- methods -------------------------------------------------------------\n\n')
  lines.append('export interface MethodTypes {\n')
  for cppClass in named:
    methods, walk = {}, cppClass
    while walk:
      entry = classes.get(walk)
      if not entry:
        break
      for method in entry['methods']:
        # setdefault: VectorTileFeatureCollection.getFeature narrows FeatureCollection's, and
        # declaring both is a type error rather than an override.
        methods.setdefault(method['name'], method)
      walk = entry['base']
    lines.append('  "%s": {\n' % cppClass)
    for name in sorted(methods):
      lines.append('    %s: %s;\n' % (name, methodSignature(methods[name])))
    lines.append('  };\n')
  lines.append('}\n\n')
  lines.append('export type MethodName<C extends ClassName> = keyof MethodTypes[C] & string;\n\n')

  lines.append('// --- events --------------------------------------------------------------\n\n')
  lines.append('export interface EventTypes {\n')
  for cppClass in named:
    events, walk = {}, cppClass
    while walk:
      entry = classes.get(walk)
      if not entry:
        break
      for event in entry['events']:
        events.setdefault(event['name'], event)
      walk = entry['base']
    lines.append('  "%s": {\n' % cppClass)
    for name in sorted(events):
      event = events[name]
      payload = 'Handle<"%s">' % event['payload'] if event['payload'] else 'null'
      lines.append('    "%s": %s;\n' % (name, payload))
    lines.append('  };\n')
  lines.append('}\n\n')
  lines.append('export type EventName<C extends ClassName> = keyof EventTypes[C] & string;\n\n')

  # --- the verbs -------------------------------------------------------------------------------
  lines.append('''// --- the API -------------------------------------------------------------

export declare function create<K extends Kind>(kind: K, id: string, spec: SpecOf[K]): Handle;

export declare function set<C extends ClassName, P extends WritablePath<C>>(
  handle: Handle<C>, path: P, value: ValueAt<C, P>): void;

export declare function get<C extends ClassName, P extends Path<C>>(
  handle: Handle<C>, path: P): ValueAt<C, P>;

export declare function call<C extends ClassName, M extends MethodName<C>>(
  handle: Handle<C>, method: M,
  ...args: Parameters<MethodTypes[C][M] extends (...a: any) => any ? MethodTypes[C][M] : never>
): ReturnType<MethodTypes[C][M] extends (...a: any) => any ? MethodTypes[C][M] : never>;

export declare function on<C extends ClassName, E extends EventName<C>>(
  handle: Handle<C>, event: E,
  handler: (payload: EventTypes[C][E]) => void): number;

export declare function off(subscription: number): boolean;
export declare function destroy(handle: Handle): boolean;
''')

  os.makedirs(os.path.dirname(outPath), exist_ok=True)
  with open(outPath, 'w') as f:
    f.writelines(lines)
  return total


here = os.path.dirname(os.path.abspath(__file__))
parser = argparse.ArgumentParser()
parser.add_argument('--schema', default=os.path.join(here, '../docs/api/massif-api.json'))
parser.add_argument('--out', default=os.path.join(here, '../bindings/typescript/massif.d.ts'))
args = parser.parse_args()

with open(args.schema) as f:
  schema = json.load(f)
paths = emit(schema, args.out)
print('%s: %d classes, %d paths, %d specs, %d enums'
      % (os.path.relpath(args.out), len(schema['classes']), paths, len(schema['specs']),
         len(schema['enums'])))
