#!/bin/sh
# Regenerates every generated artefact of the facade API surface, in dependency order.
#
#   scripts/gen-api-bindings.sh            regenerate in place
#   scripts/gen-api-bindings.sh --check    regenerate and fail if anything changed
#
# ONE entry point on purpose. The C++ property table is generated by CMake on every build, so it
# cannot drift; these four are not, and they did - a class added to all/modules never reached the
# TypeScript typing, the Objective-C constants or the C enum until somebody remembered to run three
# scripts by hand. --check is what CI runs, so "somebody remembered" stops being the mechanism.
#
# What it writes, all committed:
#   docs/api/massif-api.json                       the schema everything else is generated FROM
#   bindings/typescript/massif.d.ts                NativeScript / React Native / WASM typings
#   ios/objc/api/MassifApiNames.{h,m}              NS_TYPED_ENUM constants (Swift: .opacity)
#   android/java/com/massifmaps/api/ApiNames.java  typed Key<T> constants
#   all/native/api/massif_api_names.{h,c}          C ABI enum ids
set -e

cd "$(dirname "$0")"

# --profile full, not the default 'standard': these artefacts describe the API surface to an
# INTEGRATION, which links whatever profile it likes. Generated as 'standard' they silently lose
# routing, valhalla, geocoding and packagemanager, and a binding cannot tell that from "removed".
python3 gen-api-tables.py --profile full --schema ../docs/api/massif-api.json
python3 gen-api-typescript.py
python3 gen-api-constants.py

if [ "$1" = "--check" ]; then
    cd ..
    if ! git diff --quiet -- docs/api/massif-api.json bindings/typescript/massif.d.ts \
            ios/objc/api/MassifApiNames.h ios/objc/api/MassifApiNames.m \
            android/java/com/massifmaps/api/ApiNames.java \
            all/native/api/massif_api_names.h all/native/api/massif_api_names.c; then
        echo ""
        echo "The generated API bindings are out of date. Run scripts/gen-api-bindings.sh and"
        echo "commit the result - an integration reads these, and a stale one is a missing class."
        echo ""
        git --no-pager diff --stat -- docs/api/massif-api.json bindings/typescript/massif.d.ts \
            ios/objc/api/MassifApiNames.h ios/objc/api/MassifApiNames.m \
            android/java/com/massifmaps/api/ApiNames.java \
            all/native/api/massif_api_names.h all/native/api/massif_api_names.c
        exit 1
    fi
    echo "generated API bindings are up to date"
fi
