// Generated by scripts/gen-examples.py. Do not edit.
package com.massifmaps.MassifDemo.examples;

/**
 * Every example, in gallery order.
 *
 * Generated from the @ExampleInfo annotations rather than scanned at runtime: Android has no
 * cheap way to enumerate a package, and a list nobody maintains cannot go stale.
 */
public final class ExampleRegistry {

    public static final Class<?>[] ALL = {
        com.massifmaps.MassifDemo.examples.basics.DisplayMapExample.class,
        com.massifmaps.MassifDemo.examples.camera.FlyToExample.class,
        com.massifmaps.MassifDemo.examples.sources.GeoJsonLineExample.class,
        com.massifmaps.MassifDemo.examples.styles.StyleParametersExample.class,
        com.massifmaps.MassifDemo.examples.terrain.Terrain3DExample.class,
        com.massifmaps.MassifDemo.examples.terrain.Switch2D3DExample.class,
        com.massifmaps.MassifDemo.examples.terrain.AtmosphereExample.class,
        com.massifmaps.MassifDemo.examples.annotations.MarkersExample.class,
        com.massifmaps.MassifDemo.examples.interaction.FeatureClickExample.class,
        com.massifmaps.MassifDemo.examples.interaction.MapEventsExample.class,
        com.massifmaps.MassifDemo.examples.search.SearchFeaturesExample.class,
    };

    private ExampleRegistry() {
    }
}
